### ISSUE TITLE
[Support] I'm missing the traffic routed to the gateway

### ISSUE THREAD

**Issue by tassoman** [pivpn/pivpn#1195] opened 2020-12-08 14:22 UTC
## In raising this issue, I confirm the following: 

`{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting can be *is* directly related to the pivpn installer script.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pivpn/pivpn/wiki/FAQ), [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed), and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen)).

### Issue

Looks like routing to default gateway is not working. I can get udp traffic from client to raspberry and viceversa but I can't see any traffic between the client and the gateway or forwarded from the raspberry to the gateway.
Handshaking is keeping the connection alive between wireguard client/server.
Mine configuration is WireGuard running on default udp port, I dunno if the provider is blocking it, any chance to debug?
Router is 192.168.1.1
Raspberry is 192.168.1.4 (static ip)
DNS is raspberry pihole itself 
OS: is ubuntu server arm64

The amount of traffic is going up an down is like the DNS queries only.

This is a part of tcpdump
```
13:45:52.741779 IP (tos 0x0, ttl 44, id 62511, offset 0, flags [DF], proto UDP (17), length 156)
    37.161.x.x.34512 > pihole.aaa.bbb.com.51820: UDP, length 128
13:45:52.744292 IP (tos 0x0, ttl 64, id 35776, offset 0, flags [none], proto UDP (17), length 220)
    pihole.aaa.bbb.com.51820 > 37.161.x.x.34512: UDP, length 192
13:45:55.951398 IP (tos 0x0, ttl 44, id 62693, offset 0, flags [DF], proto UDP (17), length 140)
    37.161.x.x.34512 > pihole.aaa.bbb.com.51820: UDP, length 112
13:45:55.953538 IP (tos 0x0, ttl 64, id 36385, offset 0, flags [none], proto UDP (17), length 188)
    pihole.aaa.bbb.com.51820 > 37.161.x.x.34512: UDP, length 160
13:45:57.731629 IP (tos 0x0, ttl 44, id 62857, offset 0, flags [DF], proto UDP (17), length 156)
    37.161.x.x.34512 > pihole.aaa.bbb.com.51820: UDP, length 128
13:45:57.734236 IP (tos 0x0, ttl 64, id 36409, offset 0, flags [none], proto UDP (17), length 220)
    pihole.aaa.bbb.com.51820 > 37.161.x.x.34512: UDP, length 192
13:46:00.982036 IP (tos 0x0, ttl 44, id 62990, offset 0, flags [DF], proto UDP (17), length 140)
    37.161.x.x.34512 > pihole.aaa.bbb.com.51820: UDP, length 112

root@pihole:~# wg show wg0
interface: wg0
  public key: xxxxxxxxxxxxxxxxxxxxxxxxxxxx=
  private key: (hidden)
  listening port: 51820

peer: /yyyyyyyyyyyyyyyyyyyyyyyyyyyyyy=
  preshared key: (hidden)
  endpoint: 37.161.x.x:34512
  allowed ips: 10.6.0.2/32
  latest handshake: 1 minute, 3 seconds ago
  transfer: 24.88 KiB received, 44.36 KiB sent

root@pihole:~# sudo ufw status verbose
Status: inactive

root@pihole:~# route
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
default         192.168.1.1        0.0.0.0         UG    202    0        0 enxb827ebbeebe6
10.6.0.0        0.0.0.0         255.255.255.0   U     0      0        0 wg0
link-local      0.0.0.0         255.255.0.0     U     205    0        0 docker0
link-local      0.0.0.0         255.255.0.0     U     207    0        0 veth8d81027
172.17.0.0      0.0.0.0         255.255.0.0     U     0      0        0 docker0
192.168.1.0     0.0.0.0         255.255.255.0   U     202    0        0 enxb827ebbeebe6
```

### Console output of      `pivpn debug`
```
root@pihole:~# pivpn -d
::: Generating Debug Output
tee: /tmp/debug.log: Permission denied
::::            PiVPN debug              ::::
=============================================
::::            Latest commit            ::::
commit fc6e853049c24ab490bdaebaaa27a57b100f1c6d
Author: 4s3ti <4s3ti@protonmail.com>
Date:   Wed Dec 2 23:25:34 2020 +0100

    New pivpn status page

    Changed status page on README.md,
    new status page at https://status.pivpn.io
=============================================
::::        Installation settings        ::::
PLAT=Ubuntu
OSCN=groovy
USING_UFW=0
IPv4dev=enxb827ebbeebe6
IPv4addr=192.168.1.4/24
IPv4gw=192.168.1.1
install_user=ubuntu
install_home=/home/ubuntu
VPN=wireguard
pivpnPORT=51820
pivpnDNS1=10.6.0.1
pivpnDNS2=
pivpnHOST=REDACTED
INPUT_CHAIN_EDITED=0
FORWARD_CHAIN_EDITED=1
pivpnPROTO=udp
pivpnDEV=wg0
pivpnNET=10.6.0.0
subnetClass=24
UNATTUPG=1
INSTALLED_PACKAGES=()
=============================================
::::  Server configuration shown below   ::::
[Interface]
PrivateKey = server_priv
Address = 10.6.0.1/24
ListenPort = 51820
### begin tassoman ###
[Peer]
PublicKey = tassoman_pub
PresharedKey = tassoman_psk
AllowedIPs = 10.6.0.2/32
### end tassoman ###
=============================================
::::  Client configuration shown below   ::::
[Interface]
PrivateKey = tassoman_priv
Address = 10.6.0.2/24
DNS = 10.6.0.1

[Peer]
PublicKey = server_pub
PresharedKey = tassoman_psk
Endpoint = REDACTED:51820
AllowedIPs = 0.0.0.0/0, ::0/0
=============================================
::::    Recursive list of files in       ::::
::::    /etc/wireguard shown below       ::::
/etc/wireguard:
configs
keys
wg0.conf

/etc/wireguard/configs:
clients.txt
tassoman.conf

/etc/wireguard/keys:
server_priv
server_pub
tassoman_priv
tassoman_psk
tassoman_pub
=============================================
::::            Self check               ::::
:: [OK] IP forwarding is enabled
:: [OK] Iptables MASQUERADE rule set
:: [OK] Iptables FORWARD rule set
:: [OK] WireGuard is running
:: [OK] WireGuard is enabled (it will automatically start on reboot)
:: [OK] WireGuard is listening on port 51820/udp
=============================================
:::: Having trouble connecting? Take a look at the FAQ:
:::: https://github.com/pivpn/pivpn/wiki/FAQ
=============================================
:::: WARNING: This script should have automatically masked sensitive       ::::
:::: information, however, still make sure that PrivateKey, PublicKey      ::::
:::: and PresharedKey are masked before reporting an issue. An example key ::::
:::: that you should NOT see in this log looks like this:                  ::::
:::: YIAoJVsdIeyvXfGGDDadHh6AxsMRymZTnnzZoAb9cxRe                          ::::
=============================================
::::            Debug complete           ::::
:::
::: Debug output completed above.
::: Copy saved to /tmp/debug.log
:::
```

**Comment by tassoman** [comment] 2020-12-08 14:27
![client-pivpn](https://user-images.githubusercontent.com/92727/101496301-e3bb8a00-3969-11eb-826d-d5e9203f4c45.png)

PiHole has recognized my client

**Comment by orazioedoardo** [comment] 2020-12-10 07:22
> I can't see any traffic between the client and the gateway or forwarded from the raspberry to the gateway.

Could be the firewall, what's the output of `sudo iptables -vnL` and `sudo iptables -t nat -vnL`?

**Comment by tassoman** [comment] 2020-12-10 14:25
I've just logged in the ubuntu server arm64 raspberrypi and the prompt says:
```
  IPv4 address for docker0:         172.17.0.1
  IPv4 address for docker0:         169.254.19.39
  IPv4 address for enxb827ebbeebe6: 192.168.1.4
  IPv4 address for enxb827ebbeebe6: 192.168.1.101
```
How can be possibile there are two IPs assigned on eth interface? (enxb827ebbeebe6)

Note, the Docker stuff you're going to read is a working L2TP/ipSec VPN i use directly within mobile devices android/ios

### iptables
```
root@pihole:~# iptables -vnL
# Warning: iptables-legacy tables present, use iptables-legacy to see them
Chain INPUT (policy ACCEPT 656K packets, 205M bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain FORWARD (policy DROP 1 packets, 355 bytes)
 pkts bytes target     prot opt in     out     source               destination         
 216K  162M DOCKER-USER  all  --  *      *       0.0.0.0/0            0.0.0.0/0           
 216K  162M DOCKER-ISOLATION-STAGE-1  all  --  *      *       0.0.0.0/0            0.0.0.0/0           
 108K   80M ACCEPT     all  --  *      docker0  0.0.0.0/0            0.0.0.0/0            ctstate RELATED,ESTABLISHED
   14  4489 DOCKER     all  --  *      docker0  0.0.0.0/0            0.0.0.0/0           
 108K   82M ACCEPT     all  --  docker0 !docker0  0.0.0.0/0            0.0.0.0/0           
    0     0 ACCEPT     all  --  docker0 docker0  0.0.0.0/0            0.0.0.0/0           
  191 39510 ACCEPT     all  --  enxb827ebbeebe6 wg0     0.0.0.0/0            10.6.0.0/24          ctstate RELATED,ESTABLISHED /* wireguard-forward-rule */
  159 29994 ACCEPT     all  --  wg0    enxb827ebbeebe6  10.6.0.0/24          0.0.0.0/0            /* wireguard-forward-rule */

Chain OUTPUT (policy ACCEPT 595K packets, 57M bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain DOCKER (1 references)
 pkts bytes target     prot opt in     out     source               destination         
    5   724 ACCEPT     udp  --  !docker0 docker0  0.0.0.0/0            172.17.0.2           udp dpt:4500
    9  3765 ACCEPT     udp  --  !docker0 docker0  0.0.0.0/0            172.17.0.2           udp dpt:500

Chain DOCKER-ISOLATION-STAGE-1 (1 references)
 pkts bytes target     prot opt in     out     source               destination         
 108K   82M DOCKER-ISOLATION-STAGE-2  all  --  docker0 !docker0  0.0.0.0/0            0.0.0.0/0           
 216K  162M RETURN     all  --  *      *       0.0.0.0/0            0.0.0.0/0           

Chain DOCKER-USER (1 references)
 pkts bytes target     prot opt in     out     source               destination         
 216K  162M RETURN     all  --  *      *       0.0.0.0/0            0.0.0.0/0           

Chain DOCKER-ISOLATION-STAGE-2 (1 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 DROP       all  --  *      docker0  0.0.0.0/0            0.0.0.0/0           
 108K   82M RETURN     all  --  *      *       0.0.0.0/0            0.0.0.0/0           
```

### Then we have the nat table: 
```
root@pihole:~# iptables -t nat -vnL
# Warning: iptables-legacy tables present, use iptables-legacy to see them
Chain PREROUTING (policy ACCEPT 46569 packets, 3528K bytes)
 pkts bytes target     prot opt in     out     source               destination         
39868 2905K DOCKER     all  --  *      *       0.0.0.0/0            0.0.0.0/0            ADDRTYPE match dst-type LOCAL

Chain INPUT (policy ACCEPT 45935 packets, 3456K bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain POSTROUTING (policy ACCEPT 49058 packets, 3211K bytes)
 pkts bytes target     prot opt in     out     source               destination         
  595 64997 MASQUERADE  all  --  *      !docker0  172.17.0.0/16        0.0.0.0/0           
   16   927 MASQUERADE  all  --  *      enxb827ebbeebe6  10.6.0.0/24          0.0.0.0/0            /* wireguard-nat-rule */
    0     0 MASQUERADE  udp  --  *      *       172.17.0.2           172.17.0.2           udp dpt:4500
    0     0 MASQUERADE  udp  --  *      *       172.17.0.2           172.17.0.2           udp dpt:500

Chain OUTPUT (policy ACCEPT 49038 packets, 3206K bytes)
 pkts bytes target     prot opt in     out     source               destination         
    1    93 DOCKER     all  --  *      *       0.0.0.0/0           !127.0.0.0/8          ADDRTYPE match dst-type LOCAL

Chain DOCKER (2 references)
 pkts bytes target     prot opt in     out     source               destination         
 1076 76628 RETURN     all  --  docker0 *       0.0.0.0/0            0.0.0.0/0           
    5   724 DNAT       udp  --  !docker0 *       0.0.0.0/0            0.0.0.0/0            udp dpt:4500 to:172.17.0.2:4500
    9  3765 DNAT       udp  --  !docker0 *       0.0.0.0/0            0.0.0.0/0            udp dpt:500 to:172.17.0.2:500
```
### Legacy iptables:
```
root@pihole:~# iptables-legacy --list
Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination  
```

**Comment by tassoman** [comment] 2020-12-10 15:00
Ok I've managed to remove the dhcp assigned ip address (192.168.1.101) by disabling dhcpcd service. But the routing problem stills effective :|

**Comment by tassoman** [comment] 2020-12-10 20:38
i'm running `tcpdump -i tun0` on android terminal and I can only see connections going out.
For example `10.6.0.2.nnnnn > 10.6.0.1.domain`

**Comment by orazioedoardo** [comment] 2020-12-11 10:29
So, both the nat rule


```
16   927 MASQUERADE  all  --  *      enxb827ebbeebe6  10.6.0.0/24          0.0.0.0/0            /* wireguard-nat-rule */

```

As well as forward rules

```
 191 39510 ACCEPT     all  --  enxb827ebbeebe6 wg0     0.0.0.0/0            10.6.0.0/24          ctstate RELATED,ESTABLISHED /* wireguard-forward-rule */
 159 29994 ACCEPT     all  --  wg0    enxb827ebbeebe6  10.6.0.0/24          0.0.0.0/0            /* wireguard-forward-rule */
```

Have a positive packet count, so they are definitely being reached.

> Em I wrong if I say the OUTPUT is piping all not local traffic inside the DOCKER chain?

The OUTPUT chain is for packets originated from the raspberry pi, not forwarded packages. To recap, do the following work?

- Connect to the wireguard vpn
- While connected, connect via ssh to the raspberry pi
- While connected, connect to a host in the 192.168.1.0/24 range.
- While connected, connect to the internet.

**Comment by tassoman** [comment] 2020-12-11 20:45
>     * Connect to the wireguard vpn
>     * While connected, connect via ssh to the raspberry pi
>     * While connected, connect to a host in the 192.168.1.0/24 range.
>     * While connected, connect to the internet.

I've configured the client using the data inside `account.conf` file.
Then I've activated the VPN client who connects with a green flag.
I can't do any ssh connection, prompt waits for data, then goes "operation timed out".
I've tried ping but I can only ping the vpn client itself.

:o: ping 10.6.0.2 - 0.6 ms
:x: ping 10.6.0.1 - Request timeout
:x: ping 192.168.1.4 - Request timeout 
:x: ping 192.168.1.1 - Request timeout 
:x: ping www.google.com - Cannot resolve, unkown host

### account.conf
```
[Interface]
PrivateKey = UEEL//zzzzzzzzzzzzzzzzzzzzzzzzz=
Address = 10.6.0.2/24
DNS = 10.6.0.1

[Peer]
PublicKey = yyyyyyyyyyyyyyyyyyyyyyyy=
PresharedKey = xxxxxxxxxxxxxxxxxxxx=
Endpoint = aaa.bbb.com:51820
AllowedIPs = 0.0.0.0/0, ::0/0
```

**Comment by orazioedoardo** [comment] 2020-12-12 10:59
If you can't even ping 10.6.0.1 (the VPN IP of the raspberry), then it's likely that there is no handshake, which is a regression as it seemed to work on your first post.

**Comment by tassoman** [comment] 2020-12-14 00:40
I think there is a messup ... I'm going to backup the whole my Pi-Hole® configuration then restarting configuration by scratch.
Do you think I can try with https://raspi.debian.net/ ? :thinking: 
Ubuntu Server looks like bloated of unwanted stuff.

**Comment by orazioedoardo** [comment] 2020-12-14 08:39
[Raspberry Pi OS 9/10](https://www.raspberrypi.org/software/operating-systems/) and [Ubuntu Server 20.04](https://ubuntu.com/download/raspberry-pi) are officially supported

**Comment by tassoman** [comment] 2020-12-15 00:40
I did a fresh installation of ubuntu arm6 20.04. I've fully configured Pi-Hole® and PiVpn from scratch :exploding_head: but I'm still stuck. Maybe my home provider is blocking port udp:51820 ?
I can see handshakes, inside tcpdump, inside wireguard client, inside iptables nat table. But nothing more :sob: 

```
root@pihole:~# iptables -vnL 
Chain INPUT (policy ACCEPT 3701 packets, 387K bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain FORWARD (policy ACCEPT 388 packets, 74663 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain OUTPUT (policy ACCEPT 3617 packets, 408K bytes)
 pkts bytes target     prot opt in     out     source               destination         
root@pihole:~# iptables -vnL -t nat
Chain PREROUTING (policy ACCEPT 212 packets, 14135 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain INPUT (policy ACCEPT 196 packets, 13121 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain OUTPUT (policy ACCEPT 232 packets, 15729 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain POSTROUTING (policy ACCEPT 232 packets, 15729 bytes)
 pkts bytes target     prot opt in     out     source               destination         
   16  1014 MASQUERADE  all  --  *      eth0    10.6.0.0/24          0.0.0.0/0            /* wireguard-nat-rule */
```

**Comment by orazioedoardo** [comment] 2020-12-16 07:45
Never seen that, try to change the port or the MTU.

**Comment by tassoman** [comment] 2020-12-19 01:09
I've reinstalled pivpn from scratch, configuring port 2251, I forwarded it, then I created a key for each client.
then I activated wireguard kernel debug by `echo 'module wireguard +p' | sudo tee /sys/kernel/debug/dynamic_debug/control`
after this I followed system messages `dmesg -w`

```
[  288.986550] wireguard: wg0: Receiving handshake initiation from peer 2 (151.82.24.230:23044)
[  288.986573] wireguard: wg0: Sending handshake response to peer 2 (151.82.24.230:23044)
[  288.989687] wireguard: wg0: Keypair 1 created for peer 2
[  304.274635] wireguard: wg0: Receiving handshake initiation from peer 2 (151.82.24.230:23044)
[  304.274660] wireguard: wg0: Sending handshake response to peer 2 (151.82.24.230:23044)
[  304.277331] wireguard: wg0: Keypair 2 created for peer 2
```

I've started pinging the clients from the pivpn. The only pinged client was the ios device (while the display was on). 

```
ubuntu@pihole:~$ pivpn -c
::: Connected Clients List :::
Name          Remote IP                Virtual IP      Bytes Received      Bytes Sent      Last Seen
tassoman      (none)                   10.6.0.2        0B                  0B              (not yet)
apple         xxx.xxx.24.230:23045      10.6.0.3        11KiB               18KiB           Dec 19 2020 - 00:44:41
android       xxx.xxx.139.221:9509      10.6.0.4        16KiB               21KiB           Dec 19 2020 - 00:46:00

ubuntu@pihole:~$ ping 10.6.0.3
PING 10.6.0.3 (10.6.0.3) 56(84) bytes of data.
--- 10.6.0.3 ping statistics ---
265 packets transmitted, 177 received, 33.2075% packet loss, time 266266ms
rtt min/avg/max/mdev = 46.852/144.505/402.367/89.222 ms
```

Android client can't be pinged, 100% packet loss. Then suddently started messing up the src ip

```
[  758.139713] wireguard: wg0: Packet has unallowed src IP (10.98.142.213) from peer 3 (xxx.xxx.139.221:9518)
[  758.279107] wireguard: wg0: Packet has unallowed src IP (10.98.142.213) from peer 3 (xxx.xxx.139.221:9518)
```

Android Wireguard app is coming from Android Store, and is gaining root privs. 
Advanced settings menu can't find a suitable kernel module. I can't say if it's needed.
Android OS is LineageOS 14.1

End of all, data transfert is still missing in both clients 🤷 🤣

**Comment by tassoman** [comment] 2020-12-21 21:43
Default OpenVpn PiVPN installation, worked flawless :heavy_check_mark:

**Comment by orazioedoardo** [comment] 2020-12-25 11:12
I'm closing this as it looks like you changed plan.

**Closed by orazioedoardo** 2020-12-25 11:12 UTC

**Comment by tassoman** [comment] 2020-12-26 14:43
OpenVPN is poor in performance but works... Ok for closing this issue.

**Comment by tassoman** [comment] 2021-11-05 22:24
I've solved this issue and probably all the other issues related :unamused:  

![Huge facepalm](https://thumbs.gfycat.com/AltruisticDependableGordonsetter-small.gif)

Altough wireguard is working on udp port, __you need to forward both TCP+UDP 51820 ports from your router to the pivpn+pihole__

**Comment by tassoman** [comment] 2021-11-05 22:49
It worked for a while then now silence. I wonder if it's my provider blocking packets
```bash
root@piholepi1:~# ping 10.6.0.2
PING 10.6.0.2 (10.6.0.2) 56(84) bytes of data.
64 bytes from 10.6.0.2: icmp_seq=1 ttl=64 time=1333 ms
64 bytes from 10.6.0.2: icmp_seq=2 ttl=64 time=319 ms
64 bytes from 10.6.0.2: icmp_seq=3 ttl=64 time=128 ms
64 bytes from 10.6.0.2: icmp_seq=4 ttl=64 time=85.6 ms
64 bytes from 10.6.0.2: icmp_seq=5 ttl=64 time=130 ms
64 bytes from 10.6.0.2: icmp_seq=6 ttl=64 time=89.8 ms
64 bytes from 10.6.0.2: icmp_seq=7 ttl=64 time=120 ms
64 bytes from 10.6.0.2: icmp_seq=8 ttl=64 time=79.3 ms
^C
--- 10.6.0.2 ping statistics ---
8 packets transmitted, 8 received, 0% packet loss, time 35ms
rtt min/avg/max/mdev = 79.265/285.614/1333.495/402.566 ms, pipe 2
```

**Comment by hasael** [comment] 2024-04-20 16:51
> I've solved this issue and probably all the other issues related 😒
> 
> ![Huge facepalm](https://camo.githubusercontent.com/e439566bcf3783ceb79bccdc954dbf9fb9aacb525eb25c9bc86682f89e27897e/68747470733a2f2f7468756d62732e6766796361742e636f6d2f416c7472756973746963446570656e6461626c65476f72646f6e7365747465722d736d616c6c2e676966) [ ![Huge facepalm](https://camo.githubusercontent.com/e439566bcf3783ceb79bccdc954dbf9fb9aacb525eb25c9bc86682f89e27897e/68747470733a2f2f7468756d62732e6766796361742e636f6d2f416c7472756973746963446570656e6461626c65476f72646f6e7365747465722d736d616c6c2e676966) ](https://camo.githubusercontent.com/e439566bcf3783ceb79bccdc954dbf9fb9aacb525eb25c9bc86682f89e27897e/68747470733a2f2f7468756d62732e6766796361742e636f6d2f416c7472756973746963446570656e6461626c65476f72646f6e7365747465722d736d616c6c2e676966) [ ](https://camo.githubusercontent.com/e439566bcf3783ceb79bccdc954dbf9fb9aacb525eb25c9bc86682f89e27897e/68747470733a2f2f7468756d62732e6766796361742e636f6d2f416c7472756973746963446570656e6461626c65476f72646f6e7365747465722d736d616c6c2e676966)
> 
> Altough wireguard is working on udp port, **you need to forward both TCP+UDP 51820 ports from your router to the pivpn+pihole**

I had the same issue, and this worked for me. Thank you!
