### ISSUE TITLE
Is pivpn compatible with Raspbian Stretch?

### ISSUE THREAD

**Issue by jsfrederick** [pivpn/pivpn#342] opened 2017-08-26 17:24 UTC
Would like to update to Raspbian Stretch. Has anyone tested this yet?

Thx.

**Comment by TheSIlentLink** [comment] 2017-08-27 11:57
Hopefully we get an update with stretch support soon

**Comment by TheSIlentLink** [comment] 2017-08-27 16:36
It is unfortunately not compatible https://github.com/pivpn/pivpn/issues/337

**Comment by cfcolaco** [comment] 2017-08-27 19:22
I dont remember well, but I think I have managed to run pivpn in a Debian 9 VM ... PiVPN will tell you that can't recognize the system and ask you if you want to try it anyway! if you say yes ... it will run and install ... 

anyway .. by mid september I will try to catch up ecerything and eventually make a couple of PR, one of them to add support for Strech. 

@redfast00 Can you mark this as an improvement // feature request // wattever kind of thing so I don't forget about it latter? 

I wonder about @0-kaladin status ...

**Comment by jellemdekker** [comment] 2017-09-06 19:19
Debian Stretch uses OpenSSL 1.1.x by default whereas Debian Jessie uses 1.0.x. It seems Easy-RSA 3 doesn't support OpenSSL 1.1.x yet, this will come when EasyRSA 3.2 will be released. Source: [Easy-RSA issue 132](https://github.com/OpenVPN/easy-rsa/issues/132)

**Comment by TheSIlentLink** [comment] 2017-09-17 15:31
So are we stuck waiting for Easy-RSA 3.2?

**Comment by 0-kaladin** [comment] 2017-09-18 12:08
Maybe, I can see if there is a workaround.

**Comment by fedorafonzie** [comment] 2017-10-02 15:11
Found this workaround on reddit. Worked for me: https://www.reddit.com/r/raspberry_pi/comments/6w0dxs/openvpnpivpn_on_raspbian_stretch_error_parsing/

**Comment by ThomasLuyckx** [comment] 2017-10-06 18:48
@fedorafonzie, I appreciate the info. It worked for me as well.

**Comment by avdheijden** [comment] 2017-10-09 12:38
I've just succesfully installed pivpn on Rasbian Stretch on a Raspberrypi A.
No issues at al.
Thnx for the tutorial

**Comment by cfcolaco** [comment] 2017-10-09 19:06
@avdheijden have you used the workaround or tried with the Test branch? would be useful to have more ppl testing the test branch and providing feedback on it

**Comment by TheSIlentLink** [comment] 2017-10-09 19:07
How would we go around installing the test branch? Do we need to download and run install.sh? the link points to the current release.

**Comment by cfcolaco** [comment] 2017-10-09 19:10
@TheSIlentLink 

https://github.com/pivpn/pivpn/wiki#testing


There you have!

**Comment by avdheijden** [comment] 2017-10-10 03:13
I didn't use a workaround, i just downloaded the full stretch image, burned it to a sd cart, did some of my own basic settings, and then manually a apt-get update and upgrade.
after that i used the curl command from the website , I got a warning that it was only tested on Jessie.
i ignored the warning. After that the installation went smoothly. no errors and warnings.
after the reboot i created a ovpn file, and tested it and it worked, so I'm happy.
I did this on my first raspberrypi 1.

**Comment by TheSIlentLink** [comment] 2017-10-10 19:58
@cfcolaco I am currently installing it from the test branch as it is generating keys. However I got this error before is this normal? 

Using configuration from /etc/openvpn/easy-rsa/openssl-1.0.cnf
Can't open /etc/openvpn/easy-rsa/pki/index.txt.attr for reading, No such file or directory
1995900320:error:02001002:system library:fopen:No such file or directory:../crypto/bio/bss_file.c:74:fopen('/etc/openvpn/easy-rsa/pki/index.txt.attr','r')
1995900320:error:2006D080:BIO routines:BIO_new_file:no such file:../crypto/bio/bss_file.c:81:

Will let you know if more issues come up.

**Comment by TheSIlentLink** [comment] 2017-10-10 20:40
@cfcolaco The install finished perfectly but I can not connect using my iPhone I get this error:
2017-10-10 21:38:19 ----- OpenVPN Start -----
OpenVPN core 3.1.2 ios arm64 64-bit built on Dec  5 2016 12:50:25
2017-10-10 21:38:19 Frame=512/2048/512 mssfix-ctrl=1250
2017-10-10 21:38:19 EVENT: CORE_ERROR PolarSSL: error parsing config private key : PKCS5 - Requested encryption or digest alg not available [ERR]
2017-10-10 21:38:19 Raw stats on disconnect:
2017-10-10 21:38:19 Performance stats on disconnect:
  CPU usage (microseconds): 2626
  Network bytes per CPU second: 0
  Tunnel bytes per CPU second: 0
2017-10-10 21:38:19 EVENT: DISCONNECT_PENDING
2017-10-10 21:38:19 ----- OpenVPN Stop -----

**Comment by TheSIlentLink** [comment] 2017-10-10 20:52
Finally after following this guide: https://github.com/pivpn/pivpn/issues/364 I can confirm it works perfectly! Thanks so much @cfcolaco

**Comment by cfcolaco** [comment] 2017-10-10 21:32
@TheSIlentLink need to study that thing a bit more ... but as I understand ... your stretch is not a fresh install of stretch right? is upgrade from the previous one?

**Comment by TheSIlentLink** [comment] 2017-10-10 21:33
@cfcolaco not at all I did a clean install.

**Comment by TheSIlentLink** [comment] 2017-10-10 21:34
@cfcolaco regarding the missing files issue I found this https://github.com/OpenVPN/easy-rsa/issues/147 It seems to be normal.

**Comment by cfcolaco** [comment] 2017-10-10 22:26
@TheSIlentLink ...need to read that stuff more carefully, can you replicate it? I have done my tests in multiple different systems ( you can see it here #374  ) that never happened to me ... I know that it happens if you upgrade ... and this won't fix it anyway

**Comment by TheSIlentLink** [comment] 2017-10-11 06:48
@cfcolaco If you would like I could try a reinstall on another system and see if it happens again

**Comment by cfcolaco** [comment] 2017-10-11 20:52
@TheSIlentLink that would be nice! but now you can use the main branch! and the normal installation method as per PR #376 test branch has been merged into master! 

Closing this issue.

**Closed by cfcolaco** 2017-10-11 20:52 UTC
Labels: enhancement

**Comment by Yezariael** [comment] 2017-10-19 22:59
I did a clean install with Raspian Stretch today and got the same error.
```
writing new private key to '/etc/openvpn/easy-rsa/pki/private/server_f9W8a6IBtw$
-----
Using configuration from /etc/openvpn/easy-rsa/openssl-1.0.cnf
Can't open /etc/openvpn/easy-rsa/pki/index.txt.attr for reading, No such file o$
1996031392:error:02001002:system library:fopen:No such file or directory:../cry$
1996031392:error:2006D080:BIO routines:BIO_new_file:no such file:../crypto/bio/$
Check that the request matches the signature
Signature ok
The Subject's Distinguished Name is as follows
