### ISSUE TITLE
Client has full access to Server's Network

### ISSUE THREAD

**Issue by Geffers** [pivpn/pivpn#319] opened 2017-07-30 20:28 UTC
Folks,

Trying out something with a trusted friend he connected to my pivpn and was then able to connect, via ssh, to other machines within my network.

I was under the impression that connections under user nobody gave restricted access to server's network.

Geffers

**Comment by redfast00** [comment] 2017-07-30 22:29
Duplicate of #307 (by the same person strangely enough).

**Closed by redfast00** 2017-07-30 22:29 UTC
