### ISSUE TITLE
wireguard isn't supported on ubuntu server 64bit / arm64

### ISSUE THREAD

**Issue by mrtnd** [pivpn/pivpn#1137] opened 2020-09-05 17:30 UTC
I was playing around with the my pi 4 and wanted to see how will wireguard perform on ubuntu server 64bit for raspberry pi. It turns out the script wont allow setting up wireguard. Only OpenVPN is possible. It says wireguard isn't supported on arm64. Normal installation of wireguard via apt install is possible. I have not tried the raspberry pi os 64bit yet (it's still in beta).

**Comment by orazioedoardo** [comment] 2020-09-05 17:32
Duplicate of https://github.com/pivpn/pivpn/issues/1005

**Closed by orazioedoardo** 2020-09-05 17:32 UTC
