### ISSUE TITLE
[Install Failed]: fails on "using VPN: WireGuard" and simply hangs forever, no error output

### ISSUE THREAD

**Issue by 1butterball1** [pivpn/pivpn#1808] opened 2024-01-12 21:37 UTC
### In raising this issue I confirm that

- [X] I have read the [documentation](https://docs.pivpn.io)
- [X] I have read and understood the [PiVPN General Guidelines](https://github.com/pivpn/pivpn/#general-guidelines)
- [X] I have read and understood the [PiVPN Troubleshooting Guidelines](https://docs.pivpn.io/faq/#how-do-i-troubleshoot-connection-issues)
- [X] The issue I am reporting isn't a duplicate, see [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen).
- [X] I have searched for similar issues and solutions
- [X] I can replicate the issue even after a clean OS installation

### Describe the issue

This is a fresh raspberry pi os install on a pi4 8gb model with nothing installed except it being up to date and docker installed. The script simply hangs after selecting wireguard as the preferred vpn.  I am aware of a screenshot taken on a mac which seems to show the same problem on a closed issue, but there was no solution posted there.  There doesn't seem to be anything within the docs about the problem either (unless I am misreading something).  The previously mentioned closed post said something about octopi and the docs mention a conflict of git wrappers, but octopi is not installed (this is a clean, fresh install with nothing running except the basic defaults on raspberry pi os lite, bookworm with ssh enabled and docker installed).  

Since there is a containerized version in the works, I am assuming docker doesn't conflict with anything.

EDIT: a fresh install without docker also produces the same error.
EDIT2: the aforementioned closed post with no solution is here https://github.com/pivpn/pivpn/issues/1704

### Expected behavior

script completes or outputs an error code when it fails.

### Please describe the steps to replicate the issue

fresh install of latest raspberypi os lite using the pi installer,
ssh into pi,
sudo -i
apt update
apt upgrade
curl -sSL https://get.docker.com | sh
curl -L https://install.pivpn.io | bash

### Have you taken any steps towards solving your issue?

Its hanging somewhere after line 1676 (I think) under auto_install/install.sh but I do not have a proposed solution yet and there doesn't seem to be any obvious "get stuck here if wrong var" type of loop prior to the next expected output to the user so I am unsure as to what the problem is.

Going the gitclone rout and running install.sh also produces the same error.

If it helps, the data generated in /tmp/setupVars.conf is as follows:

PLAT=Debian
OSCN=bookworm
USING_UFW=0
pivpnforceipv6route=1
IPv4dev=eth0
dhcpReserv=1
IPv4addr=10.0.0.3/8
IPv4gw=10.0.0.1
install_user=wgtest
install_home=/home/wgtest
VPN=wireguard

### Where did you run pivpn?

RaspberryPi

### Please provide your output from `uname -a`

Linux wgtest 6.1.0-rpi7-rpi-v8 #1 SMP PREEMPT Debian 1:6.1.63-1+rpt1 (2023-11-24) aarch64 GNU/Linux

### Details about Operative System

PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

**Comment by orazioedoardo** [comment] 2024-01-18 18:21
Duplicate of https://github.com/pivpn/pivpn/issues/1518

**Closed by orazioedoardo** 2024-01-18 18:21 UTC
Labels: Needs Investigation
