### ISSUE TITLE
[BUG] Directories not being created automatically

### ISSUE THREAD

**Issue by p1r473** [pivpn/pivpn#1304] opened 2021-05-06 16:19 UTC
## In raising this issue, I confirm the following: 

`{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting *is* directly related to the pivpn installer script.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pivpn/pivpn/wiki/FAQ), [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed), and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen)).

**Describe the bug**
The required folders don't seem to be getting created automatically
```

root@Harbormaster:~# pivpn wg add
Enter a Name for the Client: d
/opt/pivpn/wireguard/makeCONF.sh: line 82: keys/d_pub: No such file or directory
tee: keys/d_priv: No such file or directory
::: Client Keys generated
grep: configs/clients.txt: No such file or directory
/opt/pivpn/wireguard/makeCONF.sh: line 90: keys/d_pub: No such file or directory
/opt/pivpn/wireguard/makeCONF.sh: line 90: configs/clients.txt: No such file or directory
/opt/pivpn/wireguard/makeCONF.sh: line 95: -2: substring expression < 0
cat: keys/d_priv: No such file or directory
/opt/pivpn/wireguard/makeCONF.sh: line 97: configs/d.conf: No such file or directory
/opt/pivpn/wireguard/makeCONF.sh: line 105: configs/d.conf: No such file or directory
/opt/pivpn/wireguard/makeCONF.sh: line 107: configs/d.conf: No such file or directory
cat: keys/server_pub: No such file or directory
cat: keys/d_psk: No such file or directory
/opt/pivpn/wireguard/makeCONF.sh: line 113: configs/d.conf: No such file or directory
::: Client config generated
cat: keys/d_pub: No such file or directory
cat: keys/d_psk: No such file or directory
::: Updated server config
wg-quick@wg0.service is not active, cannot reload.
::: Failed to reload WireGuard
cp: cannot stat 'configs/d.conf': No such file or directory
chown: cannot access '/home/linaro/configs/d.conf': No such file or directory
chmod: cannot access '/home/linaro/configs/d.conf': No such file or directory
```
```
root@Harbormaster:~# pivpn wg add
Enter a Name for the Client: f
/opt/pivpn/wireguard/makeCONF.sh: line 82: keys/f_pub: No such file or directory
tee: keys/f_priv: No such file or directory
::: Client Keys generated
grep: configs/clients.txt: No such file or directory
/opt/pivpn/wireguard/makeCONF.sh: line 90: keys/f_pub: No such file or directory
/opt/pivpn/wireguard/makeCONF.sh: line 90: configs/clients.txt: No such file or directory
/opt/pivpn/wireguard/makeCONF.sh: line 95: -2: substring expression < 0
cat: keys/f_priv: No such file or directory
/opt/pivpn/wireguard/makeCONF.sh: line 97: configs/f.conf: No such file or directory
/opt/pivpn/wireguard/makeCONF.sh: line 105: configs/f.conf: No such file or directory
/opt/pivpn/wireguard/makeCONF.sh: line 107: configs/f.conf: No such file or directory
cat: keys/server_pub: No such file or directory
cat: keys/f_psk: No such file or directory
/opt/pivpn/wireguard/makeCONF.sh: line 113: configs/f.conf: No such file or directory
::: Client config generated
cat: keys/f_pub: No such file or directory
cat: keys/f_psk: No such file or directory
::: Updated server config
wg-quick@wg0.service is not active, cannot reload.
::: Failed to reload WireGuard
cp: cannot stat 'configs/f.conf': No such file or directory
chown: cannot access '/home/linaro/configs/f.conf': No such file or directory
chmod: cannot access '/home/linaro/configs/f.conf': No such file or directory
```

**To Reproduce**
Installed with `curl -L https://install.pivpn.io | bash`
Typed in `pivpn wg add`

**Expected behavior**
Folders should be created automcatically

**Screenshots**

**Desktop (please complete the following information):**
 - VPN Protocol

**Smartphone (please complete the following information):**
 - VPN Protocol

**Additional context**

**Comment by 4s3ti** [comment] 2021-05-06 19:23
This is clearly related and caused by:  with https://github.com/pivpn/pivpn/issues/1304 

Therefore my recommendation stands, 
Try on a clean system or please be more specific on what you have done. 

Closing.

**Closed by 4s3ti** 2021-05-06 19:23 UTC
Labels: Needs Investigation

**Comment by p1r473** [comment] 2021-05-06 20:11
Hi,
What I have done was
1. `curl -L https://install.pivpn.io | bash`
2. I noticed that the command `pivpn` did not work, so I chased down the symlink issue in #1302 and renames the 3 files with .sh. Now, pivpn works.
3. Then, I had to ``apt-get install wireguard` because 'wg' command was not working, which turned out to be the install script did not install wireguard for me
4. Now I am at the stage where I am getting all these directory errors

I have not done anything out of the ordinary to my PiVpn installation, I was following the instructions.
Im on an Asus Tinkerboard 2S running their TinkerOs based on Buster (Debian 10)

**Comment by p1r473** [comment] 2021-05-06 20:25
Testing the test branch, but having these same issues
```
root@Harbormaster:/home/linaro# curl -L https://test.pivpn.io | TESTING= bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   162  100   162    0     0    405      0 --:--:-- --:--:-- --:--:--   405
100 84313  100 84313    0     0   151k      0 --:--:-- --:--:-- --:--:--  151k
:::
::: You are root.
::: Reconfigure option selected.
::: Hostname length OK
::: Verifying free disk space...
:::
::: Package Cache update is needed, running apt-get update -y ...
 done!
:::
::: Checking apt-get for upgraded packages.... done!
:::
::: Your system is up to date! Continuing with PiVPN installation...
:::    Checking for git... already installed!
:::    Checking for tar... already installed!
:::    Checking for wget... already installed!
:::    Checking for curl... already installed!
:::    Checking for grep... already installed!
:::    Checking for dnsutils... already installed!
:::    Checking for whiptail... already installed!
:::    Checking for net-tools... already installed!
:::    Checking for bsdmainutils... already installed!
:::    Checking for iptables-persistent... already installed!
::: Using User: linaro
:::
::: Checking for existing base files...
:::    Checking /usr/local/src/pivpn is a repo... OK!
:::     Updating repo in /usr/local/src/pivpn...Branch 'test' set up to track remote branch 'test' from 'origin'.
Switched to a new branch 'test'
 done!
::: Using VPN: OpenVPN
::: Installing OpenVPN from Debian package...
:::    Checking for openvpn... already installed!
:::    Checking for grepcidr... already installed!
:::    Checking for expect... already installed!
::: Using protocol: udp
  [i] Listening on all interfaces, permitting origins from one hop away (LAN)
  [✓] Restarting DNS server
::: Backing up the openvpn folder to /etc/openvpn_2021-05-06-202305.tar.gz
./easyrsa: 341: set: Illegal option -o echo
::: Building CA...
Using SSL: openssl OpenSSL 1.1.1d  10 Sep 2019
read EC key
writing EC key
./easyrsa: 341: set: Illegal option -o echo

::: CA Complete.

Note: using Easy-RSA configuration from: /etc/openvpn/easy-rsa/vars
Using SSL: openssl OpenSSL 1.1.1d  10 Sep 2019
Generating an EC private key
writing new private key to '/etc/openvpn/easy-rsa/pki/easy-rsa-2687.qOhc7E/tmp.P7d717'
-----
Using configuration from /etc/openvpn/easy-rsa/pki/easy-rsa-2687.qOhc7E/tmp.PW4mAn
Check that the request matches the signature
Signature ok
The Subject's Distinguished Name is as follows
commonName            :ASN.1 12:'Harbormaster_ba43df0d-1776-4caf-8dda-5c818eacdf57'
Certificate is to be certified until May  4 20:23:07 2031 GMT (3650 days)

Write out database with 1 new entries
Data Base Updated
./easyrsa: 341: set: Illegal option -o echo

Note: using Easy-RSA configuration from: /etc/openvpn/easy-rsa/vars
Using SSL: openssl OpenSSL 1.1.1d  10 Sep 2019
Using configuration from /etc/openvpn/easy-rsa/pki/easy-rsa-2766.VgZcVg/tmp.M7efJP

An updated CRL has been created.
CRL file: /etc/openvpn/easy-rsa/pki/crl.pem

./easyrsa: 341: set: Illegal option -o echo
openvpn:x:114:121::/var/lib/openvpn/:/usr/sbin/nologin
iptables v1.8.2 (nf_tables):  CHAIN_ADD failed (No such file or directory): chain PREROUTING
iptables v1.8.2 (nf_tables): Couldn't load match `comment':No such file or directory

Try `iptables -h' or 'iptables --help' for more information.
# Warning: iptables-legacy tables present, use iptables-legacy to see them
# Warning: iptables-legacy tables present, use iptables-legacy to see them
# Warning: iptables-legacy tables present, use iptables-legacy to see them
# Warning: iptables-legacy tables present, use iptables-legacy to see them
# Warning: iptables-legacy tables present, use iptables-legacy-save to see them
::: Install Complete...
::: Restarting services...
:::    Checking for unattended-upgrades... already installed!
::: Setupfiles copied to /etc/pivpn/openvpn/setupVars.conf
::: Installing scripts to /opt/pivpn...
unlink: cannot unlink '/etc/bash_completion.d/pivpn': No such file or directory
 done.
::: Flushing writes to disk...
::: done.
:::
root@Harbormaster:/home/linaro# wg
root@Harbormaster:/home/linaro# pivpn wg add
Enter a Name for the Client: HMSInterceptor
/opt/pivpn/wireguard/makeCONF.sh: line 82: keys/HMSInterceptor_pub: No such file or directory
tee: keys/HMSInterceptor_priv: No such file or directory
::: Client Keys generated
grep: configs/clients.txt: No such file or directory
/opt/pivpn/wireguard/makeCONF.sh: line 90: keys/HMSInterceptor_pub: No such file or directory
/opt/pivpn/wireguard/makeCONF.sh: line 90: configs/clients.txt: No such file or directory
/opt/pivpn/wireguard/makeCONF.sh: line 95: -2: substring expression < 0
cat: keys/HMSInterceptor_priv: No such file or directory
/opt/pivpn/wireguard/makeCONF.sh: line 99: configs/HMSInterceptor.conf: No such file or directory
/opt/pivpn/wireguard/makeCONF.sh: line 105: configs/HMSInterceptor.conf: No such file or directory
/opt/pivpn/wireguard/makeCONF.sh: line 109: configs/HMSInterceptor.conf: No such file or directory
/opt/pivpn/wireguard/makeCONF.sh: line 111: configs/HMSInterceptor.conf: No such file or directory
cat: keys/server_pub: No such file or directory
cat: keys/HMSInterceptor_psk: No such file or directory
/opt/pivpn/wireguard/makeCONF.sh: line 117: configs/HMSInterceptor.conf: No such file or directory
::: Client config generated
cat: keys/HMSInterceptor_pub: No such file or directory
cat: keys/HMSInterceptor_psk: No such file or directory
::: Updated server config
wg-quick@wg0.service is not active, cannot reload.
::: Failed to reload WireGuard
cp: cannot stat 'configs/HMSInterceptor.conf': No such file or directory
chown: cannot access '/home/linaro/configs/HMSInterceptor.conf': No such file or directory
chmod: cannot access '/home/linaro/configs/HMSInterceptor.conf': No such file or directory
======================================================================
::: Done! HMSInterceptor.conf successfully created!
::: HMSInterceptor.conf was copied to /home/linaro/configs for easy transfer.
::: Please use this profile only on one device and create additional
::: profiles for other devices. You can also use pivpn -qr
::: to generate a QR Code you can scan with the mobile app.
======================================================================
```

**Comment by 4s3ti** [comment] 2021-05-06 23:27
as stated here: https://github.com/pivpn/pivpn/issues/1239 and at this point in some other issues ... 
there are still some limitations in Wireguard support for some distros and boards, this happens because different boards require different kernel headers and there is no way we can test and know about all of them. 

afaik Debian 10 doesn't have wire-guard yet built into the kernel which, therefore we are not supporting it. 

Maybe we should be more clear about it. might put something up about that on the documentation. 

As you said you are not doing anything fancy .. but shouting out bug without reading around and mentioning all those details in first place like the board you are using, OS, don't make it easier either.
