### ISSUE TITLE
Updating issue

### ISSUE THREAD

**Issue by jjpd19** [pivpn/pivpn#960] opened 2020-02-22 10:53 UTC
Hi everybody. I have read something similar overhere but not exactly the same, so, I decided to open a new entry.
I am having this weird message at the end of the updating process. Does anybody understand why and can help me? thank you in advance.
The message is:

cp: no se puede efectuar `stat' sobre '/etc/.pivpn/scripts/bash-completion': No existe el fichero o el directorio

The screen is as follows (xxx in the user name and machine are deliberated):

 pivpn -up
[sudo] password for xxxxxxx:
/opt/pivpn/update.sh: 78: /opt/pivpn/update.sh: [[: not found
going do update PiVPN Scripts
/opt/pivpn/update.sh: 17: /opt/pivpn/update.sh: [[: not found
fatal: la ruta de destino '/etc/.pivpn' ya existe y no es un directorio vacío.
PiVPN Scripts have been updated
xxxx@xxxx:~/ovpns $ sudo pivpn -up
going do update PiVPN Scripts
Clonando en '/etc/.pivpn'...
remote: Enumerating objects: 104, done.
remote: Counting objects: 100% (104/104), done.
remote: Compressing objects: 100% (58/58), done.
remote: Total 2284 (delta 51), reused 72 (delta 34), pack-reused 2180
Recibiendo objetos: 100% (2284/2284), 747.25 KiB | 1.93 MiB/s, listo.
Resolviendo deltas: 100% (1274/1274), listo.
cp: no se puede efectuar `stat' sobre '/etc/.pivpn/scripts/bash-completion': No existe el fichero o el directorio
PiVPN Scripts have been updated

I have checked the directory and got:

xxxxx@xxxxx:~/ovpns $ ls /etc/.pivpn/scripts
backup.sh  openvpn  self_check.sh  uninstall.sh  update.sh  wireguard
xxxxx@xxxxx:~/ovpns $ ls /etc/.pivpn/scripts/openvpn
bash-completion  clientStat.sh  listOVPN.sh  makeOVPN.sh  pivpn  pivpnDebug.sh  removeOVPN.sh

**Comment by orazioedoardo** [comment] 2020-02-22 11:30
I think it's a duplicate of: https://github.com/pivpn/pivpn/issues/916

**Comment by jjpd19** [comment] 2020-02-22 12:27
> 
> 
> I think it's a duplicate of: #916

I think so either. Thanks. Can close the topic.

**Closed** 2020-02-22 13:01 UTC
