### ISSUE TITLE
[BUG] Installer incorrectly assumes amd64 when running on Debian

### ISSUE THREAD

**Issue by orazioedoardo** [pivpn/pivpn#1180] opened 2020-11-14 09:31 UTC
## In raising this issue, I confirm the following: 

`{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting can be *is* directly related to the pivpn installer script.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pivpn/pivpn/wiki/FAQ), [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed), and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen)).

**Describe the bug**
When Debian platform is detected, kernel headers for amd64 will be installed, regardless of the underlying architecture.

**To Reproduce**
1. Install PiVPN on non x86 Debian
2. See error `E: Package 'linux-headers-amd64' has no installation candidate`

**Expected behavior**
Either find a suitable kernel headers package or bail out with a more descriptive message.

**Desktop (please complete the following information):**
 - WireGuard
 - OS: Debian
 - Version any

**Additional context**
Found here: https://github.com/MichaIng/DietPi/issues/3910

**Comment by TamaTamaGoGo** [comment] 2020-11-22 14:58
edit install script to install raspberrypi-kernel-headers instead.
``wget https://raw.githubusercontent.com/pivpn/pivpn/master/auto_install/install.sh && sudo chmod 777 install.sh && nano install.sh``
Ctrl+W and type linux-headers-amd64 and ENTER.
You will find the letter linux-headers-amd64, change to raspberrypi-kernel-headers .
After editing, run
``./install.sh``

**Comment by hazardlabs** [comment] 2020-11-23 13:54
I also had this issue, when trying to install on an armel based nas

**Comment by MichaIng** [comment] 2020-12-11 21:51
The problem is that the installer currently sets the flag for WireGuard support, even if the module is not build into the kernel and it is not an x86_64 or Raspbian system. In such case, to build the kernel module, kernel headers are required, which are only reliable known for Raspbian and x86_64 on Debian and Ubuntu (the `linux-headers-amd64` package): https://github.com/pivpn/pivpn/blob/master/auto_install/install.sh#L481-L503

Probably not the most beautiful fix, but what would work is to replace `WIREGUARD_SUPPORT=1` at line 495 by:
```
[[ $WIREGUARD_BUILTIN == 1 || $PLAT == 'Raspbian' || $DPKG_ARCH == 'amd64' ]] && WIREGUARD_SUPPORT=1
```
and line 497 `if [ "$PLAT" = "Debian" ] || [ "$PLAT" = "Raspbian" ]; then` with:
```
if [[ $PLAT == 'Raspbian' ]] || [[ $PLAT == 'Debian' && $DPKG_ARCH == 'amd64' ]]; then
```

Better would be to do the builtin check separately to enable support as well for Raspbian/Debian if the package is not yet available (Buster without backports) but the module already built into the kernel. E.g. on Raspbian this could become a common setup soon when RPi Linux 5.10 is released or already now when `rpi-update` + "next" branch was used.

For @orazioedoardo and @hazardlabs this sadly means that WireGuard via PiVPN is not supported on your boards. You can hack it in manually but kernel headers are required and on non-Raspbian boards there are various different ways how the kernel is installed and hence the name of the headers package, or if there is even one, impossible to support in any generic way.

**Comment by MichaIng** [comment] 2020-12-11 23:39
Pull request with fix is up: #1201

**Comment by uocxp** [comment] 2021-01-16 13:04
I am still facing this issue, despite the merging the PR. 
```

	elif [ "$PLAT" = "Debian" ]; then

		echo "::: Installing WireGuard from Debian package... "

		if [ "$NEED_WIREGUARD_REPO" -eq 1 ]; then
			echo "::: Adding Debian repository... "
			echo "deb https://deb.debian.org/debian/ bullseye main" | $SUDO tee /etc/apt/sources.list.d/pivpn-bullseye-repo.list > /dev/null

			printf 'Package: *\nPin: release n=bullseye\nPin-Priority: -1\n\nPackage: wireguard wireguard-dkms wireguard-tools\nPin: release n=bullseye\nPin-Priority: 100\n' | $SUDO tee /etc/apt/preferences.d/pivpn-limit-bullseye > /dev/null

			echo "::: Updating package cache..."
			# shellcheck disable=SC2086
			$SUDO ${UPDATE_PKG_CACHE} &> /dev/null & spinner $!
		fi

		PIVPN_DEPS=(wireguard-tools qrencode)

		if [ "$WIREGUARD_BUILTIN" -eq 0 ]; then
			# Explicitly install the module if not built-in
			PIVPN_DEPS+=(linux-headers-amd64 wireguard-dkms)
		fi

		installDependentPackages PIVPN_DEPS[@]
```
This code snippet is still trying to install trying to install `linux-headers-amd64`

**Comment by MichaIng** [comment] 2021-01-16 15:19
The fix has not yet been merged into master branch or uploaded. @orazioedoardo may I ask to give this some priority and bring the new code life to avoid further confusion for many ARM users?

@uocxp 
But just to be clear: This means that in your case WireGuard via PiVPN is not supported as the kernel module is not built into your kernel and PiVPN cannot know the exact kernel you use rather than how to pull headers for it, if even available. You need to either upgrade to a newer kernel (5.6+) to have WireGuard natively builtin or search headers for yours manually. When you found and installed headers, `apt install wireguard-dkms` will build the kernel module, `apt install wireguard-tools` makes the userspace tools available (service/wg/wg-quick).

Actually, for the PiVPN installer, it would be an idea to support manually build kernel modules as well, hence when not being part of a DEB package. But of course on every kernel upgrade, it needs to be manually re-build as well, if not DKMS does it (requiring headers update as well). So it could be supported via some warning, like:
> The WireGuard kernel module has been found on your system, but no related DEB package, hence we cannot assure that this module will be available after kernel upgrades, which may hence break WireGuard.
>
> Do you want to continue using WireGuard via PiVPN, which requires you to take care the module rebuild yourself?

That way users can manually search for headers to build the module e.g. via DKMS and still manage that WireGuard instance via PiVPN. But as always, such things may lead to additional support effort for users which did not fully understand the underlying issue and hit "y" right away 😅.

**Comment by 4s3ti** [comment] 2021-01-17 11:57
@MichaIng I will try to get test merged later today into master. 

I don't think it would be good idea to support manually build kernel modules, i'd prefer to keep it as simple as it is ...Along side with some automated testing (which i am currently working on when i have some free time), I will be also working on an official docker which i believe to be way more beneficial and easier to maintain instead of supporting a lot of very random things that we not always have a way to test.

**Comment by MichaIng** [comment] 2021-01-17 12:56
Sounds reasonable. And the limit will fade out anyway with upgraded kernel versions, making efforts into this direction obsolete.

**Comment by 4s3ti** [comment] 2021-01-17 17:31
Merged into master:  https://github.com/pivpn/pivpn/commit/b5ec995f68fbae2eb30b50e1b6a4350f96316f2e

**Closed by 4s3ti** 2021-01-17 17:31 UTC
Labels: Fix in Test Branch, bug
