### ISSUE TITLE
No internet for connected clients after fresh install.

### ISSUE THREAD

**Issue by pkulak** [pivpn/pivpn#380] opened 2017-10-12 17:06 UTC
## Console output of `pivpn debug`
```
::: Generating Debug Output
:::					:::
::		PiVPN Debug		 ::
:::					:::
::	Latest Commit			 ::
:::					:::
commit ad6f5b6c8b57cf72d22527cff4b2290a40514a47
Merge: 454b755 1a67b50
Author: redfast00 <redfast00@users.noreply.github.com>
Date:   Wed Oct 11 18:46:48 2017 +0200

    Merge pull request #376 from redfast00/master

    Merge test branch into master
:::					:::
::	Recursive list of files in	 ::
::	/etc/openvpn/easy-rsa/pki	 ::
:::					:::
/etc/openvpn/easy-rsa/pki/:
Default.txt
ca.crt
crl.pem
dh2048.pem
index.txt
index.txt.attr
index.txt.attr.old
index.txt.old
issued
phil1.ovpn
phil2.ovpn
private
serial
serial.old
ta.key

/etc/openvpn/easy-rsa/pki/issued:
phil1.crt
phil2.crt
server_Q1WubOE077bMDD69.crt

/etc/openvpn/easy-rsa/pki/private:
ca.key
phil1.key
phil2.key
server_Q1WubOE077bMDD69.key
:::					:::
::	Output of /etc/pivpn/*		 ::
:::					:::
:: START /etc/pivpn/DET_PLATFORM ::
Raspbian
:: END /etc/pivpn/DET_PLATFORM ::
:: START /etc/pivpn/INSTALL_PORT ::
1194
:: END /etc/pivpn/INSTALL_PORT ::
:: START /etc/pivpn/INSTALL_PROTO ::
udp
:: END /etc/pivpn/INSTALL_PROTO ::
:: START /etc/pivpn/INSTALL_USER ::
pi
:: END /etc/pivpn/INSTALL_USER ::
:: START /etc/pivpn/NO_UFW ::
1
:: END /etc/pivpn/NO_UFW ::
:: START /etc/pivpn/pivpnINTERFACE ::
eth0
:: END /etc/pivpn/pivpnINTERFACE ::
:::					:::
:: /etc/openvpn/easy-rsa/pki/Default.txt ::
:::					:::
client
dev tun
proto udp
remote home.pkulak.com 1194
resolv-retry infinite
nobind
persist-key
persist-tun
key-direction 1
remote-cert-tls server
tls-version-min 1.2
verify-x509-name server_Q1WubOE077bMDD69 name
cipher AES-256-CBC
auth SHA256
comp-lzo
verb 1
:::					:::
::	Debug Output Complete		 ::
:::					:::
:::
::: Debug output completed above.
::: Copy saved to /tmp/debug.txt
:::
```

## Console output of `sudo iptables -t nat -L`

```
Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination
DOCKER     all  --  anywhere             anywhere             ADDRTYPE match dst-type LOCAL

Chain INPUT (policy ACCEPT)
target     prot opt source               destination

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination
DOCKER     all  --  anywhere            !loopback/8           ADDRTYPE match dst-type LOCAL

Chain POSTROUTING (policy ACCEPT)
target     prot opt source               destination
MASQUERADE  all  --  172.17.0.0/16        anywhere
MASQUERADE  all  --  10.8.0.0/24          anywhere

Chain DOCKER (2 references)
target     prot opt source               destination
RETURN     all  --  anywhere             anywhere
```

## Console output of `server.conf`

```
dev tun
proto udp
port 1194
ca /etc/openvpn/easy-rsa/pki/ca.crt
cert /etc/openvpn/easy-rsa/pki/issued/server_Q1WubOE077bMDD69.crt
key /etc/openvpn/easy-rsa/pki/private/server_Q1WubOE077bMDD69.key
dh /etc/openvpn/easy-rsa/pki/dh2048.pem
topology subnet
server 10.8.0.0 255.255.255.0
# server and remote endpoints
ifconfig 10.8.0.1 10.8.0.2
# Add route to Client routing table for the OpenVPN Server
push "route 10.8.0.1 255.255.255.255"
# Add route to Client routing table for the OPenVPN Subnet
push "route 10.8.0.0 255.255.255.0"
# your local subnet
push "route 192.168.1.0 255.255.255.0"
# Set your primary domain name server address for clients
push "dhcp-option DNS 192.168.1.1"
# 128.0.0.0/1 rather than 0.0.0.0/0. This has the benefit of
# overriding but not wiping out the original default gateway.
push "redirect-gateway def1"
client-to-client
keepalive 10 120
remote-cert-tls client
tls-version-min 1.2
tls-auth /etc/openvpn/easy-rsa/pki/ta.key 0
cipher AES-256-CBC
auth SHA256
comp-lzo
user nobody
group nogroup
persist-key
persist-tun
crl-verify /etc/openvpn/crl.pem
status /var/log/openvpn-status.log 20
status-version 3
log /var/log/openvpn.log
verb 1
# Generated for use by PiVPN.io
```

## Issue

At first I was sure this was a DNS issue, since that's usually what goes wrong, but I can't get ANY traffic to go through, even connecting to the IPs of other machines on the network. So next thought was an iptables issue, but the line is there. Only thing I can think of is that Docker is interfering somehow, but I don't really understand how multiple masquerade entries could conflict with each other...

Anyway, this is an amazing project, thanks so much for all the work. If anyone has any ideas, I'd be super grateful. Thanks!

**Comment by cfcolaco** [comment] 2017-10-12 17:54
hi!! =) 
Just to try to get on the same page ... 

Is PiVPN running on a Docker container? or natively in raspbian??
Are the PiVPN Clients Windows Machines?? 
can you give me the output of ```sudo iptables -t nat -S``` please??

From a connected client: 

Can you provide the log output from openvpn??
Can you ping 10.8.0.1?
is  192.168.1.1 the IP address of your router? if yes can you ping it?
Can you ping 8.8.8.8?


sorry for that bunch of questions ... but they are important to track where are you having your issue, and to determine if it was a pivpn failure or not =)

**Comment by pkulak** [comment] 2017-10-12 18:21
PiVPN is running natively on Raspbian.

I'm using Tunnelblick on a Mac to connect.

`sudo iptables -t nat -S`

```
-P PREROUTING ACCEPT
-P INPUT ACCEPT
-P OUTPUT ACCEPT
-P POSTROUTING ACCEPT
-N DOCKER
-A PREROUTING -m addrtype --dst-type LOCAL -j DOCKER
-A OUTPUT ! -d 127.0.0.0/8 -m addrtype --dst-type LOCAL -j DOCKER
-A POSTROUTING -s 172.17.0.0/16 ! -o docker0 -j MASQUERADE
-A POSTROUTING -s 10.8.0.0/24 -o eth0 -j MASQUERADE
-A DOCKER -i docker0 -j RETURN
```

Tunnelblick says:

```
*Tunnelblick: OS X 10.12.6; Tunnelblick 3.7.2a (build 4851)
2017-10-12 11:12:48 *Tunnelblick: Attempting connection with phil2 using shadow copy; Set nameserver = 769; monitoring connection
2017-10-12 11:12:48 *Tunnelblick: openvpnstart start phil2.tblk 1337 769 0 1 0 1065264 -ptADGNWradsgnw 2.3.18-openssl-1.0.2k
2017-10-12 11:12:49 *Tunnelblick: openvpnstart log:
     OpenVPN started successfully. Command used to start OpenVPN (one argument per displayed line):
     
          /Applications/Tunnelblick.app/Contents/Resources/openvpn/openvpn-2.3.18-openssl-1.0.2k/openvpn
          --daemon
          --log
          /Library/Application Support/Tunnelblick/Logs/-SUsers-Sphil-SLibrary-SApplication Support-STunnelblick-SConfigurations-Sphil2.tblk-SContents-SResources-Sconfig.ovpn.769_0_1_0_1065264.1337.openvpn.log
          --cd
          /Library/Application Support/Tunnelblick/Users/phil/phil2.tblk/Contents/Resources
          --verb
          3
          --config
          /Library/Application Support/Tunnelblick/Users/phil/phil2.tblk/Contents/Resources/config.ovpn
          --verb
          3
          --cd
          /Library/Application Support/Tunnelblick/Users/phil/phil2.tblk/Contents/Resources
          --management
          127.0.0.1
          1337
          --management-query-passwords
          --management-hold
          --script-security
          2
          --up
          /Applications/Tunnelblick.app/Contents/Resources/client.up.tunnelblick.sh -9 -d -f -m -w -ptADGNWradsgnw
          --down
          /Applications/Tunnelblick.app/Contents/Resources/client.down.tunnelblick.sh -9 -d -f -m -w -ptADGNWradsgnw

2017-10-12 11:12:48 *Tunnelblick: openvpnstart starting OpenVPN
2017-10-12 11:12:49 OpenVPN 2.3.18 x86_64-apple-darwin [SSL (OpenSSL)] [LZO] [PKCS11] [MH] [IPv6] built on Sep 26 2017
2017-10-12 11:12:49 library versions: OpenSSL 1.0.2k  26 Jan 2017, LZO 2.09
2017-10-12 11:12:49 MANAGEMENT: TCP Socket listening on [AF_INET]127.0.0.1:1337
2017-10-12 11:12:49 Need hold release from management interface, waiting...
2017-10-12 11:12:49 MANAGEMENT: Client connected from [AF_INET]127.0.0.1:1337
2017-10-12 11:12:49 MANAGEMENT: CMD 'pid'
2017-10-12 11:12:49 MANAGEMENT: CMD 'state on'
2017-10-12 11:12:49 MANAGEMENT: CMD 'state'
2017-10-12 11:12:49 MANAGEMENT: CMD 'bytecount 1'
2017-10-12 11:12:49 MANAGEMENT: CMD 'hold release'
2017-10-12 11:12:49 *Tunnelblick: Established communication with OpenVPN
2017-10-12 11:12:49 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
2017-10-12 11:12:49 *Tunnelblick: Obtained passphrase from the Keychain
2017-10-12 11:12:49 MANAGEMENT: CMD 'password [...]'
2017-10-12 11:12:49 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
2017-10-12 11:12:49 Control Channel Authentication: tls-auth using INLINE static key file
2017-10-12 11:12:49 Outgoing Control Channel Authentication: Using 256 bit message hash 'SHA256' for HMAC authentication
2017-10-12 11:12:49 Incoming Control Channel Authentication: Using 256 bit message hash 'SHA256' for HMAC authentication
2017-10-12 11:12:49 Socket Buffers: R=[196724->196724] S=[9216->9216]
2017-10-12 11:12:49 MANAGEMENT: >STATE:1507831969,RESOLVE,,,
2017-10-12 11:12:49 UDPv4 link local: [undef]
2017-10-12 11:12:49 UDPv4 link remote: [AF_INET]*.*.*.*:1194
2017-10-12 11:12:49 MANAGEMENT: >STATE:1507831969,WAIT,,,
2017-10-12 11:12:49 MANAGEMENT: >STATE:1507831969,AUTH,,,
2017-10-12 11:12:49 TLS: Initial packet from [AF_INET]*.*.*.*:1194, sid=22354480 f9511180
2017-10-12 11:12:49 VERIFY OK: depth=1, CN=ChangeMe
2017-10-12 11:12:49 Validating certificate key usage
2017-10-12 11:12:49 ++ Certificate has key usage  00a0, expects 00a0
2017-10-12 11:12:49 VERIFY KU OK
2017-10-12 11:12:49 Validating certificate extended key usage
2017-10-12 11:12:49 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication
2017-10-12 11:12:49 VERIFY EKU OK
2017-10-12 11:12:49 VERIFY X509NAME OK: CN=server_Q1WubOE077bMDD69
2017-10-12 11:12:49 VERIFY OK: depth=0, CN=server_Q1WubOE077bMDD69
2017-10-12 11:12:50 Data Channel Encrypt: Cipher 'AES-256-CBC' initialized with 256 bit key
2017-10-12 11:12:50 Data Channel Encrypt: Using 256 bit message hash 'SHA256' for HMAC authentication
2017-10-12 11:12:50 Data Channel Decrypt: Cipher 'AES-256-CBC' initialized with 256 bit key
2017-10-12 11:12:50 Data Channel Decrypt: Using 256 bit message hash 'SHA256' for HMAC authentication
2017-10-12 11:12:50 Control Channel: TLSv1.2, cipher TLSv1/SSLv3 DHE-RSA-AES256-GCM-SHA384, 2048 bit RSA
2017-10-12 11:12:50 [server_Q1WubOE077bMDD69] Peer Connection Initiated with [AF_INET]*.*.*.*:1194
2017-10-12 11:12:51 MANAGEMENT: >STATE:1507831971,GET_CONFIG,,,
2017-10-12 11:12:52 SENT CONTROL [server_Q1WubOE077bMDD69]: 'PUSH_REQUEST' (status=1)
2017-10-12 11:12:52 PUSH: Received control message: 'PUSH_REPLY,route 10.8.0.1 255.255.255.255,route 10.8.0.0 255.255.255.0,route 192.168.1.0 255.255.255.0,dhcp-option DNS 192.168.1.1,redirect-gateway def1,route-gateway 10.8.0.1,topology subnet,ping 10,ping-restart 120,ifconfig 10.8.0.3 255.255.255.0'
2017-10-12 11:12:52 OPTIONS IMPORT: timers and/or timeouts modified
2017-10-12 11:12:52 OPTIONS IMPORT: --ifconfig/up options modified
2017-10-12 11:12:52 OPTIONS IMPORT: route options modified
2017-10-12 11:12:52 OPTIONS IMPORT: route-related options modified
2017-10-12 11:12:52 OPTIONS IMPORT: --ip-win32 and/or --dhcp-option options modified
2017-10-12 11:12:52 Opening utun (connect(AF_SYS_CONTROL)): Resource busy
2017-10-12 11:12:52 Opened utun device utun1
2017-10-12 11:12:52 do_ifconfig, tt->ipv6=0, tt->did_ifconfig_ipv6_setup=0
2017-10-12 11:12:52 MANAGEMENT: >STATE:1507831972,ASSIGN_IP,,10.8.0.3,
2017-10-12 11:12:52 /sbin/ifconfig utun1 delete
                                        ifconfig: ioctl (SIOCDIFADDR): Can't assign requested address
2017-10-12 11:12:52 NOTE: Tried to delete pre-existing tun/tap instance -- No Problem if failure
2017-10-12 11:12:52 /sbin/ifconfig utun1 10.8.0.3 10.8.0.3 netmask 255.255.255.0 mtu 1500 up
2017-10-12 11:12:52 /sbin/route add -net 10.8.0.0 10.8.0.3 255.255.255.0
                                        add net 10.8.0.0: gateway 10.8.0.3
2017-10-12 11:12:52 /Applications/Tunnelblick.app/Contents/Resources/client.up.tunnelblick.sh -9 -d -f -m -w -ptADGNWradsgnw utun1 1500 1570 10.8.0.3 255.255.255.0 init
                                        **********************************************
                                        Start of output from client.up.tunnelblick.sh
                                        Disabled IPv6 for 'Display Ethernet'
                                        Disabled IPv6 for 'Display FireWire'
                                        Disabled IPv6 for 'Wi-Fi'
                                        Disabled IPv6 for 'Bluetooth PAN'
                                        Disabled IPv6 for 'Thunderbolt Bridge'
                                        Retrieved from OpenVPN: name server(s) [ 192.168.1.1 ], search domain(s) [  ] and SMB server(s) [  ] and using default domain name [ openvpn ]
                                        Not aggregating ServerAddresses because running on OS X 10.6 or higher
                                        Setting search domains to 'openvpn' because running under OS X 10.6 or higher and the search domains were not set manually (or are allowed to be changed) and 'Prepend domain name to search domains' was not selected
                                        Saved the DNS and SMB configurations so they can be restored
                                        Changed DNS ServerAddresses setting from '10.0.2.2' to '192.168.1.1'
                                        Changed DNS SearchDomains setting from '' to 'openvpn'
                                        Changed DNS DomainName setting from '' to 'openvpn'
                                        Did not change SMB NetBIOSName setting of ''
                                        Did not change SMB Workgroup setting of ''
                                        Did not change SMB WINSAddresses setting of ''
                                        DNS servers '192.168.1.1' will be used for DNS queries when the VPN is active
                                        NOTE: The DNS servers do not include any free public DNS servers known to Tunnelblick. This may cause DNS queries to fail or be intercepted or falsified even if they are directed through the VPN. Specify only known public DNS servers or DNS servers located on the VPN network to avoid such problems.
                                        Flushed the DNS cache via dscacheutil
                                        /usr/sbin/discoveryutil not present. Not flushing the DNS cache via discoveryutil
                                        Notified mDNSResponder that the DNS cache was flushed
                                        Setting up to monitor system configuration with process-network-changes
                                        End of output from client.up.tunnelblick.sh
                                        **********************************************
2017-10-12 11:12:56 *Tunnelblick: No 'connected.sh' script to execute
2017-10-12 11:12:56 /sbin/route add -net *.*.*.* 10.0.2.2 255.255.255.255
                                        add net *.*.*.*: gateway 10.0.2.2
2017-10-12 11:12:56 /sbin/route add -net 0.0.0.0 10.8.0.1 128.0.0.0
                                        add net 0.0.0.0: gateway 10.8.0.1
2017-10-12 11:12:56 /sbin/route add -net 128.0.0.0 10.8.0.1 128.0.0.0
                                        add net 128.0.0.0: gateway 10.8.0.1
2017-10-12 11:12:56 MANAGEMENT: >STATE:1507831976,ADD_ROUTES,,,
2017-10-12 11:12:56 /sbin/route add -net 10.8.0.1 10.8.0.1 255.255.255.255
                                        route: writing to routing socket: Can't assign requested address
                                        add net 10.8.0.1: gateway 10.8.0.1: Can't assign requested address
2017-10-12 11:12:56 /sbin/route add -net 10.8.0.0 10.8.0.1 255.255.255.0
                                        route: writing to routing socket: File exists
                                        add net 10.8.0.0: gateway 10.8.0.1: File exists
2017-10-12 11:12:56 /sbin/route add -net 192.168.1.0 10.8.0.1 255.255.255.0
                                        add net 192.168.1.0: gateway 10.8.0.1
2017-10-12 11:12:56 Initialization Sequence Completed
2017-10-12 11:12:56 MANAGEMENT: >STATE:1507831976,CONNECTED,SUCCESS,10.8.0.3,*.*.*.*
```

I _can_ ping 10.8.0.1

192.168.1.1 is my router, and I _cannot_ ping it. I can't curl it either (it has a web interface on 80).

I _cannot_ ping 8.8.8.8

```
egrep *ip_forward=. /etc/sysctl.d/*sysctl.conf
net.ipv4.ip_forward=1
```

Not problem at all with the questions. Thanks so much for the help!

**Comment by cfcolaco** [comment] 2017-10-12 19:20
Ok I think I might found where the problem is ... 

```
-P PREROUTING ACCEPT
-P INPUT ACCEPT
-P OUTPUT ACCEPT
-P POSTROUTING ACCEPT
-N DOCKER
>>>> Move HERE <<<<<
-A PREROUTING -m addrtype --dst-type LOCAL -j DOCKER
-A OUTPUT ! -d 127.0.0.0/8 -m addrtype --dst-type LOCAL -j DOCKER
-A POSTROUTING -s 172.17.0.0/16 ! -o docker0 -j MASQUERADE
-A POSTROUTING -s 10.8.0.0/24 -o eth0 -j MASQUERADE <<<<<------- NOT HERE
-A DOCKER -i docker0 -j RETURN
>>>>> OR MOVE HERE <<<<<
```

I am no expert in understanding IPTables but one think i Know is that IP Tables runs the rules TOP/Down ... 
So the rule being there, for me doesn't sound quite right!!
So easiest way to try to check this out,

```
cp /etc/iptables/rules.v4 /etc/iptables/rules.v4_backup
```
Edit the ```/etc/iptables/rules.v4/``` file and move the rule to one of the places I have shown you.

Then ```sudo iptables-restore etc/iptables/rules.v4 && sudo iptables -t nat -S``` 

and confirm if the rule I have mentioned is where you placed it. 
Try to connect and test. 
Repeat the process every time you move a rule to a different place! 


BE AWARE OF 2 THINGS: 

1 - you MUST connect to the VPN from outside of your internal network!!! 

2 - your ``` /etc/iptables/rules.v4```

should be something similar to this!!  edit only between the regions MARKED Below!! 

```
# Generated by iptables-save v1.6.0 on Sun Oct  8 18:07:31 2017
*nat
:PREROUTING ACCEPT [0:0]
:INPUT ACCEPT [0:0]
:OUTPUT ACCEPT [1:168]
:POSTROUTING ACCEPT [1:168]
<<<<<< HERE >>>>>>
-N DOCKER
-A PREROUTING -m addrtype --dst-type LOCAL -j DOCKER
-A OUTPUT ! -d 127.0.0.0/8 -m addrtype --dst-type LOCAL -j DOCKER
-A POSTROUTING -s 172.17.0.0/16 ! -o docker0 -j MASQUERADE
-A POSTROUTING -s 10.8.0.0/24 -o eth0 -j MASQUERADE
-A DOCKER -i docker0 -j RETURN
<<<<<HERE>>>>>>
COMMIT
# Completed on Sun Oct  8 18:07:31 2017
# Generated by iptables-save v1.6.0 on Sun Oct  8 18:07:31 2017
*filter
:INPUT ACCEPT [4562:567745]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [4486:521725]
COMMIT
# Completed on Sun Oct  8 18:07:31 2017
```

3 - You might have to thinker around with those rules to get it right!! After PiVPN starts working Docker might fail!! so ... its kind of trial and error situation ... but I am almost sure that the problem is there!! 

You can even try to remove all the docker rules and leave only the 

```-A POSTROUTING -s 10.8.0.0/24 -o eth0 -j MASQUERADE```

and see if it works!! 

Sorry for the long post... and for the "instructions for dummies" style ... but as I don't know how comfortable you are .. better to explain everything!! if you have any questions just shout! =)

**Comment by pkulak** [comment] 2017-10-13 04:00
Wow, I took your advice, and slowly started hacking away at my iptables until I got down to this:

```
-P PREROUTING ACCEPT
-P INPUT ACCEPT
-P OUTPUT ACCEPT
-P POSTROUTING ACCEPT
-A POSTROUTING -s 10.8.0.0/24 -o eth0 -j MASQUERADE
```

Still no dice! I may actually just wipe my Pi clean, start over, and do a clean install of everything with no docker. I really want to get this VPN working. haha

**Comment by cfcolaco** [comment] 2017-10-13 09:11
@pkulak before wiping!! =P 
There is no learning in wiping and starting over!! =P 
 
(keep the backup we created previously safe!! ) 

Replace the content of your /etc/iptables/rules.v4 file with this or confirm that it looks like this!! 

```
*nat
:PREROUTING ACCEPT [0:0]
:INPUT ACCEPT [0:0]
:OUTPUT ACCEPT [1:168]
:POSTROUTING ACCEPT [1:168]
-A POSTROUTING -s 10.8.0.0/24 -o eth0 -j MASQUERADE
COMMIT
*filter
:INPUT ACCEPT [4562:567745]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [4486:521725]
COMMIT
```

then do

```
sudo iptables-restore /etc/iptables/rules.v4 
sudo iptables -t nat -S
sudo iptables -S 
```
Confirm that it matches with the config on the file! 
Reboot the pi!! 

and try again! ;) 

You can connect to the pi from outside ... so the problem is it is not routing properly! 
Can be the case that your MAC is not getting the routes also!!
but for now let's just make this test!

**Comment by pkulak** [comment] 2017-10-14 05:23
Woo! That did it! I'm posting this response from my phone's hotspot through my Pi, connected to PiHole for my DNS. Thanks so much!

Of course, now I've hosed my docker install, but I'm fine with that. I set it up as a bit of an experiment to see if running all my stuff in containers would be easier... it hasn't been! I'll just install Plex directly and be done with it. :D

**Comment by cfcolaco** [comment] 2017-10-14 07:45
Great is has been solved!! 
If you want we can try to fix your iptables to have docker working. 

Meanwhile closing the issue ... however feel free to add any comment.

**Closed by cfcolaco** 2017-10-14 07:45 UTC
