### ISSUE TITLE
Password for private key is empty

### ISSUE THREAD

**Issue by LKay** [pivpn/pivpn#372] opened 2017-10-08 08:35 UTC
## Console output of `pivpn debug`
```
::: Generating Debug Output
:::                                     :::
::              PiVPN Debug              ::
:::                                     :::
::      Latest Commit                    ::
:::                                     :::
commit 454b755116d8cad6b67b56ac15a7235ceac02b5a
Merge: b3ebdb8 f385a3e
Author: redfast00 <redfast00@users.noreply.github.com>
Date:   Sat Aug 12 14:15:34 2017 +0200

    Merge pull request #333 from jhealy86/patch-1

    fix markdown link syntax
:::                                     :::
::      Recursive list of files in       ::
::      /etc/openvpn/easy-rsa/pki        ::
:::                                     :::
/etc/openvpn/easy-rsa/pki/:
ca.crt
crl.pem
Default.txt
dh2048.pem
index.txt
index.txt.attr
index.txt.attr.old
index.txt.old
issued
private
serial
serial.old
ta.key

/etc/openvpn/easy-rsa/pki/issued:
server.crt

/etc/openvpn/easy-rsa/pki/private:
ca.key
server.key
:::                                     :::
::      Output of /etc/pivpn/*           ::
:::                                     :::
:: START /etc/pivpn/DET_PLATFORM ::
Raspbian
:: END /etc/pivpn/DET_PLATFORM ::
:: START /etc/pivpn/INSTALL_PORT ::
1194
:: END /etc/pivpn/INSTALL_PORT ::
:: START /etc/pivpn/INSTALL_PROTO ::
udp
:: END /etc/pivpn/INSTALL_PROTO ::
:: START /etc/pivpn/INSTALL_USER ::
pi
:: END /etc/pivpn/INSTALL_USER ::
:: START /etc/pivpn/NO_UFW ::
1
:: END /etc/pivpn/NO_UFW ::
:: START /etc/pivpn/pivpnINTERFACE ::
eth0
:: END /etc/pivpn/pivpnINTERFACE ::
:: START /etc/pivpn/REVOKE_STATUS ::
1
:: END /etc/pivpn/REVOKE_STATUS ::
:::                                     :::
:: /etc/openvpn/easy-rsa/pki/Default.txt ::
:::                                     :::
client
dev tun
proto udp
remote vpn.local 1194
resolv-retry infinite
nobind
persist-key
persist-tun
key-direction 1
remote-cert-tls server
tls-version-min 1.2
verify-x509-name server name
cipher AES-256-CBC
auth SHA256
comp-lzo
verb 1
:::                                     :::
::      Debug Output Complete            ::
:::                                     :::
:::
::: Debug output completed above.
::: Copy saved to /tmp/debug.txt
:::
```

## Issue

Creating new user with both `pivpn add` or `pivpn add nopass` succeeds but if I create a profile with password the generated `.ovpn` file when imported to OpenVPN client doest not connect and returns error saying: `Core exception: connection error: PEM_PASSWORD_FAILED: PolarSSL error parsing config private key : PK - Private key password can't be empty`.

It however works and connects fine when profile is generated without password. Looks like the password entered for `pivpn add` is ignored and private key for profile is created with empty password.

**Comment by cfcolaco** [comment] 2017-10-08 09:19
That's Odd!! even yesterday installed PiVPN on a couple of times on a VPS and it worked perfectly! =S 

don't even know what to think of this! =S can be the case of some special character you are entering the cause of the issue? try with a simple password like 12345 just for testing purposes ...

**Comment by LKay** [comment] 2017-10-08 09:42
I tried even simple passwords like `12345678` or `testtest` and none have worked. I also tried to change private key encryption as described [here](https://www.reddit.com/r/raspberry_pi/comments/6w0dxs/openvpnpivpn_on_raspbian_stretch_error_parsing/) or [here](https://github.com/pivpn/pivpn/issues/346) and nothing works. I can only connect to the server if profile is created using `pivpn add nopass` which does not require any password (poor security).

**Comment by cfcolaco** [comment] 2017-10-08 16:35
that's gotta be a local issue on your side.... 

Just tested 5++ new pivpn installs today and none gave me that kind of issue! 

Wondering how can we track such thing!

**Comment by killermosi** [comment] 2017-10-09 15:02
No issues here, too, I have installed PiVPN on a fresh Stretch install and the keys generated just fine.

Is it possible to attach one of the faulty `.ovpn` files? (just be sure to edit out any sensitive info, like the server name and half or more of the certificate/keys where present)

**Comment by cfcolaco** [comment] 2017-10-30 21:21
Closing issue, assuming issue resolved. 

@LKay any further questions post here .. I will reopen if needed!

**Closed by cfcolaco** 2017-10-30 21:21 UTC

**Comment by gorbehnare** [comment] 2018-10-27 17:43
Hello

I am experiencing exact same issue. This is a brand new Raspberry Pi3 with new installation of PiVPN (this is my first time setting this up). 

Anyone found any solutions or know how or why this happens?

Best regards

**Comment by gorbehnare** [comment] 2018-10-27 20:18
Here are the client error: 
`CLIENT_EXCEPTION : connect error: PEM_PASSWORD_FAIL: mbed TLS: error parsing config private key : PK - Private key password can't be empty [FATAL-ERR]
FATAL:CLIENT_EXCEPTION: connect error: PEM_PASSWORD_FAIL: mbed TLS: error parsing config private key : PK - Private key password can't be empty
`

**Comment by gorbehnare** [comment] 2018-10-27 22:05
After wasting almost an entire day I found the solution/work around in case anyone is stuck with this. The issue is not with the PiVPN, but with the OpenVPN client. Since this is my first time ever using OpenVPN I downloaded "OpenVPN Connect" as client, and this client does not ask for password when connecting. 
Downloaded and installed full OpenVPN client (including OpenVPN GUI) and it must be "Run as Administrator" and it asks for password and connects without any issues.

**Comment by SamRavenWall** [comment] 2018-11-08 12:52
Thanks @gorbehnare ! I also downloaded open VPN connect instead of the openVPN client.

**Comment by b-scherer** [comment] 2019-04-28 18:24
Thank you @gorbehnare same issue here!

**Comment by J-Robinson042519** [comment] 2019-11-29 06:10
had the same issue.  updated to openvpn connect ver 3 and it worked.

**Comment by rmanalan** [comment] 2020-01-15 17:04
Same issue. I downloaded TunnelBlick for macos and it worked great.

**Comment by dotshap** [comment] 2024-03-26 05:38
same issue
