### ISSUE TITLE
Is it possible to run two separate instances of OpenVPN on one Pi?

### ISSUE THREAD

**Issue by globbergouhl** [pivpn/pivpn#352] opened 2017-09-08 01:16 UTC
Apart from the first VPN feeding into tun0 adapter, I would like to have a second independent VPN feeding into a tun1. Is this possible? The reason for this is that I want to redirect all traffic coming in through tun1 into TOR, while tun0 does not go to TOR.

**Comment by redfast00** [comment] 2017-09-08 09:08
Yes, this is possible, just add a second config file on the server.

**Comment by AABatteries** [comment] 2017-10-02 10:32
Simply adding a second config file and restarting openvpn would result in running two instances?

```
/etc/openvpn/private_tunnel.conf
/etc/openvpn/dedicated_gaming_tunnel.conf
```
Does this look ok? I'm trying to set up listening on two different ports because OpenVPN does not support doing so in a single instance

**Comment by InnovativeInventor** [comment] 2017-10-02 11:40
You could just use a vm or something like docker.

**Comment by redfast00** [comment] 2017-10-03 14:58
You should remove the extra systemd service: openvpn does this for you. What are the permissions on the config files?

**Comment by AABatteries** [comment] 2017-10-03 15:36
Permissions for both config files are 0644

I stopped the extra systemd service, and did `systemctl restart openvpn` - I'm still getting connection refused (code = 111)  on port 443 while the other port still works fine

**Comment by jvaleros** [comment] 2017-10-11 01:29
No need for all this trouble, you can just create two separate instances with the two ports you want and change some basic details like the ip ranges given by each server. I  was able to fo it following @vincentkenny01 instructions. [Post in pivpn github](https://github.com/pivpn/pivpn/issues/178)

**Comment by AABatteries** [comment] 2017-10-12 10:07
@jvaleros how do you create an .ovpn file for the client then? -a option for pivpn does not support it, it will just generate .ovpn for the default server.conf. Do you just make a copy and edit some of the parameters? I was still unable to make this work, still getting connection refused and 


```
11:53 SIGUSR1[connection failed(soft),init_instance] received, process restarting
```


I think I'll post my questions to the other thread. I followed instructions step-by-step, not sure where the problem is. Did you rename tun device in the second server config file? Or did you leave both tun device names the same?

**Comment by cfcolaco** [comment] 2017-10-26 21:57
@AABatteries  ... am I the only one seeing the missing sudo in 

'''raspberrypi:/etc/openvpn $ systemctl start openvpn@server_443.service'''  ??? 

I don't just throwing a wild guess since I just looked over this! =)

**Comment by cfcolaco** [comment] 2017-10-26 22:02
@AABatteries now that I have read the whole thread .. have you managed to put everything working?? 

Actually the script does not support the creation of ovpn files for different config files ... that i actually something you need to do yourself! =/ maybe in the future we can add that feature ... but right now ... I dont see it comming so soon .. unles you want to role up your sleeves, we will be glad to accept Pull requests! =)

**Comment by cfcolaco** [comment] 2017-10-30 21:40
Closing issue .. as I don't see major priority on this! 

@redfast00 @0-kaladin will probably put this in the contributions part of the readme in case some one wants to role up sleeves and make the script support multiple instances of OpenVPN

**Closed by cfcolaco** 2017-10-30 21:40 UTC
