### ISSUE TITLE
[Support] <Running WIreguard server AND openvpn client on same pi>

### ISSUE THREAD

**Issue by rmystique** [pivpn/pivpn#1006] opened 2020-04-02 06:08 UTC
So I have the wire guard server running fine and can connect from my android to it and have web access through the vpn, but when I start the openvpn client I can no longer connect to the wireguard server and hence no web access. I am using a ddns to update my ip so the android has the current ip of the pi.

Here is my iptables:

# Generated by iptables-save v1.8.2 on Wed Apr  1 20:58:16 2020
*nat
:PREROUTING ACCEPT [95:20399]
:INPUT ACCEPT [77:19012]
:OUTPUT ACCEPT [139:9073]
:POSTROUTING ACCEPT [139:9073]
-A POSTROUTING -s 10.6.0.0/24 -o eth0 -m comment --comment wireguard-nat-rule -j MASQUERADE
-A POSTROUTING -s 10.6.0.0/24 -o tun0 -j MASQUERADE
COMMIT
# Completed on Wed Apr  1 20:58:16 2020
# Generated by iptables-save v1.8.2 on Wed Apr  1 20:58:16 2020
*filter
:INPUT ACCEPT [15201:19874102]
:FORWARD ACCEPT [258:70145]
:OUTPUT ACCEPT [9297:744681]
COMMIT
# Completed on Wed Apr  1 20:58:16 2020

And WG0.CONF:

[Interface]
PrivateKey = xxxxxx
Address = 10.6.0.1/24
ListenPort = 12704
# begin mine
[Peer]
PublicKey = xxxx
PresharedKey = xxxx
AllowedIPs = 10.6.0.2/32
# end

**Comment by orazioedoardo** [comment] 2020-04-02 06:56
Duplicate of https://github.com/pivpn/pivpn/issues/968

**Closed** 2020-04-02 06:56 UTC

**Comment by rmystique** [comment] 2020-04-02 07:27
These are not the same issue , I already have both installed the problem is
when both are running the connection is dropped, seems to be some sort of
routing or Nat issue

**Comment by orazioedoardo** [comment] 2020-04-02 07:55
Ok but this setup is not supported as of today.

Anyways I think the error is here:
` -A POSTROUTING -s 10.6.0.0/24 -o tun0 -j MASQUERADE`

PiVPN uses 10.8.0.0/24 for OpenVPN.
