### ISSUE TITLE
No connection with new raspberry pi

### ISSUE THREAD

**Issue by surak** [pivpn/pivpn#862] opened 2019-11-05 15:46 UTC
## In raising this issue, I confirm the following: 

`{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting can be *is* directly related to the pivpn installer script.
- [X] The issue I am reporting isn't a duplicate (see [FAQs]

### Issue

Can't connect. I have done the same as the previous raspberry pi, and replaced the router port for the new raspberry.

I get an initial handshake, but it gets stalled afterwards.

I tried this: https://github.com/angristan/openvpn-install/commit/ad3c223385a9aa323227633fcc5e456d1235e873 but makes it worse.

The difference from this and the previous raspberry pi is essentially that this one has docker installed (for other hass.io) and this one is connected with ethernet.

Output from server.log:
```
Nov  5 16:36:10 pi4-server ovpn-server[1214]: EXTERNALIP:39284 TLS: Initial packet from [AF_INET]EXTERNALIP:39284, sid=e1560ebf 1701ac50
Nov  5 16:36:22 pi4-server ovpn-server[1214]: EXTERNALIP:59532 TLS: Initial packet from [AF_INET] EXTERNALIP:59532, sid=39c66d21 1c09b6cd
Nov  5 16:37:11 pi4-server ovpn-server[1214]: EXTERNALIP:39284 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
Nov  5 16:37:11 pi4-server ovpn-server[1214]: EXTERNALIP:39284 TLS Error: TLS handshake failed
Nov  5 16:37:11 pi4-server ovpn-server[1214]: EXTERNALIP:39284 SIGUSR1[soft,tls-error] received, client-instance restarting
Nov  5 16:37:22 pi4-server ovpn-server[1214]: EXTERNALIP:59532 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
Nov  5 16:37:22 pi4-server ovpn-server[1214]: EXTERNALIP:59532 TLS Error: TLS handshake failed
Nov  5 16:37:22 pi4-server ovpn-server[1214]: EXTERNALIP:59532 SIGUSR1[soft,tls-error] received, client-instance restarting
Nov  5 16:37:27 pi4-server ovpn-server[1214]: EXTERNALIP:55781 TLS: Initial packet from [AF_INET]EXTERNALIP:55781, sid=d33f59ce 4f8672e2
```
### Have you searched for similar issues and solutions?
 Yes. I wouldn't report if I would have found a solution.

### Console output of      `pivpn debug`
```
::::		PiVPN debug		 ::::
=============================================
::::		Latest commit		 ::::
commit d0c10db6ec391961b7201fb564055c1176ca73e3
Author: 4s3ti <cfcolaco@colacoweb.net>
Date:   Tue Sep 3 10:09:48 2019 +0200

    install.sh: apt-get with , uninstall.sh: added var PKG_MANAGER and replaced apt-get with
=============================================
::::	    Installation settings    	 ::::
/etc/pivpn/DET_PLATFORM -> Raspbian
/etc/pivpn/FORWARD_CHAIN_EDITED -> 1
/etc/pivpn/HELP_SHOWN -> 
/etc/pivpn/INPUT_CHAIN_EDITED -> 0
/etc/pivpn/INSTALL_PORT -> 1194
/etc/pivpn/INSTALL_PROTO -> udp
/etc/pivpn/INSTALL_USER -> pi
/etc/pivpn/NO_UFW -> 1
/etc/pivpn/TWO_POINT_FOUR -> 
/etc/pivpn/pivpnINTERFACE -> eth0
=============================================
::::	setupVars file shown below	 ::::
INSTALL_USER=pi
UNATTUPG=unattended-upgrades
pivpnInterface=eth0
IPv4dns=
IPv4addr=192.168.2.118
IPv4gw=192.168.2.1
pivpnProto=udp
PORT=1194
ENCRYPT=256
APPLY_TWO_POINT_FOUR=true
DOWNLOAD_DH_PARAM=false
PUBLICDNS=REMOTE
OVPNDNS1=208.67.222.222
OVPNDNS2=208.67.220.220
=============================================
::::  Server configuration shown below   ::::
dev tun
proto udp
port 1194
ca /etc/openvpn/easy-rsa/pki/ca.crt
cert /etc/openvpn/easy-rsa/pki/issued/pi4-server_496a117c-bd02-4dfc-94cb-0decb1856bc6.crt
key /etc/openvpn/easy-rsa/pki/private/pi4-server_496a117c-bd02-4dfc-94cb-0decb1856bc6.key
dh none
topology subnet
server 10.8.0.0 255.255.255.0
# Set your primary domain name server address for clients
push "dhcp-option DNS 208.67.222.222"
push "dhcp-option DNS 208.67.220.220"
# Prevent DNS leaks on Windows
push "block-outside-dns"
# Override the Client default gateway by using 0.0.0.0/1 and
# 128.0.0.0/1 rather than 0.0.0.0/0. This has the benefit of
# overriding but not wiping out the original default gateway.
push "redirect-gateway def1"
client-to-client
keepalive 1800 3600
remote-cert-tls client
tls-version-min 1.2
tls-crypt /etc/openvpn/easy-rsa/pki/ta.key
cipher AES-256-CBC
# local 192.168.2.118
auth SHA256
user nobody
group nogroup
persist-key
persist-tun
crl-verify /etc/openvpn/crl.pem
status /var/log/openvpn-status.log 20
status-version 3
syslog
verb 3
#DuplicateCNs allow access control on a less-granular, per user basis.
#Remove # if you will manage access by user instead of device. 
#duplicate-cn
# Generated for use by PiVPN.io
=============================================
::::  Client template file shown below   ::::
client
dev tun
proto udp
remote REMOTE 1194
resolv-retry infinite
nobind
persist-key
persist-tun
remote-cert-tls server
tls-version-min 1.2
verify-x509-name pi4-server_496a117c-bd02-4dfc-94cb-0decb1856bc6 name
cipher AES-256-CBC
auth SHA256
auth-nocache
verb 3
=============================================
:::: 	Recursive list of files in	 ::::
::: /etc/openvpn/easy-rsa/pki shows below :::
/etc/openvpn/easy-rsa/pki/:
Default.txt
ca.crt
crl.pem
ecparams
extensions.temp
index.txt
index.txt.attr
index.txt.attr.old
index.txt.old
issued
openssl-easyrsa.cnf
private
renewed
revoked
safessl-easyrsa.cnf
serial
serial.old
strube.ovpn
ta.key

/etc/openvpn/easy-rsa/pki/ecparams:
prime256v1.pem

/etc/openvpn/easy-rsa/pki/issued:
pi4-server_496a117c-bd02-4dfc-94cb-0decb1856bc6.crt
strube.crt

/etc/openvpn/easy-rsa/pki/private:
ca.key
pi4-server_496a117c-bd02-4dfc-94cb-0decb1856bc6.key
strube.key

/etc/openvpn/easy-rsa/pki/renewed:
private_by_serial
reqs_by_serial

/etc/openvpn/easy-rsa/pki/renewed/private_by_serial:

/etc/openvpn/easy-rsa/pki/renewed/reqs_by_serial:

/etc/openvpn/easy-rsa/pki/revoked:
private_by_serial
reqs_by_serial

/etc/openvpn/easy-rsa/pki/revoked/private_by_serial:

/etc/openvpn/easy-rsa/pki/revoked/reqs_by_serial:
=============================================
::::		Self check		 ::::
:: [OK] IP forwarding is enabled
:: [OK] Iptables MASQUERADE rule set
:: [OK] Iptables FORWARD rule set
:: [OK] OpenVPN is running
:: [OK] OpenVPN is enabled (it will automatically start on reboot)
:: [OK] OpenVPN is listening on port 1194/udp
=============================================
::::      Snippet of the server log      ::::
Nov  5 16:37:22 pi4-server ovpn-server[1214]: REDACTED:59532 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
Nov  5 16:37:22 pi4-server ovpn-server[1214]: REDACTED:59532 TLS Error: TLS handshake failed
Nov  5 16:37:22 pi4-server ovpn-server[1214]: REDACTED:59532 SIGUSR1[soft,tls-error] received, client-instance restarting
Nov  5 16:37:27 pi4-server ovpn-server[1214]: REDACTED:55781 TLS: Initial packet from [AF_INET]REDACTED:55781, sid=d33f59ce 4f8672e2
Nov  5 16:38:27 pi4-server ovpn-server[1214]: REDACTED:55781 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
Nov  5 16:38:27 pi4-server ovpn-server[1214]: REDACTED:55781 TLS Error: TLS handshake failed
Nov  5 16:38:27 pi4-server ovpn-server[1214]: REDACTED:55781 SIGUSR1[soft,tls-error] received, client-instance restarting
Nov  5 16:38:32 pi4-server ovpn-server[1214]: REDACTED:45883 TLS: Initial packet from [AF_INET]REDACTED:45883, sid=50ad0662 77715e6b
Nov  5 16:39:32 pi4-server ovpn-server[1214]: REDACTED:45883 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
Nov  5 16:39:32 pi4-server ovpn-server[1214]: REDACTED:45883 TLS Error: TLS handshake failed
Nov  5 16:39:32 pi4-server ovpn-server[1214]: REDACTED:45883 SIGUSR1[soft,tls-error] received, client-instance restarting
Nov  5 16:39:37 pi4-server ovpn-server[1214]: REDACTED:52596 TLS: Initial packet from [AF_INET]REDACTED:52596, sid=c03bf058 dfdf96a3
Nov  5 16:40:37 pi4-server ovpn-server[1214]: REDACTED:52596 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
Nov  5 16:40:37 pi4-server ovpn-server[1214]: REDACTED:52596 TLS Error: TLS handshake failed
Nov  5 16:40:37 pi4-server ovpn-server[1214]: REDACTED:52596 SIGUSR1[soft,tls-error] received, client-instance restarting
Nov  5 16:40:42 pi4-server ovpn-server[1214]: REDACTED:50288 TLS: Initial packet from [AF_INET]REDACTED:50288, sid=2c49a598 60397348
Nov  5 16:41:42 pi4-server ovpn-server[1214]: REDACTED:50288 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
Nov  5 16:41:42 pi4-server ovpn-server[1214]: REDACTED:50288 TLS Error: TLS handshake failed
Nov  5 16:41:42 pi4-server ovpn-server[1214]: REDACTED:50288 SIGUSR1[soft,tls-error] received, client-instance restarting
Nov  5 16:41:52 pi4-server ovpn-server[1214]: REDACTED:53815 TLS: Initial packet from [AF_INET]REDACTED:53815, sid=f7047d24 7b260a21
=============================================
::::		Debug complete		 ::::
::: 
::: Debug output completed above.
::: Copy saved to /tmp/debug.txt
::: 

```
### Have you taken any steps towards solving your issue?
```
  reinstalling, removing everything and starting from scratch, adding the "local" thing suggested elsewhere, like here: https://github.com/angristan/openvpn-install/commit/ad3c223385a9aa323227633fcc5e456d1235e873
```

Output from client:

```
openvpn --config ovpns/strube.ovpn
Tue Nov  5 16:45:01 2019 OpenVPN 2.4.7 arm-unknown-linux-gnueabihf [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Feb 20 2019
Tue Nov  5 16:45:01 2019 library versions: OpenSSL 1.1.1d  10 Sep 2019, LZO 2.10
Enter Private Key Password: ************
Tue Nov  5 16:45:04 2019 Outgoing Control Channel Encryption: Cipher 'AES-256-CTR' initialized with 256 bit key
Tue Nov  5 16:45:04 2019 Outgoing Control Channel Encryption: Using 256 bit message hash 'SHA256' for HMAC authentication
Tue Nov  5 16:45:04 2019 Incoming Control Channel Encryption: Cipher 'AES-256-CTR' initialized with 256 bit key
Tue Nov  5 16:45:04 2019 Incoming Control Channel Encryption: Using 256 bit message hash 'SHA256' for HMAC authentication
Tue Nov  5 16:45:04 2019 TCP/UDP: Preserving recently used remote address: [AF_INET]87.164.228.150:1194
Tue Nov  5 16:45:04 2019 Socket Buffers: R=[163840->163840] S=[163840->163840]
Tue Nov  5 16:45:04 2019 UDP link local: (not bound)
Tue Nov  5 16:45:04 2019 UDP link remote: [AF_INET]REDACTED:1194
```

and new output after trying this:

```
Nov  5 16:45:04 pi4-server ovpn-server[1214]: REDACTED:52653 TLS: Initial packet from [AF_INET]87.164.228.150:52653, sid=079cb2a3 cfabc880
Nov  5 16:45:52 pi4-server ovpn-server[1214]: REDACTED:40631 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
Nov  5 16:45:52 pi4-server ovpn-server[1214]: REDACTED:40631 TLS Error: TLS handshake failed
Nov  5 16:45:52 pi4-server ovpn-server[1214]: REDACTED:40631 SIGUSR1[soft,tls-error] received, client-instance restarting

```

**Comment by 4s3ti** [comment] 2019-11-07 00:10
> The difference from this and the previous raspberry pi is essentially that this one has docker installed (for other hass.io) and this one is connected with ethernet.

That's is exactly why .. PiVPN doesn't play nice when installed with docker, you have either to thinker with IPTables, remove docker or if you really want docker you are probably better off running it inside a docker container ... might wanna give this a try:  https://github.com/InnovativeInventor/docker-pivpn

**Comment by surak** [comment] 2019-11-07 14:51
Hi, thanks.

I would like to give it a shot at the iptables thing. Do you know what one conflict with the other? It's worth a shot

**Comment by 4s3ti** [comment] 2019-11-07 19:44
I avoid docker on pis at all costs .. so i don't really know where the conflict is ... but if you post here the output of 
`sudo iptables -S`
and
`sudo iptables -t nat -S`

we might give it a shot

**Comment by surak** [comment] 2019-11-07 21:39
Sure, here: 
```sh
$ sudo iptables -S
-P INPUT ACCEPT
-P FORWARD ACCEPT
-P OUTPUT ACCEPT
-N DOCKER
-N DOCKER-ISOLATION-STAGE-1
-N DOCKER-ISOLATION-STAGE-2
-N DOCKER-USER
-A FORWARD -j DOCKER-USER
-A FORWARD -j DOCKER-ISOLATION-STAGE-1
-A FORWARD -o docker0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -o docker0 -j DOCKER
-A FORWARD -i docker0 ! -o docker0 -j ACCEPT
-A FORWARD -i docker0 -o docker0 -j ACCEPT
-A FORWARD -o hassio -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -o hassio -j DOCKER
-A FORWARD -i hassio ! -o hassio -j ACCEPT
-A FORWARD -i hassio -o hassio -j ACCEPT
-A FORWARD -d 10.8.0.0/24 -i eth0 -o tun0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -s 10.8.0.0/24 -i tun0 -o eth0 -j ACCEPT
-A FORWARD -d 10.8.0.0/24 -i eth0 -o tun0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -s 10.8.0.0/24 -i tun0 -o eth0 -j ACCEPT
-A DOCKER-ISOLATION-STAGE-1 -i docker0 ! -o docker0 -j DOCKER-ISOLATION-STAGE-2
-A DOCKER-ISOLATION-STAGE-1 -i hassio ! -o hassio -j DOCKER-ISOLATION-STAGE-2
-A DOCKER-ISOLATION-STAGE-1 -j RETURN
-A DOCKER-ISOLATION-STAGE-2 -o docker0 -j DROP
-A DOCKER-ISOLATION-STAGE-2 -o hassio -j DROP
-A DOCKER-ISOLATION-STAGE-2 -j RETURN
-A DOCKER-USER -j RETURN
```

and

```
 $ sudo iptables -t nat -S
-P PREROUTING ACCEPT
-P INPUT ACCEPT
-P OUTPUT ACCEPT
-P POSTROUTING ACCEPT
-N DOCKER
-A PREROUTING -m addrtype --dst-type LOCAL -j DOCKER
-A OUTPUT ! -d 127.0.0.0/8 -m addrtype --dst-type LOCAL -j DOCKER
-A POSTROUTING -s 172.17.0.0/16 ! -o docker0 -j MASQUERADE
-A POSTROUTING -s 172.30.32.0/23 ! -o hassio -j MASQUERADE
-A POSTROUTING -s 10.8.0.0/24 -o eth0 -j MASQUERADE
-A POSTROUTING -s 10.8.0.0/24 -o eth0 -j MASQUERADE
-A POSTROUTING -s 10.8.0.0/24 -o wlan0 -j MASQUERADE
-A DOCKER -i docker0 -j RETURN
-A DOCKER -i hassio -j RETURN
```

**Comment by NOT-1337** [comment] 2019-11-08 14:06
Hi surak,

I'm experiencing a similar issue. I've installed pivpn (this week) and when I try to connect from the client, which is an iPhone running iOS 13, I get an error message "mbed TLS: cert has unsupported type for external pki support". From the pivpn debug logs I get something similar to you. I've not been successful in finding much information about the client error.

When trying to find an explanation and solution to my problem my main theory is that (my) problem is caused by stricter handling of TLS certificates from iOS 13 & macOS 10.15, check this post https://support.apple.com/en-us/HT210176. I've tried to ensure that my certificates comply but so far none of my attempts been successful. Today I found http://blog.nashcom.de/nashcomblog.nsf/dx/more-strict-server-certificate-handling-in-ios-13-macos-10.15.htm?opendocument&comments#anc1. From this I suspect that I do need to use a domain name instead of IP address to the server. I will try this tonight. 

If someone can confirm my theory that would be highly appreciated.

**Comment by orazioedoardo** [comment] 2019-11-12 12:00
> I'm experiencing a similar issue. I've installed pivpn (this week) and when I try to connect from the client, which is an iPhone running iOS 13, I get an error message "mbed TLS: cert has unsupported type for external pki support". From the pivpn debug logs I get something similar to you. I've not been successful in finding much information about the client error.
@NOT-1337 wow so PiVPN is not working on iOS 13 at all? Weird, we should get a ton of reports then, I'll have a look later.

**Comment by orazioedoardo** [comment] 2019-11-12 12:06
@surak Let's try a clean Iptables setup:
```
sudo iptables -P INPUT ACCEPT
sudo iptables -P FORWARD ACCEPT
sudo iptables -P OUTPUT ACCEPT
sudo iptables -F
sudo iptables -X
sudo iptables -t nat -F
sudo iptables -t nat -X
sudo iptables -t nat -A POSTROUTING -s 10.8.0.0/24 -o eth0 -j MASQUERADE
```
Attempt a connection, and post the output of `/var/log/openvpn.log` (hide public ip's if there are any).

**Comment by NOT-1337** [comment] 2019-11-12 14:03
@orazioedoardo your valuable feedback made me take a step back and revise what I was doing. I added yet another user. This time omitting the -i option (which I had assumed was needed). I'm now able to successfully connect from my iOS 13 device. Tnx.

**Comment by 4s3ti** [comment] 2019-11-12 15:23
> @surak Let's try a clean Iptables setup:
> 
> ```
> sudo iptables -P INPUT ACCEPT
> sudo iptables -P FORWARD ACCEPT
> sudo iptables -P OUTPUT ACCEPT
> sudo iptables -F
> sudo iptables -X
> sudo iptables -t nat -F
> sudo iptables -t nat -X
> sudo iptables -t nat -A POSTROUTING -s 10.8.0.0/24 -o eth0 -j MASQUERADE
> ```
> 
> Attempt a connection, and post the output of `/var/log/openvpn.log` (hide public IPs if there are any).

@orazioedoardo that way Docker will stop working completely! 
By looking at IPTables .. i don't really think PiVPN and Docker can co-exist .. the only way would be having pivpn in a docker container.

**Comment by orazioedoardo** [comment] 2019-11-12 15:55
> @orazioedoardo that way Docker will stop working completely!
@4s3ti I know but if it works with a clean iptables, than it's just a matter of reordering some rules so PiVPN rules have the precedence.

**Comment by 4s3ti** [comment] 2019-11-12 23:26
@orazioedoardo yeah you are right there .. i believe i already did a brief attempt in the past but it didn't worked either . but i can't remember what i did so better take it from scratch again.

**Comment by orazioedoardo** [comment] 2020-01-28 13:08
No comments in a while, closing...

**Closed by orazioedoardo** 2020-01-28 13:08 UTC

**Comment by surak** [comment] 2020-01-28 20:33
If one wants to have a vpn to home, WireGuard is the way to go. It’s already part of hassio, works fast and well.
