### ISSUE TITLE
[Support] Pivpn installer not working on Ubuntu Server

### ISSUE THREAD

**Issue by Z3R0CON** [pivpn/pivpn#1206] opened 2020-12-19 06:27 UTC
`{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting can be *is* directly related to the pivpn installer script.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pivpn/pivpn/wiki/FAQ), [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed), and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen)).

### Console output of      `curl -L install.pivpn.dev | bash`
```
  curl -L https://install.pivpn.io | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   162  100   162    0     0    372      0 --:--:-- --:--:-- --:--:--   372
100 83088  100 83088    0     0  14340      0  0:00:05  0:00:05 --:--:-- 19021
:::
::: sudo will be used for the install.
::: Did not detect perfectly supported OS but,
::: Continuing installation at user's own risk...
::: Did not detect perfectly supported OS but,
::: Continuing installation at user's own risk...
::: Hostname length OK
::: Verifying free disk space...
:::
::: Checking apt-get for upgraded packages.... done!
:::
::: Your system is up to date! Continuing with PiVPN installation...
:::    Checking for git... already installed!
:::    Checking for tar... already installed!
:::    Checking for wget... already installed!
:::    Checking for curl... already installed!
:::    Checking for grep... already installed!
:::    Checking for dnsutils... already installed!
:::    Checking for whiptail... already installed!
:::    Checking for net-tools... not installed!
:::    Checking for bsdmainutils... not installed!
:::    Checking for iptables-persistent... not installed!
:::    Failed to install net-tools!
:::    Failed to install bsdmainutils!
:::    Failed to install iptables-persistent!
```

```
### Have you taken any steps towards solving your issue?
```
  Only sort of work around is to manually apt install whatever packages it fails to automatically install.
```

Is there any kind of work around to this? The moment it touches items that aren't installed it immediately fails to install them.

**Comment by 4s3ti** [comment] 2020-12-19 19:03
Duplicate of: https://github.com/pivpn/pivpn/issues/1204 

Closing.

**Closed by 4s3ti** 2020-12-19 19:03 UTC
