### ISSUE TITLE
Install quits after selecting IP address

### ISSUE THREAD

**Issue by greenones** [pivpn/pivpn#388] opened 2017-10-20 06:44 UTC
Hi all,

I'm new to PiVPN but have a fresh install of Raspbian all ready.  The OS is update to date and when I run the command: curl -L https://install.pivpn.io | bash

I click ok to This installer will transform your Raspberry Pi....

I click OK to static IP needed..

I select eth0 (available)

I choose to use my current network settings

Then it says "FYI : IP Conflict" and other text saying "It is possible your router could still try to assign this IP to a device..." etc

I click OK and the installer quits to command line reporting:

::: Static IP already configured.
: error fetching interface information: Device not found
: error fetching interface information: Device not found

Any ideas guys? I'm lost.

**Comment by greenones** [comment] 2017-10-20 07:25
To add to this..

This file: /etc/dhcpcd.conf

Does appear to have been written to with static IP details:

# A hook script is provided to lookup the hostname if not set by the DHCP
# server, but it should not be run by default.
nohook lookup-hostname
interface
    static ip_address=192.168.x.xxx
    static routers=192.168.x.xxx
    static domain_name_servers=192.168.x.xxx

**Comment by greenones** [comment] 2017-10-20 07:28
OS details:

PRETTY_NAME="Raspbian GNU/Linux 8 (jessie)"
NAME="Raspbian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

**Comment by cfcolaco** [comment] 2017-10-20 14:52
This issue seems to be happening a lot ... so today // tomorrow wil to some testing about this ... meanwhile ... can you uninstall pivpn 

```pivpn uninstall ```

Update the system first

```
sudo apt-get update
sudo apt-get upgrade
```

then try rerun pivpn!!

**Comment by greenones** [comment] 2017-10-20 16:18
Thanks for the response :)

I've ran the update and upgrade but still getting the same issue:

: error fetching interface information: Device not found
: error fetching interface information: Device not found

Thanks for supporting this! Looking forward to the fix 👍

**Comment by andrelanger** [comment] 2017-10-23 07:38
I have exactly the same issue.

I ran the install script 

`curl -L https://install.pivpn.io | bash

and was able to select the static IP address and gateway address, then got a FYI: IP Conflict information window and then suddenly exit the setup back to the shell.

I tried to install pivpn on a Raspberry 2 Model B with Raspbian GNU/Linux 8 (jessie) v4.9.57 v7 and a German localization. Enough SD card space is provided. Attempted it with sudo in a zsh and as root in a bash. No error entries in syslog or something like that

**Comment by cfcolaco** [comment] 2017-10-26 21:34
I am sorry guys ... not having much time as I have expected ... but will soon do some testing and see if I can replicate this ...

**Comment by cfcolaco** [comment] 2017-10-30 20:31
Ok  ... tested it myself ... and I experienced ZERO errors with the config.

seems that the raspbian folks want to hide the old images, so  had to dig around to find the old raspbian images  and here they are: http://downloads.raspberrypi.org/raspbian/images/

seems I cant reproduce the error! 
Important to mention that I am at an hotel so I am quite limited and more prone to errors, but they didn't happened. 

So I took the steps that a regular, user with little knowledge would take!! 

Steps I have taken:
1- downloaded the latest jessie image from the website i mentioned earlier. 
2 - burned the image into the sdcard and booted jessie
3 - ran pivpn script ... over WLAN and it went quite smooth!! No errors at all and is all running!! 

So mates What I will recommend you, is to Re image your pis with Stretch and follow from there ... I will stop to provide support to jessie for new installs! there are too much issues around here and so litle time, so better start focusing on things that really need to be solved! 

I am sorry guys .. hope you can understand my position here! @0-kaladin @redfast00 hope you can agree with me on this! 

If any of you can provide me the exact steps to replicate this issue, please post it here, and I will be glad to re open the issue and fix whatever needs to be fixed. until there... is just something you did wrong on your systems! It mitght be a missing package that it is failing to get from updates,  it may be missing file, may be a messed up config in /etc/ ... it can be a gazilion of thigs ... so I need the exact steps to replicate this! ... the regular install .. works just fine!

**Comment by tlim01** [comment] 2018-01-22 08:11
I had this issue, but it turns out it was my mistake. I didn't select an inteface(eth0). I had pressed <Enter> on eth0. This did not select it. I had to hit <Space> then <Enter>. The * had to appear next to my selected interface.

**Comment by cfcolaco** [comment] 2018-01-22 22:57
@tlim01 Working on a fix for that in the next few weeks it might land on the test branch! Ty for your feedback!

**Comment by ms158** [comment] 2018-02-13 17:16
Thats an issue of language. If your system speaks German the grep and awk in setNetwork doesn't work. i.E. Mask is Maske in german and addr is Adresse. So just dpkg-reconfigure locales to english and it should work.
Perhaps future versions of that script should verify the language or do a export LANG=en (LANGUAGE, LC_ALL?)

**Comment by josephchrzempiec** [comment] 2018-05-26 23:45
I also had this same problem Where it stopped on me. What i did was installed the latest Raspberry pi RASPBIAN STRETCH WITH DESKTOP.

At this time i post it the Version is

Version:April 2018
Release date:2018-04-18
Kernel version:4.14


After i installed that i did not update or upgrade it. I did hooked up a monitor with a keyboard and mouse then i went into the config  to enable SSH and VNC because i use VNC a lot. After that i went into the config once more and Expand the file storage to use all the the SD card. I;m using a 16GB ssd class 10 card for the speed. 

Then i rebooted came back in remotely into putty and i installed pipvn using the command Sudo curl -L https://install.pivpn.io | bash

I'm not a programmer so forgive me on that. I'm learning as i go along. Once i did all of that i was able to get to the setup blue screen of the Pipvn and put in my settings Now I'm able to do VPN. Hopefully this will help Someone.

**Comment by bcrhiaadn** [comment] 2018-10-16 14:55
sudo apt-get autoremove --purge while i'm waiting for the image to write to the other SD card. No luck

**Comment by 4s3ti** [comment] 2019-10-19 10:37
closing this as this seems to be resolved with the latest changes. 
if this still a thing let us know.

**Closed by 4s3ti** 2019-10-19 10:37 UTC
Labels: Priority, bug
