### ISSUE TITLE
packages

### ISSUE THREAD

**Issue by sappsys** [pivpn/pivpn#335] opened 2017-08-14 14:46 UTC
I installed a brand new minimal Raspbian to my Pi, did all required updates and upgrades to get it fully up to date. I then ran the install script... This is where issues begin... The installer seems to have made some assumptions, like me having git installed and iptables-persistant and nslookup oh and OpenVPN!
Would it not be a good idea to have the installer try and install any package it thinks it might depend on ?
I ended up running the install script about 5 times but I did finally end up with a working system (though had to do my own iptables-save).

**Comment by redfast00** [comment] 2017-08-14 15:48
It should normally install the packages it needs (see source code). If it failed, do you still have the logs of the failed installs? We can't really do much without them.

**Comment by sappsys** [comment] 2017-08-14 22:14
I don't still have the logs unfortunately, I remember the screen saying all packages were up to date but then it couldn't find git. And similar for the openvpn directory & nslookup

**Comment by redfast00** [comment] 2017-08-15 07:50
Since you don't have the logs and I haven't been able to reproduce this, I am closing this issue.

**Closed by redfast00** 2017-08-15 07:50 UTC

**Comment by InnovativeInventor** [comment] 2017-08-16 12:26
sappsys, try to reproduce this and give us the logs. I have never experienced this before and it looks like redfast00 couldn't reproduce it either. There shouldn't be anything wrong because you are using a brand new install of Raspbian

**Comment by sappsys** [comment] 2017-08-16 12:47
I have a brand new Pi arriving tomorrow so I'll build that from scratch with the same starting image and see what happens.

**Comment by sappsys** [comment] 2017-08-18 09:57
Everything built fine this time around - must have been some glitch.
