### ISSUE TITLE
PiVPN install fails -- gzip: stdin: unexpected end of file

### ISSUE THREAD

**Issue by CapnDoody** [pivpn/pivpn#674] opened 2019-01-27 19:54 UTC
# PiVPN Issue Template

## Issue
After installation, the pivpn command does not exist. The folder /etc/.pivpn has some files in it, including the pivpn file, but does not execute when run:
pi@raspberrypi:~ $ pivpn
-bash: pivpn: command not found

## Have you searched for similar issues and solutions? 
    Similar to issues 215 and 153 but their resolutions did not help
  

## Console output of `curl -L install.pivpn.io | bash`
```
pi@raspberrypi:~ $ curl -L https://install.pivpn.io | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   178  100   178    0     0    387      0 --:--:-- --:--:-- --:--:--   387
100 53084  100 53084    0     0  74077      0 --:--:-- --:--:-- --:--:-- 74077
:::
::: sudo will be used for the install.
::: Verifying free disk space...
:::
::: Checking apt-get for upgraded packages.... done!
:::
::: Your system is up to date! Continuing with PiVPN installation...
::: Static IP already configured.
::: Using User: pi
:::
::: Checking for existing base files...
:::    Checking /etc/.pivpn is a repo...:::    Cloning https://github.com/pivpn/pivpn.git into /etc/.pivpn... done!
:::
::: Stopping OpenVPN service... done.
      
gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
::: Install Complete...
::: Restarting services...
::: done.
:::
::: Installation Complete!
::: Now run 'pivpn add' to create an ovpn profile for each of your devices.
::: Run 'pivpn help' to see what else you can do!
::: It is strongly recommended you reboot after installation.
:::
::: The install log is located at: /etc/pivpn/install.log
pi@raspberrypi:~ $ ```

## Have you taken any steps towards solving your issue? 
Remove folders /etc/.pivpn and try to reinstall 

I previously had openvpn installed but never got it working. I wasn't sure if this might have been causing issues with the PiVPN install, so I removed OpenVPN with apt-get remove, and also deleted the services from /etc/systemd as well as /etc/init.d/ -- after removing all of this I did a reboot and attempted reinstall, and got same results.

**Comment by CaptBV** [comment] 2019-02-20 21:33
Hi @CapnDoody, 
You can change rule 888 of https://install.pivpn.io (which is https://raw.githubusercontent.com/pivpn/pivpn/master/auto_install/install.sh) 

from:
wget -q -O - "$UNATTUPG_CONFIG" | $SUDO tar xz
to:
wget -qO- "$UNATTUPG_CONFIG" | $SUDO tar xzf -


I ran into much the same issue as you did. 
Btw, there are some more wget statements that need editing. 

Cheers, 
CaptnBV

**Comment by devZer0** [comment] 2019-03-18 23:38
what's the difference between "tar xz" and tar "xzf -" ?  that is the same for me

**Comment by PGallagher69** [comment] 2019-04-10 15:34
I found this problem to be an incorrect path to the Easy RSA Github Repo, and then to the subsequent move command... Change the following lines... Line 33;

`easyrsaRel="https://github.com/OpenVPN/easy-rsa/releases/download/v${easyrsaVer}/EasyRSA-${easyrsaVer}.tgz"
`
to

`easyrsaRel="https://github.com/OpenVPN/easy-rsa/releases/download/v${easyrsaVer}/EasyRSA-unix-v${easyrsaVer}.tgz"`

And then on line 762 - Change;

`wget -q -O - "${easyrsaRel}" | $SUDO tar xz -C /etc/openvpn && $SUDO mv /etc/openvpn/EasyRSA-${easyrsaVer} /etc/openvpn/easy-rsa`

to

`wget -qO- "${easyrsaRel}" | $SUDO tar xzf - -C /etc/openvpn && $SUDO mv /etc/openvpn/EasyRSA-v${easyrsaVer} /etc/openvpn/easy-rsa`

**Comment by InnovativeInventor** [comment] 2019-04-10 22:02
I have been able to reproduce this issue. Is there a fix planned?

**Comment by remy561** [comment] 2019-04-10 22:43
Had the same issue, your fix allowed pivpn to install successfully. Thanks!

**Comment by Giraffe1966** [comment] 2019-04-11 22:43
The easy-rsa problem has been fixed (#716)

**Comment by BDGreyson** [comment] 2019-05-09 18:29
Just encountered the same problem trying to install on a Pi with Pihole, exact same situation and error.

Replacing the lines did, sadly, not help, causing the same thing to happen again. I'm really hoping there is a fix possible and it's not a matter of my system.

**Comment by 4s3ti** [comment] 2019-05-26 13:35
Closing this issue, as it seems to be resolved, @BDGreyson if you are still encountering this error, please give it a shot, make a new fresh install. 

If it still happens, please reopen a new issue with all the required information. 

Kind Regards.

**Closed by 4s3ti** 2019-05-26 13:35 UTC

**Comment by Paulf007** [comment] 2019-10-28 06:20
Not sure if I am missing something  but I have attempted to run the Script on Jessie, Strech and Buster and I am getting the same error :

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
chown: cannot access '/etc/openvpn/easy-rsa': No such file or directory
mkdir: cannot create directory ‘/etc/openvpn/easy-rsa/pki’: No such file or directory
main: line 825: cd: /etc/openvpn/easy-rsa: No such file or directory

Should I run the Script as Sudo or is there something else I need to do before I run the Script?
Regards
Paul

**Comment by ctianm** [comment] 2019-12-28 10:07
Yes me too I have same problem with Paul
