### ISSUE TITLE
[Support] No QR Code option

### ISSUE THREAD

**Issue by casmokey** [pivpn/pivpn#1122] opened 2020-08-23 17:32 UTC
## In raising this issue, I confirm the following: 

`{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting can be *is* directly related to the pivpn installer script.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pivpn/pivpn/wiki/FAQ), [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed), and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen)).

I do not have the option of using a -qr code to install a Wireguard profile

`pi@raspberrypi:~$ pivpn
::: Control all PiVPN specific functions!
:::
::: Usage: pivpn <command> [option]
:::
::: Commands:
:::  -a, add [nopass]     Create a client ovpn profile, optional nopass
:::  -c, clients          List any connected clients to the server
:::  -d, debug            Start a debugging session if having trouble
:::  -l, list             List all valid and revoked certificates
:::  -r, revoke           Revoke a client ovpn profile
:::  -h, help             Show this help dialog
:::  -u, uninstall        Uninstall PiVPN from your system!
:::  -up, update          Updates PiVPN Scripts
:::  -bk, backup          Backup Openvpn and ovpns dir`

**Comment by orazioedoardo** [comment] 2020-08-23 20:29
If you read the text you can see that you have installed OpenVPN, for which there is not qrcode option.

**Comment by casmokey** [comment] 2020-08-23 20:47
I don't get the option to pick between WG or OVPN. It thinks I am not running Raspbian even though I am.

**Comment by orazioedoardo** [comment] 2020-08-23 21:04
Output of `pivpn -d`?

**Comment by casmokey** [comment] 2020-08-23 21:36
[pivpn-debug.txt](https://github.com/pivpn/pivpn/files/5115065/pivpn-debug.txt)

**Comment by orazioedoardo** [comment] 2020-08-24 06:10
Most likely a duplicate of https://github.com/pivpn/pivpn/issues/1117

**Comment by casmokey** [comment] 2020-08-24 08:16
Is there any way to fix this issue?

**Comment by orazioedoardo** [comment] 2020-08-24 08:19
Either install and configure WireGuard by yourself or flash the 32-bit version of Raspberry Pi OS and install PiVPN.

**Comment by orazioedoardo** [comment] 2020-09-06 12:39
Closing as duplicate.

**Closed by orazioedoardo** 2020-09-06 12:39 UTC
