### ISSUE TITLE
Installed fails to install missing apts (Ubuntu)

### ISSUE THREAD

**Issue by AlexHockaday** [pivpn/pivpn#1198] opened 2020-12-10 00:21 UTC
## In raising this issue, I confirm the following: 

`{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md).
- [?] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting can be *is* directly related to the pivpn installer script.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pivpn/pivpn/wiki/FAQ), [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed), and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen)).

Install script fails to install net-tools

net-tools and iptables-persistent are the only missing components, when the script attempts to install them this error appears:

`usr/bin/debconf-apt-progress: can't open /tmp/tmp.sahRKY9SRm: Permission denied at /usr/bin/debconf-apt-progress line 249, <STDIN> line 3.                             
:::    Failed to install net-tools!
:::    Failed to install iptables-persistent!
`

**To Reproduce**
1. install pi-hole
2. run pi-vpn install script

**Expected behavior**
Install completing sucessfully

**~~Desktop~~ Server (please complete the following information):**
 - VPN Protocol none yet installed
 - OS: [e.g. iOS] Ubuntu Server 20.04

**Comment by orazioedoardo** [comment] 2020-12-10 09:58
Try the test branch: https://github.com/pivpn/pivpn/wiki#testing

**Comment by shelleycat485** [comment] 2020-12-11 21:26
I saw this too, a workaround on AWS ubuntu new images is 
sudo apt-get update
sudo apt-get upgrade
before doing the install.  I don't know why it makes a difference.

**Comment by AlexHockaday** [comment] 2020-12-12 03:34
I was able to work around this by canceling (ctrl-c) the script, manually installing the packages listed, then running the script again.

**Comment by orazioedoardo** [comment] 2020-12-12 11:23
The error is `::: Failed to install net-tools! ::: Failed to install iptables-persistent!` but you can't see the reason because `debconf-apt-progress` can't write the log file which the script would show to the user. Since you can't reproduce, i'll close the issue.

**Closed by orazioedoardo** 2020-12-12 11:23 UTC
Labels: Needs Investigation
