### ISSUE TITLE
Cannot add a client

### ISSUE THREAD

**Issue by duramato** [pivpn/pivpn#521] opened 2018-04-17 13:28 UTC
# PiVPN Issue Template

When trying to add a new client, it fails. (see console output below)

## Have you searched for similar issues and solutions? 
    Yes 
  

## Console output of `pivpn add` or `pivpn add nopass`
```
$ sudo pivpn add
cat: /etc/pivpn/INSTALL_USER: No such file or directory
Enter a Name for the Client:  tes
Enter the password for the client:
Enter the password again to verify:
spawn ./easyrsa build-client-full tes
couldn't execute "./easyrsa": permission denied
    while executing
"spawn ./easyrsa build-client-full "tes""
spawn openssl rsa -in pki/private/tes.key -des3 -out pki/private/tes.key
Error opening Private Key pki/private/tes.key
1996073056:error:02001002:system library:fopen:No such file or directory:bss_file.c:398:fopen('pki/private/tes.key','r')
1996073056:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:400:
unable to load Private Key
expect: spawn id exp6 not open
    while executing
"expect "Enter PEM pass phrase" { send "Password\r" }"
[ERROR]: Client Public Key Certificate not found: tes.crt
```

## Console output of `pivpn debug`
```
$ pivpn debug
cat: /etc/pivpn/NO_UFW: No such file or directory
::: Generating Debug Output
:::                                     :::
::              PiVPN Debug              ::
:::                                     :::
::      Latest Commit                    ::
:::                                     :::
commit 33ed7e7012d5278162d72c3477a0d9b4345520ab
Merge: 1375fa1 30397f2
Author: redfast00 <redfast00@users.noreply.github.com>
Date:   Sat Mar 24 13:39:55 2018 +0100

    Merge pull request #502 from stan3/nonexecutable

    Changed permission bits on text files.
:::                                     :::
::      Recursive list of files in       ::
::      /etc/openvpn/easy-rsa/pki        ::
:::                                     :::
/etc/openvpn/easy-rsa/pki/:
ca.crt
dh.pem
index.txt
index.txt.attr
index.txt.attr.old
index.txt.old
issued
private
serial
serial.old
ta.key

/etc/openvpn/easy-rsa/pki/issued:
cli.crt
nes.crt
nexus5.crt
server.crt

/etc/openvpn/easy-rsa/pki/private:
ca.key
cli.3des.key
cli.key
default.txt
nes.3des.key
nes.key
nexus5.3des.key
nexus5.key
server.key
:::                                     :::
::      Output of /etc/pivpn/*           ::
:::                                     :::
:: START /etc/pivpn/INSTALL_PORT ::
1194
:: END /etc/pivpn/INSTALL_PORT ::
:: START /etc/pivpn/INSTALL_PROTO ::
udp
:: END /etc/pivpn/INSTALL_PROTO ::
:: START /etc/pivpn/pivpnINTERFACE ::
eth0
:: END /etc/pivpn/pivpnINTERFACE ::
:::                                     :::
:: /etc/openvpn/easy-rsa/pki/Default.txt ::
:::                                     :::
cat: /etc/openvpn/easy-rsa/pki/Default.txt: No such file or directory
:::                                     :::
::      Debug Output Complete            ::
:::                                     :::
:::
::: Debug output completed above.
::: Copy saved to /tmp/debug.txt
:::

```

## Console Output of `sudo iptables -t nat -S`
```
 $ sudo iptables -t nat -S
-P PREROUTING ACCEPT
-P INPUT ACCEPT
-P OUTPUT ACCEPT
-P POSTROUTING ACCEPT
-A POSTROUTING -s 10.8.0.0/24 -o eth0 -j SNAT --to-source 192.168.1.4
-A POSTROUTING -s 10.8.0.0/24 -o eth0 -j SNAT --to-source 192.168.1.4
```

## Console Output of `sudo iptables -S`
```
$ sudo iptables -S
-P INPUT ACCEPT
-P FORWARD ACCEPT
-P OUTPUT ACCEPT

```

## output of `sudo netstat -uanp | grep openvpn`

```
None
```

## Have you taken any steps towards solving your issue? 
 None

**Comment by NyxCode** [comment] 2018-04-24 08:51
Doesn't work for me either. 
```
root@raspberrypi:~# pivpn add
cat: /etc/pivpn/INSTALL_USER: No such file or directory
Enter a Name for the Client:  Main
/opt/pivpn/makeOVPN.sh: line 165: /etc/openvpn/easy-rsa/pki/index.txt: No such file or directory
/opt/pivpn/makeOVPN.sh: line 179: cd: /etc/openvpn/easy-rsa: No such file or directory
```

**Comment by kmpdigital** [comment] 2018-05-16 10:27
I am seeing the same thing. I had to reinstall due to selecting the wrong interface.  I attempted to uninstall and reinstall and no luck 

```
pi@raspberrypi:/opt/pivpn $ sudo pivpn add
cat: /etc/pivpn/INSTALL_USER: No such file or directory
Enter a Name for the Client:  User
/opt/pivpn/makeOVPN.sh: line 165: /etc/openvpn/easy-rsa/pki/index.txt: No such file or directory
/opt/pivpn/makeOVPN.sh: line 179: cd: /etc/openvpn/easy-rsa: No such file or directory
```

**Comment by justincdotme** [comment] 2018-05-18 13:06
I am having the same issue. I get the following output when I run `pivpn add`

`pi@vpn-1:/etc/openvpn $ sudo pivpn add
cat: /etc/pivpn/INSTALL_USER: No such file or directory
Enter a Name for the Client:  User
/opt/pivpn/makeOVPN.sh: line 165: /etc/openvpn/easy-rsa/pki/index.txt: No such file or directory
/opt/pivpn/makeOVPN.sh: line 179: cd: /etc/openvpn/easy-rsa: No such file or directory`

I've tried uninstalling pivpn, reinstalling it as root but that made no difference. I also tried manually installing the easy-rsa package using apt-get but that didn't seem to make a difference either. I noticed that /etc/openvpn doesn't contain an easy-rsa dir after installing pivpn.

**Comment by kmpdigital** [comment] 2018-05-18 13:12
I had a backup SD so I spun up a new image of raspbian and it worked just fine. What I noticed the same thing that there was no easy-rsa folder as well. Another thing I noticed was when I ran the setup for the second(3rd 4th etc) time that I was not asked to generate a key 1024/2048.

I h

**Comment by justincdotme** [comment] 2018-05-19 12:51
Same here, I saw your post and installed a fresh Raspbian Stretch image. This time PiVPN installed fine. Previously, the first attempt at installing PiVPN failed immediately. All subsequent attempts to install PiVPN failed with the message about the missing easy-rsa dir and the UI never presented the key generation prompt. Glad its working now, I'll post installer logs and all that if I can reproduce it in the future.

**Comment by wstafford3** [comment] 2018-06-19 15:20
I am getting the same message:
$ pivpn -a
cat: /etc/pivpn/INSTALL_USER: No such file or directory
Enter a Name for the Client:  pi
/opt/pivpn/makeOVPN.sh: line 165: /etc/openvpn/easy-rsa/pki/index.txt: No such file or directory
/opt/pivpn/makeOVPN.sh: line 179: cd: /etc/openvpn/easy-rsa: No such file or directory


Has a solution to this been found yet??

**Comment by eugeneniemand** [comment] 2018-06-26 16:01
same here...
```
 pivpn add
cat: /etc/pivpn/INSTALL_USER: No such file or directory
Enter a Name for the Client:  iphone
/opt/pivpn/makeOVPN.sh: line 165: /etc/openvpn/easy-rsa/pki/index.txt: No such file or directory
/opt/pivpn/makeOVPN.sh: line 179: cd: /etc/openvpn/easy-rsa: No such file or directory
```

**Comment by orazioedoardo** [comment] 2018-07-12 07:07
Can you all run `cat /etc/os-release` and `uname -a` on your raspberry? Assuming you STILL have a broken installation, not a new working one.

**Comment by EnricoSx** [comment] 2018-07-12 19:35
solved for me
```
apt update; apt upgrade -y; reboot
sudo curl -L https://install.pivpn.io | bash
```
thanks for your hard work!

**Comment by nicocti** [comment] 2018-07-28 21:39
Same issue for me on a fresh new raspbian install.
Actually, the install process didn't even created the key nor asked me for the port to be used.
Logs from the install:

```
nicocti@MARAT:~ $ cat /etc/pivpn/install.log 
:::
::: Stopping OpenVPN service... done.
:::   
::: Installing scripts to /opt/pivpn...
```

**Comment by nicocti** [comment] 2018-07-28 23:36
Fixed after complete raspbian re-install using the same image. Must have missed sth.

**Comment by AdvancedFollower** [comment] 2018-09-13 09:33
Same issue here. Would prefer not to do a clean install if possible.
If I manually create the INSTALL_USER file and write my username inside it, this part of the script works. However it fails later because it can't find Default.txt (it actually creates the ovpn file but there's no configuration info in it, just the keys). I don't get the error about easy-rsa however.

Also when actually installing PiVPN, I never get presented with the option to select public IP or DNS, port etc. The install exits before this (which is probably why the config files are missing in the first place).

**Comment by AdvancedFollower** [comment] 2018-09-13 11:07
@orazioedoardo I downloaded the install.sh file in order to test with those lines added, but when I executed the file locally, it actually worked this time. No errors at all and I can add clients and connect from them.

**Comment by orazioedoardo** [comment] 2018-09-13 11:29
Nooooo, missed opportunity.

**Comment by AdvancedFollower** [comment] 2018-09-13 11:32
Maybe the error was related to trying to run the script remotely (curl -L https://install.pivpn.io | bash)?  I had already tried that at least 4-5 times and never got it to work. But as soon as I downloaded the script locally, added the two lines (don't know whether that makes a difference), set chmod +x and executed it locally, it worked on the first try. Coincidence perhaps, but a bit weird.

**Comment by orazioedoardo** [comment] 2018-09-13 11:53
Mmmh, can you answer these questions, if you don't mind?
1) What's your system language?
2) What's your username?
3) Can you use sudo with your username or you have to do `su root` to get root?
3) Did you run `curl -L https://install.pivpn.io | bash` as root or standard user?
4) Did you download and run the script manually as root or standard user with sudo?

**Comment by AdvancedFollower** [comment] 2018-09-14 09:04
1. #  File generated by update-locale
LANG=en_GB.UTF-8
LC_CTYPE=en_GB.UTF-8
LC_TIME=en_GB.UTF-8
LC_ALL=en_GB.UTF-8

2. Same as my first name

3. Sudo works fine

4. As my standard user (with sudo permission), also tried running it from Dietpi-Software with same result

5.  Standard user witrh Sudo

**Comment by manuBocquet** [comment] 2018-09-27 00:02
I found a problem in the install script.

This is the patch  :

*** install.orig	2018-09-26 23:58:02.462777785 +0000
--- install.fixed	2018-09-26 23:59:30.472539916 +0000
***************
*** 892,898 ****
          echo 1 > /tmp/noUFW
          $SUDO iptables -t nat -A POSTROUTING -s 10.8.0.0/24 -o "$IPv4dev" -j MASQUERADE
          case ${PLAT} in
!             Ubuntu|Debian|Devuan)
                  $SUDO iptables-save | $SUDO tee /etc/iptables/rules.v4 > /dev/null
                  ;;
              *)
--- 892,898 ----
          echo 1 > /tmp/noUFW
          $SUDO iptables -t nat -A POSTROUTING -s 10.8.0.0/24 -o "$IPv4dev" -j MASQUERADE
          case ${PLAT} in
!             Ubuntu|Debian|Devuan|Raspbian)
                  $SUDO iptables-save | $SUDO tee /etc/iptables/rules.v4 > /dev/null
                  ;;
              *)


you can use patch command to fix the script.

**Comment by 4s3ti** [comment] 2019-04-29 13:19
This seems to be resolved. 
Let me know if i am closing this by mistake, 
Seems not to be a a bug per se ... try to take this discussions at pivpn subreddit, and if needed an issue will be opened here. 

https://www.reddit.com/r/pivpn/

**Closed by 4s3ti** 2019-04-29 13:19 UTC

**Comment by Valenwe** [comment] 2022-08-24 15:33
Bug's still up, even after a clean uninstall, reinstall...
