### ISSUE TITLE
Can't access internet after install.

### ISSUE THREAD

**Issue by montainz09** [pivpn/pivpn#156] opened 2016-11-19 18:59 UTC
After I installed pivpn on a Pi B+ running the latest raspian lite using the script, I now can't access the internet in order to update or upgrade the pi. The pi is using a usb wifi adapter. During the install process I chose wlan0 for the vpn as there was not an ethernet connection despite the option to use eth0. The pi is still accessible over lan, and I can connect to the vpn server from other networks, but when I try to update the pi using `sudo apt-get update` to receive a `Failed to fetch` error. This error was repeated when I reinstalled from a fresh raspbian install. Both times the I was able to update/upgrade before the install, just not after.

**Comment by 0-kaladin** [comment] 2016-11-19 19:48
Check the IP in /etc/resolv.conf
it is probably using your gateway (router), if you want, change to 8.8.8.8 or something.
this is still something I need to investigate.

**Comment by 0-kaladin** [comment] 2016-11-19 19:52
Duplicate of Issue #80

**Closed by 0-kaladin** 2016-11-19 19:52 UTC
Labels: duplicate
