### ISSUE TITLE
Raspberrypi zero - pivpn install bash fails

### ISSUE THREAD

**Issue by mhano** [pivpn/pivpn#1261] opened 2021-02-24 08:01 UTC
Pi vpn install fails if raspberrypi is upgraded prior to install 

Error relates to the packages : expect, tcl-expect, tcl8.6

“tcl8.6” isn’t available and so pivpn install script fails...

downgrading back to os straight off the sd card, installing Pi-vpn then upgrading was my work-around.

**Comment by 4s3ti** [comment] 2021-03-01 19:40
i'd say we would have more complaints and more failures if this was rly a bug! closing due to lack of details! thanks for taking time with it @shelleycat485 ... @mhano if you feel this was wrongly closed please feel free to re-open and provide extra details, how can this be reproduced, which version of raspbian are you using, where did you download it from, exactly what did you do before this happening ....

**Closed by 4s3ti** 2021-03-01 19:40 UTC
Labels: Needs Investigation

**Comment by mhano** [comment] 2021-03-02 00:26
Thanks for having a look guys.

Appears you are correct, i believe the pivpn issue I had was related to a corrupted install... which may be a hardware failure as rare as they are reported to be..

I’ve done a stack of additional testing, my next step is to buy another raspberrypi zero w board (hopefully I don’t end up with one with the same issue / from the same batch)...

https://github.com/raspberrypi/linux/issues/4178

Apologies for the red herring and thanks again.
