### ISSUE TITLE
Install script fails to build the CA certificates

### ISSUE THREAD

**Issue by LordEvron** [pivpn/pivpn#1507] opened 2022-04-23 11:35 UTC
## In raising this issue, I confirm the following: 

`{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md).
- [] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting *is* directly related to the pivpn installer script.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pivpn/pivpn/wiki/FAQ), [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed), and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen)).

**Describe the bug**
It seems that the installer script fails to build a CA authority. 

**To Reproduce**
Just run the install script on ubuntu server 22.04 64bit
 curl -L https://install.pivpn.io | bash 

**Expected behavior**
when selected OpenVPN--> pivpn list, there are no entries.. while there should be the one of the server...

**Screenshots**
This is a screenshot of the error i get during the installation phase... 

![image](https://user-images.githubusercontent.com/19925068/164892547-e8442b98-2ffb-402e-9fcf-bbc80f011dea.png)

**Setup (please complete the following information):**
 - VPN Protocol .. >OPENVPN TCP version
 - OS: [e.g. iOS] --> UBUNTU Server 22.04 64bit
 - Version [e.g. 22]  22.04 Jelly 
 - Device:  RPI 4 

**Additional context**
This is a screenshot if i try to add a new connection    eg pivpn add 

![image](https://user-images.githubusercontent.com/19925068/164892724-9e63e81d-8977-42d9-8ee6-93e2a113e363.png)
 

and this is the output of pivpn list 

![image](https://user-images.githubusercontent.com/19925068/164892765-27f6efce-527b-438e-b1c4-1677050d571c.png)

**Comment by orazioedoardo** [comment] 2022-04-24 08:03
Please avoid posting screenshots of text, post the actual text.

Anyways it fails because openssl is asking for a password to encrypt the CA keys, even though we set [nopass](https://github.com/pivpn/pivpn/blob/f80b0a7962d91862132c0a4abd65c1e67bd37bd7/auto_install/install.sh#L1880) as easy-rsa argument.

> Just run the install script on ubuntu server 22.04 64bit

I will try to reproduce this later.

**Comment by TinCanTech** [comment] 2022-04-24 11:49
I'll help, if I can.

**Comment by LordEvron** [comment] 2022-04-24 13:35
yes, i can confirm that is the "./easy-rsa command that ignores the nopass argument...

**Comment by OOLEHLEH** [comment] 2022-05-02 15:49
getting the same error with and without the nopass option, Im also using the same distro and pi

**Comment by orazioedoardo** [comment] 2022-05-03 15:30
Should be fixed now with https://github.com/pivpn/pivpn/commit/a5e41c466fd9539dcbfaaee4ca13853fca87e107. Can you try installing from [test](https://docs.pivpn.io/install/#to-install-from-testdevelopment-branch)?

@TinCanTech I'm getting this error when generating the server certificate on ubuntu 22.04. No subsequent errors with easy-rsa later. Can we just ignore it?

```
configuration file routines:NCONF_get_string:no value:../crypto/conf/conf_lib.c:315:group=<NULL> name=unique_subject
```

**Comment by TinCanTech** [comment] 2022-05-03 16:09
@orazioedoardo Currently, EasyRSA 3.0.8 does not officially support OpenSSL 3.x, because of this and other small out-standing bugs in OpenSSL.

To fix the problem, download `easyrsa git/master`

**Comment by orazioedoardo** [comment] 2022-05-03 16:18
> To fix the problem, download `easyrsa git/master`

That’s what I did in the commit. Now works but the error message above (from openssl I guess) is printed.

**Comment by TinCanTech** [comment] 2022-05-03 16:23
I'll take a closer look.

**Comment by TinCanTech** [comment] 2022-05-03 17:05
I cannot reproduce. Ubuntu 22.04, OpenSSL 3.0.2, full unit test passed and manually building a CA with `nopass` completed ok.

**Comment by TinCanTech** [comment] 2022-05-03 17:18
I just tried a pivpn install, it failed:
```
root@ub22:/home/tct# curl -L https://test.pivpn.io | TESTING= bash

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   162  100   162    0     0    502      0 --:--:-- --:--:-- --:--:--   501
100 93721  100 93721    0     0   162k      0 --:--:-- --:--:-- --:--:--  162k
:::
::: You are root.
::: Did not detect perfectly supported OS but,
::: Continuing installation at user's own risk...
main: line 307: /tmp/setupVars.conf: Permission denied
main: line 308: /tmp/setupVars.conf: Permission denied
::: Hostname length OK
::: Verifying free disk space...
:::
::: Package Cache update is needed, running apt-get update -y ...
 done!
:::
::: Checking apt-get for upgraded packages.... done!
:::
::: There are 4 updates available for your system!
::: We recommend you update your OS after installing PiVPN! 
:::
main: line 542: /tmp/setupVars.conf: Permission denied
:::    Checking for git... already installed!
:::    Checking for tar... already installed!
:::    Checking for curl... already installed!
:::    Checking for grep... already installed!
:::    Checking for dnsutils... not installed!
:::    Checking for grepcidr... not installed!
:::    Checking for whiptail... already installed!
:::    Checking for net-tools... not installed!
:::    Checking for bsdmainutils... not installed!
:::    Checking for bash-completion... already installed!
:::    Checking for iptables-persistent... not installed!
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  ncal netfilter-persistent
Suggested packages:
  calendar whois vacation mailutils
The following NEW packages will be installed:
  bsdmainutils dnsutils grepcidr iptables-persistent ncal net-tools netfilter-persistent
0 upgraded, 7 newly installed, 0 to remove and 4 not upgraded.
Need to get 259 kB of archives.
After this operation, 1104 kB of additional disk space will be used.
Get:1 http://gb.archive.ubuntu.com/ubuntu jammy/universe amd64 netfilter-persistent all 1.0.16 [7440 B]
Get:2 http://gb.archive.ubuntu.com/ubuntu jammy/universe amd64 iptables-persistent all 1.0.16 [6488 B]
Get:3 http://gb.archive.ubuntu.com/ubuntu jammy/universe amd64 ncal amd64 12.1.7+nmu3ubuntu2 [20.2 kB]
Get:4 http://gb.archive.ubuntu.com/ubuntu jammy/universe amd64 bsdmainutils all 12.1.7+nmu3ubuntu2 [3170 B]
Get:5 http://gb.archive.ubuntu.com/ubuntu jammy/universe amd64 dnsutils all 1:9.18.1-1ubuntu1 [3918 B]
Get:6 http://gb.archive.ubuntu.com/ubuntu jammy/universe amd64 grepcidr amd64 2.0-2 [13.8 kB]
Get:7 http://gb.archive.ubuntu.com/ubuntu jammy/main amd64 net-tools amd64 1.60+git20181103.0eebece-1ubuntu5 [204 kB]
Fetched 259 kB in 0s (2417 kB/s)
Preconfiguring packages ...
Selecting previously unselected package netfilter-persistent.
(Reading database ... 73190 files and directories currently installed.)
Preparing to unpack .../0-netfilter-persistent_1.0.16_all.deb ...
Unpacking netfilter-persistent (1.0.16) ...
Selecting previously unselected package iptables-persistent.
Preparing to unpack .../1-iptables-persistent_1.0.16_all.deb ...
Unpacking iptables-persistent (1.0.16) ...
Selecting previously unselected package ncal.
Preparing to unpack .../2-ncal_12.1.7+nmu3ubuntu2_amd64.deb ...
Unpacking ncal (12.1.7+nmu3ubuntu2) ...
Selecting previously unselected package bsdmainutils.
Preparing to unpack .../3-bsdmainutils_12.1.7+nmu3ubuntu2_all.deb ...
Unpacking bsdmainutils (12.1.7+nmu3ubuntu2) ...
Selecting previously unselected package dnsutils.
Preparing to unpack .../4-dnsutils_1%3a9.18.1-1ubuntu1_all.deb ...
Unpacking dnsutils (1:9.18.1-1ubuntu1) ...
Selecting previously unselected package grepcidr.
Preparing to unpack .../5-grepcidr_2.0-2_amd64.deb ...
Unpacking grepcidr (2.0-2) ...
Selecting previously unselected package net-tools.
Preparing to unpack .../6-net-tools_1.60+git20181103.0eebece-1ubuntu5_amd64.deb ...
Unpacking net-tools (1.60+git20181103.0eebece-1ubuntu5) ...
Setting up net-tools (1.60+git20181103.0eebece-1ubuntu5) ...
Setting up ncal (12.1.7+nmu3ubuntu2) ...
Setting up dnsutils (1:9.18.1-1ubuntu1) ...
Setting up bsdmainutils (12.1.7+nmu3ubuntu2) ...
Setting up grepcidr (2.0-2) ...
Setting up netfilter-persistent (1.0.16) ...
Created symlink /etc/systemd/system/multi-user.target.wants/netfilter-persistent.service -> /lib/systemd/system/netfilter-persistent.service.
Setting up iptables-persistent (1.0.16) ...
update-alternatives: using /lib/systemd/system/netfilter-persistent.service to provide /lib/systemd/system/iptables.service (iptables.service) in auto mode
Processing triggers for man-db (2.10.2-1) ...
Scanning processes...                                                                                                                                
Scanning linux images...                                                                                                                             

Running kernel seems to be up-to-date.

No services need to be restarted.

No containers need to be restarted.

No user sessions are running outdated binaries.

No VM guests are running outdated hypervisor (qemu) binaries on this host.
:::    Package dnsutils successfully installed!
:::    Package grepcidr successfully installed!
:::    Package net-tools successfully installed!
:::    Package bsdmainutils successfully installed!
:::    Package iptables-persistent successfully installed!
::: IPv6 test connections to google.com have failed. Disabling IPv6 support. (The curl test failed with code: 7)
main: line 812: /tmp/setupVars.conf: Permission denied
main: line 693: /tmp/setupVars.conf: Permission denied
::: Using User: tct
main: line 1084: /tmp/setupVars.conf: Permission denied
main: line 1085: /tmp/setupVars.conf: Permission denied
:::
::: Checking for existing base files...
:::    Checking /usr/local/src/pivpn is a repo... not found!
:::    Cloning https://github.com/pivpn/pivpn.git into /usr/local/src/pivpn ... done!
:::     Checkout branch 'test' from https://github.com/pivpn/pivpn.git in /usr/local/src/pivpn...
:::     'test' branch checkout done!
::: Using VPN: OpenVPN
main: line 1378: /tmp/setupVars.conf: Permission denied
::: Installing OpenVPN from Debian package... 
:::    Checking for openvpn... not installed!
:::    Checking for expect... not installed!
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  libpkcs11-helper1 tcl-expect
Suggested packages:
  tk8.6 resolvconf openvpn-systemd-resolved easy-rsa
The following NEW packages will be installed:
  expect libpkcs11-helper1 openvpn tcl-expect
0 upgraded, 4 newly installed, 0 to remove and 4 not upgraded.
Need to get 904 kB of archives.
After this operation, 2370 kB of additional disk space will be used.
Get:1 http://gb.archive.ubuntu.com/ubuntu jammy/universe amd64 tcl-expect amd64 5.45.4-2build1 [105 kB]
Get:2 http://gb.archive.ubuntu.com/ubuntu jammy/universe amd64 expect amd64 5.45.4-2build1 [137 kB]
Get:3 http://gb.archive.ubuntu.com/ubuntu jammy/main amd64 libpkcs11-helper1 amd64 1.28-1 [50.0 kB]
Get:4 http://gb.archive.ubuntu.com/ubuntu jammy/main amd64 openvpn amd64 2.5.5-1ubuntu3 [611 kB]
Fetched 904 kB in 0s (3534 kB/s)
Preconfiguring packages ...
Selecting previously unselected package tcl-expect:amd64.
(Reading database ... 73283 files and directories currently installed.)
Preparing to unpack .../tcl-expect_5.45.4-2build1_amd64.deb ...
Unpacking tcl-expect:amd64 (5.45.4-2build1) ...
Selecting previously unselected package expect.
Preparing to unpack .../expect_5.45.4-2build1_amd64.deb ...
Unpacking expect (5.45.4-2build1) ...
Selecting previously unselected package libpkcs11-helper1:amd64.
Preparing to unpack .../libpkcs11-helper1_1.28-1_amd64.deb ...
Unpacking libpkcs11-helper1:amd64 (1.28-1) ...
Selecting previously unselected package openvpn.
Preparing to unpack .../openvpn_2.5.5-1ubuntu3_amd64.deb ...
Unpacking openvpn (2.5.5-1ubuntu3) ...
Setting up tcl-expect:amd64 (5.45.4-2build1) ...
Setting up libpkcs11-helper1:amd64 (1.28-1) ...
Setting up openvpn (2.5.5-1ubuntu3) ...
Created symlink /etc/systemd/system/multi-user.target.wants/openvpn.service -> /lib/systemd/system/openvpn.service.
Setting up expect (5.45.4-2build1) ...
Processing triggers for man-db (2.10.2-1) ...
Processing triggers for libc-bin (2.35-0ubuntu3) ...
Scanning processes...                                                                                                                                
Scanning linux images...                                                                                                                             

Running kernel seems to be up-to-date.

No services need to be restarted.

No containers need to be restarted.

No user sessions are running outdated binaries.

No VM guests are running outdated hypervisor (qemu) binaries on this host.
:::    Package openvpn successfully installed!
:::    Package expect successfully installed!
::: Using protocol: udp
main: line 1520: /tmp/setupVars.conf: Permission denied
main: line 1593: /tmp/setupVars.conf: Permission denied
::: Using Quad9 servers.
main: line 1742: /tmp/setupVars.conf: Permission denied
main: line 1743: /tmp/setupVars.conf: Permission denied
main: line 1801: /tmp/setupVars.conf: Permission denied
main: line 1871: /tmp/setupVars.conf: Permission denied
main: line 1874: /tmp/setupVars.conf: Permission denied
::: Backing up the openvpn folder to /etc/openvpn_2022-05-03-171348.tar.gz
stty: 'standard input': Inappropriate ioctl for device

::: Building CA...
Using configuration from /etc/openvpn/easy-rsa/pki/ad55f7d1/temp.b847a002
-----

stty: 'standard input': Inappropriate ioctl for device


::: CA Complete.
* Notice:
Using Easy-RSA configuration from: /etc/openvpn/easy-rsa/pki/vars

* Notice:
Using SSL: openssl OpenSSL 3.0.2 15 Mar 2022 (Library: OpenSSL 3.0.2 15 Mar 2022)

-----
* Notice:

Keypair and certificate request completed. Your files are:
req: /etc/openvpn/easy-rsa/pki/reqs/ub22_efc951e6-822f-45e8-889f-145f8d686dfe.req
key: /etc/openvpn/easy-rsa/pki/private/ub22_efc951e6-822f-45e8-889f-145f8d686dfe.key

Using configuration from /etc/openvpn/easy-rsa/pki/b0796f1a/temp.d7a1ae38
4087C32E757F0000:error:0700006C:configuration file routines:NCONF_get_string:no value:../crypto/conf/conf_lib.c:315:group=<NULL> name=unique_subject
Check that the request matches the signature
Signature ok
The Subject's Distinguished Name is as follows
commonName            :ASN.1 12:'ub22_efc951e6-822f-45e8-889f-145f8d686dfe'
Certificate is to be certified until Apr 30 17:13:51 2032 GMT (3650 days)

Write out database with 1 new entries
Data Base Updated

* Notice:
Certificate created at: /etc/openvpn/easy-rsa/pki/issued/ub22_efc951e6-822f-45e8-889f-145f8d686dfe.crt

stty: 'standard input': Inappropriate ioctl for device

2022-05-03 17:13:51 WARNING: Using --genkey --secret filename is DEPRECATED.  Use --genkey secret filename instead.
* Notice:
Using Easy-RSA configuration from: /etc/openvpn/easy-rsa/pki/vars

* Notice:
Using SSL: openssl OpenSSL 3.0.2 15 Mar 2022 (Library: OpenSSL 3.0.2 15 Mar 2022)

Using configuration from /etc/openvpn/easy-rsa/pki/bbb7356a/temp.b997e57f

* Notice:

An updated CRL has been created.
CRL file: /etc/openvpn/easy-rsa/pki/crl.pem

stty: 'standard input': Inappropriate ioctl for device

Adding system user `openvpn' (UID 113) ...
Adding new group `openvpn' (GID 118) ...
Adding new user `openvpn' (UID 113) with group `openvpn' ...
Creating home directory `/var/lib/openvpn/' ...
main: line 2254: /tmp/setupVars.conf: Permission denied
main: line 1297: /tmp/setupVars.conf: Permission denied
root@ub22:/home/tct# 
```

**Comment by orazioedoardo** [comment] 2022-05-04 06:59
> main: line 307: /tmp/setupVars.conf: Permission denied

How's this possible? It's not happening on my test ubuntu.

> 4087C32E757F0000:error:0700006C:configuration file routines:NCONF_get_string:no value:../crypto/conf/conf_lib.c:315:group=<NULL> name=unique_subject

Same error. Occurs at `./easyrsa build-server-full ubuntu_ce6c4210-fb5e-4b31-bc6b-c62795fe7160 nopass`.

By the way even though I see this error, subsequent client certificate creation, removal work without issue. This error does not appear at all on openssl < 3.

**Comment by TinCanTech** [comment] 2022-05-04 10:02
The error may only effect renewal, which requires `unique_subject = no`.

If the certs are valid then use them.

FTR: The version of EasyRSA used by `pivpn git/master` does **not** support OpenSSL 3.x and will **not** work correctly.

**Comment by orazioedoardo** [comment] 2022-05-04 10:18
> The error may only effect renewal, which requires unique_subject = no.

Ok, doesn't affect PiVPN then, since there is no `pivpn renew` option as of now.

> FTR: The version of EasyRSA used by pivpn git/master does not support OpenSSL 3.x and will not work correctly.

Yes, that's why `pivpn git/test` now uses easy-rsa from commit [8d1be1c](https://github.com/OpenVPN/easy-rsa/tree/8d1be1c9cf2333a8eee63c86191d27b2e5b63e8b), which was latest `easyrsa git/master` commit at the time.

**Comment by TinCanTech** [comment] 2022-05-04 10:41
I retested TEST and got some different errors, although, it seemed to work:
```
root@ub22:/etc/openvpn/easy-rsa# curl -L https://test.pivpn.io | TESTING= bash
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   162  100   162    0     0    554      0 --:--:-- --:--:-- --:--:--   554
100 93721  100 93721    0     0   119k      0 --:--:-- --:--:-- --:--:--  119k
:::
::: You are root.
::: Did not detect perfectly supported OS but,
::: Continuing installation at user's own risk...
::: Hostname length OK
::: Verifying free disk space...
:::
::: Package Cache update is needed, running apt-get update -y ...
 done!
:::
::: Checking apt-get for upgraded packages....sh: 0: getcwd() failed: No such file or directory
sh: 0: getcwd() failed: No such file or directory
sh: 0: getcwd() failed: No such file or directory
sh: 0: getcwd() failed: No such file or directory
 done!
:::
::: There are 4 updates available for your system!
::: We recommend you update your OS after installing PiVPN! 
:::
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
:::    Checking for git... already installed!
:::    Checking for tar... already installed!
:::    Checking for curl... already installed!
:::    Checking for grep... already installed!
:::    Checking for dnsutils... already installed!
:::    Checking for grepcidr... already installed!
:::    Checking for whiptail... already installed!
:::    Checking for net-tools... already installed!
:::    Checking for bsdmainutils... already installed!
:::    Checking for bash-completion... already installed!
:::    Checking for iptables-persistent... already installed!
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
sh: 0: getcwd() failed: No such file or directory
sh: 0: getcwd() failed: No such file or directory
0 upgraded, 0 newly installed, 0 to remove and 4 not upgraded.
sh: 0: getcwd() failed: No such file or directory
sh: 0: getcwd() failed: No such file or directory
::: IPv6 test connections to google.com have failed. Disabling IPv6 support. (The curl test failed with code: 7)
::: Using User: tct
:::
::: Checking for existing base files...
:::    Checking /usr/local/src/pivpn is a repo... not found!
:::    Cloning https://github.com/pivpn/pivpn.git into /usr/local/src/pivpn ...chdir: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
chdir: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
 done!
:::     Checkout branch 'test' from https://github.com/pivpn/pivpn.git in /usr/local/src/pivpn...
:::     'test' branch checkout done!
::: Using VPN: OpenVPN
::: Installing OpenVPN from Debian package... 
:::    Checking for openvpn... already installed!
:::    Checking for expect... already installed!
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
0 upgraded, 0 newly installed, 0 to remove and 4 not upgraded.
::: Using OpenDNS servers.
::: Backing up the openvpn folder to /etc/openvpn_2022-05-04-103342.tar.gz
stty: 'standard input': Inappropriate ioctl for device

::: Building CA...
Using configuration from /etc/openvpn/easy-rsa/pki/29130465/temp.c02f3f43
-----

stty: 'standard input': Inappropriate ioctl for device


::: CA Complete.
* Notice:
Using Easy-RSA configuration from: /etc/openvpn/easy-rsa/pki/vars

* Notice:
Using SSL: openssl OpenSSL 3.0.2 15 Mar 2022 (Library: OpenSSL 3.0.2 15 Mar 2022)

-----
* Notice:

Keypair and certificate request completed. Your files are:
req: /etc/openvpn/easy-rsa/pki/reqs/ub22_3dd703ab-1459-4d1c-9719-176da3bfc58a.req
key: /etc/openvpn/easy-rsa/pki/private/ub22_3dd703ab-1459-4d1c-9719-176da3bfc58a.key

Using configuration from /etc/openvpn/easy-rsa/pki/8bab3c09/temp.6f3d702d
4067DE8D587F0000:error:0700006C:configuration file routines:NCONF_get_string:no value:../crypto/conf/conf_lib.c:315:group=<NULL> name=unique_subject
Check that the request matches the signature
Signature ok
The Subject's Distinguished Name is as follows
commonName            :ASN.1 12:'ub22_3dd703ab-1459-4d1c-9719-176da3bfc58a'
Certificate is to be certified until May  1 10:33:45 2032 GMT (3650 days)

Write out database with 1 new entries
Data Base Updated

* Notice:
Certificate created at: /etc/openvpn/easy-rsa/pki/issued/ub22_3dd703ab-1459-4d1c-9719-176da3bfc58a.crt

stty: 'standard input': Inappropriate ioctl for device

2022-05-04 10:33:45 WARNING: Using --genkey --secret filename is DEPRECATED.  Use --genkey secret filename instead.
* Notice:
Using Easy-RSA configuration from: /etc/openvpn/easy-rsa/pki/vars

* Notice:
Using SSL: openssl OpenSSL 3.0.2 15 Mar 2022 (Library: OpenSSL 3.0.2 15 Mar 2022)

Using configuration from /etc/openvpn/easy-rsa/pki/6cdc9ab8/temp.897aff18

* Notice:

An updated CRL has been created.
CRL file: /etc/openvpn/easy-rsa/pki/crl.pem

stty: 'standard input': Inappropriate ioctl for device

openvpn:x:113:118::/var/lib/openvpn/:/usr/sbin/nologin
::: Install Complete...
::: Restarting services...
::: Setupfiles copied to /etc/pivpn/openvpn/setupVars.conf
::: Installing scripts to /opt/pivpn...
 done.
::: Flushing writes to disk...
::: done.
:::
```
Followed by:
```
root@ub22:/etc/openvpn/easy-rsa# ls -l
total 0
root@ub22:/etc/openvpn/easy-rsa# pivpn -a
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
::: Create a client ovpn profile, optional nopass
:::
::: Usage: pivpn <-a|add> [-n|--name <arg>] [-p|--password <arg>]|[nopass] [-d|--days <number>] [-b|--bitwarden] [-i|--iOS] [-o|--ovpn] [-h|--help]
:::
::: Commands:
:::  [none]               Interactive mode
:::  nopass               Create a client without a password
:::  -n,--name            Name for the Client (default: "ub22")
:::  -p,--password        Password for the Client (no default)
:::  -d,--days            Expire the certificate after specified number of days (default: 1080)
:::  -b,--bitwarden       Create and save a client through Bitwarden
:::  -i,--iOS             Generate a certificate that leverages iOS keychain
:::  -o,--ovpn            Regenerate a .ovpn config file for an existing client
:::  -h,--help            Show this help dialog

Enter a Name for the Client:  ^C
```
And:
```
root@ub22:/etc/openvpn/easy-rsa# cd ..
root@ub22:/etc/openvpn# pivpn -a
Enter a Name for the Client:  ^C
```
So, some bug there ..

**Comment by 4s3ti** [comment] 2022-09-17 15:08
Think this was probably fixed in the meantime. 

Re-Open if I am wrong.

**Closed by 4s3ti** 2022-09-17 15:08 UTC
Labels: bug, Needs Investigation
