### ISSUE TITLE
Installer fails at 'Configuring netfilter-persistent' step and without any message.

### ISSUE THREAD

**Issue by christyler80** [pivpn/pivpn#756] opened 2019-05-27 20:57 UTC
## In raising this issue, I confirm the following: 

`{please fill the checkboxes, e.g: [X]}`

- [] I have read and understood the [contributors guide](https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md).
- [] The issue I am reporting can be *replicated*.
- [] The issue I am reporting can be *is* directly related to the pivpn installer script.
- [] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pivpn/pivpn/wiki/FAQ), [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed), and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen)).

### Have you searched for similar issues and solutions?
    (yes/no / which issues?)

### Console output of      `curl -L install.pivpn.io | bash`
```
  Output Here
```

### Console output of      `pivpn add` or `pivpn add nopass`
```
  Output Here
```

### Console output of      `pivpn debug`
```
  Output Here
```
### Have you taken any steps towards solving your issue?
```
  which?
```

**Comment by christyler80** [comment] 2019-05-30 09:33
Running PiVPN 'uninstall', then commenting out lp, ppdev, parport_pc_ in /etc/modules-load.d/cups-filters.conf, before re running the PIVPN installation (i.e. curl installer) resolved this problem for me.

**Comment by 4s3ti** [comment] 2019-05-30 11:34
since you managed to resolve it will be closing the issue. 
next time please provide all the details requested in the issue template, we ask for them for a reason! 

we can't help PiVPN Users with their issues if they don't help us understand what the issue is. 
right in the same way that we don't go to a doctor without telling our symptoms!

**Closed** 2019-05-30 11:34 UTC
