### ISSUE TITLE
problem connecting to newly installed pivpn

### ISSUE THREAD

**Issue by Baimba** [pivpn/pivpn#276] opened 2017-06-16 04:29 UTC
So, I am totally new to all this. 
this is the result I am getting when I try to connect to the pivpn server installed on my pi3. I have been trying for hours now, still no connection. I have read much of the threads but I cannot find anything pertaining to this issue or how it can be solved. 
Please help me solve this. If anyone can point out the mistakes I am making and tell me how to correct it I shall be grateful. 
I will provide any information that is needed.
PLEASE HELP!!!!!!

Fri Jun 16 00:11:21 2017 Windows version 6.2 (Windows 8 or greater) 64bit
Fri Jun 16 00:11:21 2017 library versions: OpenSSL 1.0.2k  26 Jan 2017, LZO 2.10
Fri Jun 16 00:11:30 2017 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
Fri Jun 16 00:11:30 2017 TCP/UDP: Preserving recently used remote address: [AF_INET]71.76.216.46:1194
Fri Jun 16 00:11:30 2017 UDP link local: (not bound)
Fri Jun 16 00:11:30 2017 UDP link remote: [AF_INET]71.76.216.46:1194
Fri Jun 16 00:12:30 2017 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
Fri Jun 16 00:12:30 2017 TLS Error: TLS handshake failed
Fri Jun 16 00:12:30 2017 SIGUSR1[soft,tls-error] received, process restarting
Fri Jun 16 00:12:35 2017 TCP/UDP: Preserving recently used remote address: [AF_INET]71.76.216.46:1194
Fri Jun 16 00:12:35 2017 UDP link local: (not bound)
Fri Jun 16 00:12:35 2017 UDP link remote: [AF_INET]71.76.216.46:1194
Fri Jun 16 00:13:35 2017 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
Fri Jun 16 00:13:35 2017 TLS Error: TLS handshake failed
Fri Jun 16 00:13:35 2017 SIGUSR1[soft,tls-error] received, process restarting
Fri Jun 16 00:13:40 2017 TCP/UDP: Preserving recently used remote address: [AF_INET]71.76.216.46:1194
Fri Jun 16 00:13:40 2017 UDP link local: (not bound)
Fri Jun 16 00:13:40 2017 UDP link remote: [AF_INET]71.76.216.46:1194

*****This the information from the .ovpn file: 
Again, I do not understand any of it yet.

client
dev tun
proto udp
remote 71.76.216.46 1194
resolv-retry infinite
nobind
persist-key
persist-tun
key-direction 1
remote-cert-tls server
tls-version-min 1.2
verify-x509-name server name
cipher AES-256-CBC
auth SHA256
comp-lzo
verb 1
<ca>

</ca>
<cert>

</cert>
<key>

</key>
<tls-auth>

# PiVPN Issue Template

## Console output of `curl install.pivpn.io | bash`
```

```

## Console output of `pivpn add` or `pivpn add nopass`
```

```

## Console output of `pivpn debug`
```

```

**Comment by redfast00** [comment] 2017-06-16 06:18
Did you forward the port within your router? Do you have a static external IP address?

**Comment by Baimba** [comment] 2017-06-16 06:54
Yes. I forwarded both internal and external ports. 1194. 
Also have a static external ip address.

**Comment by DewGew** [comment] 2017-06-16 08:01
I have the same problem ...

**Comment by redfast00** [comment] 2017-06-16 09:52
Are you trying this from inside or outside of your network? Do you have an Android phone you can test this with?

**Comment by cfcolaco** [comment] 2017-06-16 10:37
Please read issue #275 try everything I Mention in the comments and then post here the result.

The most common cause of:

TLS key negotiation failed to occur within 60 seconds (check your network connectivity)

Is NOT starting openvpn **as administrator** ( right click on icon > run as administrator ) 


If this doesn't result comment the `tls-version-min 1.2` booth on client .ovpn and server.conf files.

**Comment by Baimba** [comment] 2017-06-16 15:00
My android phone connects to the pivpn server from outside the local network  (via 4G). But I cannot access any websites. 
This is the log:

10:51 AM OpenVPN 2.5-icsopenvpn [git:icsopenvpn-a3a71dc0a6604559] android-14-armeabi-v7a [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on May 11 2017

**Comment by Baimba** [comment] 2017-06-16 15:06
10:51 AM library versions: OpenSSL 1.0.2k  26 Jan 2017, LZO 2.09
10:51 AM WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
10:51 AM TCP/UDP: Preserving recently used remote address: [AF_INET]71.76.216.46:1194
10:51 AM UDP link local: (not bound)
10:51 AM UDP link remote: [AF_INET]71.76.216.46:1194
10:51 AM [server] Peer Connection Initiated with [AF_INET]71.76.216.46:1194
10:51 AM GDG: SIOCGIFHWADDR(lo) failed
10:51 AM do_ifconfig, tt->did_ifconfig_ipv6_setup=0
10:51 AM Initialization Sequence Completed

**Comment by cfcolaco** [comment] 2017-06-16 15:09
@Baimba try to comment the 

`tls-version-min 1.2`

in booth client.ovpn and `/etc/openvpn/server.conf `
then on your pi

`sudo systemcl restart openvpn`

**Comment by Baimba** [comment] 2017-06-16 19:54
OK. I am able to connect to the server after starting the client as administrator. I still cannot connect to websites though. What gives? 
I am about to comment out....... tls-version-min 1.2.
restart and see what happens. I'll post the logs here.

Thanks so far........... for getting me signed in to the server.

**Comment by Baimba** [comment] 2017-06-16 20:00
is it sudo systemcl restart openvpn........ or sudo systemctl restart openvpn ?

**Comment by Baimba** [comment] 2017-06-16 20:18
see below the results of commenting out tls-version-min 1.2 in both the .conf file and the .ovpn files.

I still cannot connect to websites. Is there anything else I could be missing or doing wrong?

Please Help.

Fri Jun 16 16:11:30 2017 OpenVPN 2.4.2 x86_64-w64-mingw32 [SSL (OpenSSL)] [LZO] [LZ4] [PKCS11] [AEAD] built on May 11 2017
Fri Jun 16 16:11:30 2017 Windows version 6.2 (Windows 8 or greater) 64bit
Fri Jun 16 16:11:30 2017 library versions: OpenSSL 1.0.2k  26 Jan 2017, LZO 2.10
Enter Management Password:
Fri Jun 16 16:11:39 2017 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
Fri Jun 16 16:11:39 2017 TCP/UDP: Preserving recently used remote address: [AF_INET]71.76.216.46:1194
Fri Jun 16 16:11:39 2017 UDP link local: (not bound)
Fri Jun 16 16:11:39 2017 UDP link remote: [AF_INET]71.76.216.46:1194
Fri Jun 16 16:11:40 2017 [server] Peer Connection Initiated with [AF_INET]71.76.216.46:1194
Fri Jun 16 16:11:41 2017 open_tun
Fri Jun 16 16:11:41 2017 TAP-WIN32 device [Ethernet 2] opened: \\.\Global\{93DB4811-8BAC-46FC-950E-DC0D14E64677}.tap
Fri Jun 16 16:11:41 2017 Set TAP-Windows TUN subnet mode network/local/netmask = 10.8.0.0/10.8.0.2/255.255.255.0 [SUCCEEDED]
Fri Jun 16 16:11:41 2017 Notified TAP-Windows driver to set a DHCP IP/netmask of 10.8.0.2/255.255.255.0 on interface {93DB4811-8BAC-46FC-950E-DC0D14E64677} [DHCP-serv: 10.8.0.254, lease-time: 31536000]
Fri Jun 16 16:11:41 2017 Successful ARP Flush on interface [14] {93DB4811-8BAC-46FC-950E-DC0D14E64677}
Fri Jun 16 16:11:41 2017 do_ifconfig, tt->did_ifconfig_ipv6_setup=0
Fri Jun 16 16:11:46 2017 Initialization Sequence Completed

**Comment by cfcolaco** [comment] 2017-06-16 21:44
@Baimba it is systemctl sorry my bad! 

seems now that the issue is similar to #275 
This weekend will be hard for me to make some tests ... however, I will think about booth issues.

**Comment by Baimba** [comment] 2017-06-16 21:49
Cfcolaco. ..... thanks so much for your help. I look forward to you help on the issue of accessing websites after connecting to the server.

**Comment by cfcolaco** [comment] 2017-06-16 22:11
@Baimba meanwhile post here your 

server.conf

and the output of 

sudo iptables -t nat -S
sudo iptables -S

**Comment by Baimba** [comment] 2017-06-17 05:10
server.conf:

dev tun
proto udp
port 1194
ca /etc/openvpn/easy-rsa/pki/ca.crt
cert /etc/openvpn/easy-rsa/pki/issued/server.crt
key /etc/openvpn/easy-rsa/pki/private/server.key
dh /etc/openvpn/easy-rsa/pki/dh2048.pem
topology subnet
server 10.8.0.0 255.255.255.0
# server and remote endpoints
ifconfig 10.8.0.1 10.8.0.2
# Add route to Client routing table for the OpenVPN Server
push "route 10.8.0.1 255.255.255.255"
# Add route to Client routing table for the OPenVPN Subnet
push "route 10.8.0.0 255.255.255.0"
# your local subnet
push "route 0.0.0.0 "
# Set your primary domain name server address for clients
push "dhcp-option DNS 8.8.8.8"
push "dhcp-option DNS 8.8.4.4"
# Override the Client default gateway by using 0.0.0.0/1 and
# 128.0.0.0/1 rather than 0.0.0.0/0. This has the benefit of
# overriding but not wiping out the original default gateway.
push "redirect-gateway def1"
client-to-client
duplicate-cn
keepalive 10 120
#tls-version-min 1.2
tls-auth /etc/openvpn/easy-rsa/pki/ta.key 0
cipher AES-256-CBC
auth SHA256
comp-lzo
user nobody
group nogroup
persist-key
persist-tun
#crl-verify /etc/openvpn/crl.pem
status /var/log/openvpn-status.log 20
status-version 3
# Override the Client default gateway by using 0.0.0.0/1 and
# 128.0.0.0/1 rather than 0.0.0.0/0. This has the benefit of
# overriding but not wiping out the original default gateway.
push "redirect-gateway def1"
client-to-client
duplicate-cn
keepalive 10 120
#tls-version-min 1.2
tls-auth /etc/openvpn/easy-rsa/pki/ta.key 0
cipher AES-256-CBC
auth SHA256
comp-lzo
user nobody
group nogroup
persist-key
persist-tun
#crl-verify /etc/openvpn/crl.pem
status /var/log/openvpn-status.log 20
status-version 3
log /var/log/openvpn.log
verb 1
# Generated for use by PiVPN.io


output of 
sudo iptables -t nat -S 👍 

pi@raspberrypi:~ $ sudo iptables -t nat -S
-P PREROUTING ACCEPT
-P INPUT ACCEPT
-P OUTPUT ACCEPT
-P POSTROUTING ACCEPT


output of 
sudo iptables -S

pi@raspberrypi:~ $ sudo iptables -S
-P INPUT ACCEPT
-P FORWARD ACCEPT
-P OUTPUT ACCEPT

These are the results I got from running the command. I hope this will help figure out what my problem is. Thanks again

**Comment by cfcolaco** [comment] 2017-06-17 10:37
So far seems to be a problem with your IPtables rules, for some reason they weren't written or applied.
that's what we need to track right now.  It will be a bit long, so please be sure you understand everything I will write here, if it happens that you don't understand something, just ask and I'll clarify! :)

Just to be sure, are you using raspbian? **if yes do**:

```
cat /etc/iptables/rules.v4
```
and confirm that you have something similar to this:

```
:PREROUTING ACCEPT [0:0]
:INPUT ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
:POSTROUTING ACCEPT [0:0]
-A POSTROUTING -s 10.8.0.0/24 -o eth0 -j MASQUERADE  <---- special attention here
COMMIT
```

**If everything is ok do:**

`iptables-restore < /etc/iptables/rules.v4`

then check again if the rules have been applied with `sudo ìptables -t nat -S` 
and try to connect to VPN and access to websites! 
If everything went well, **uncomment** the tls line you commented previously in server and client and try again! =) 

**If it happens that those rules don't exist**
something went wrong while installing pivpn, so we need to create them and check everything. 

do:

```
sudo iptables -t nat -A POSTROUTING -s 10.8.0.0/24 -o eth0 -j MASQUERADE
sudo iptables-save > /etc/iptables/rules.v4
```
check if packet forwarding is enabled: 

```
$ sudo grep ip_forward /etc/sysctl.d/99-sysctl.conf

net.ipv4.ip_forward=1  <--- this is the expected output
 ```
if it appears with commented ( with a # ) or =0

edit `/etc/sysctl.d/99-sysctl.conf` and uncomment it or change the 0 to 1 and then do:

`sysctl -p /etc/sysctl.d/99-sysctl.conf`

reboot the system and then check again if the rules have been applied with `sudo iptables -t nat -S` 
and try to connect to VPN and access to websites! 
If everything went well, **uncomment** the tls line you commented previously in server and client and try again! =) 


another thing I noticed is the:
```
# your local subnet
push "route 0.0.0.0 "
```

do you require access to any device inside your local network or you just need to access to websites? 
if you require access to any device inside your local network you should change the `0.0.0.0` to 

```push "route 192.168.1.0 255.255.255.0"``` if it happens to be your local network, otherwise change it to the correct values of your network.

Hope this solves the problem and that I made this simple and clear!
if there's anything that you don't understand just ask! =)

**Comment by Baimba** [comment] 2017-06-17 12:35
This is the result of the command:

pi@raspberrypi:~ $ cat /etc/iptables/rules.v4
cat: /etc/iptables/rules.v4: No such file or directory

**Comment by Baimba** [comment] 2017-06-17 12:39
It appears that everything is not ok. What shall I do next?

**Comment by cfcolaco** [comment] 2017-06-17 12:48
what a mess we have here! =/ 
seems that for some reason PiVPN script failed to install iptables-persistent ... any clue why @redfast00 @0-kaladin ?

we have 2 options here:
1 -  Uninstall PiVPN, run sudo apt-get update && sudo apt-get upgrade, and then reinstall PiVPN and hope everything runs as expected now. 

2 - Just run sudo apt-get install iptables-persistent and then follow what I said in the previous comment 

it's up to you!

**Comment by Baimba** [comment] 2017-06-17 13:46
I ran the command as root and rebooted:
 sudo iptables -t nat -A POSTROUTING -s 10.8.0.0/24 -o eth0 -j MASQUERADE
sudo iptables-save > /etc/iptables/rules.v4

this is the result:

pi@raspberrypi:~ $ cat /etc/iptables/rules.v4
# Generated by iptables-save v1.4.21 on Sat Jun 17 13:26:02 2017
*filter
:INPUT ACCEPT [38591:4707103]
:FORWARD ACCEPT [6624:683298]
:OUTPUT ACCEPT [2121:254702]
COMMIT
# Completed on Sat Jun 17 13:26:02 2017
# Generated by iptables-save v1.4.21 on Sat Jun 17 13:26:02 2017
*nat
:PREROUTING ACCEPT [26:7391]
:INPUT ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
:POSTROUTING ACCEPT [0:0]
-A POSTROUTING -s 10.8.0.0/24 -o etho -j MASQUERADE
-A POSTROUTING -s 10.8.0.0/32 -o etho -j MASQUERADE
COMMIT
# Completed on Sat Jun 17 13:26:02 2017

rebooted again and connected to the server.......... but I still cannot access any websites. I am going to try your option 2 above and report the results here.

**Comment by Baimba** [comment] 2017-06-17 13:56
After reboot and running option 2, the results are the same as reported above. Still cannot access websites.

**Comment by Baimba** [comment] 2017-06-17 14:28
apt-get install iptables-persistent. result is below:

pi@raspberrypi:~ $ sudo apt-get install iptables-persistent
Reading package lists... Done
Building dependency tree
Reading state information... Done
iptables-persistent is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

**Comment by cfcolaco** [comment] 2017-06-17 18:08
-A POSTROUTING -s 10.8.0.0/24 -o etho -j MASQUERADE
-A POSTROUTING -s 10.8.0.0/32 -o etho -j MASQUERADE 


is that really a o ( the letter???) ...
edit /etc/iptables/iptables.v4 change etho and replace the o with a 0 (zero) eth0 (Eth"Zero")

**Comment by Baimba** [comment] 2017-06-18 07:28
So, how do I edit /etc/iptables/iptables.v4 ? it will not open in nano. Can't figure out how to get into the file to edit it. Please HELP. I am at a total loss here.

**Comment by cfcolaco** [comment] 2017-06-18 09:55
@Baimba nano should open the file ... but the file in question is `/etc/iptables/rules.v4` **not** `iptables.v4` ... Please pay attention to file names and to what is told, and don't just blind copy everything I place here because sometimes whoever is supporting can make mistakes to! it's important to understand what we are telling you to do! 
if nano can't open the file ... I will guess that you might have messed up somewhere in your fresh install of raspbian! which is hard to track this way ...

**Comment by Baimba** [comment] 2017-06-19 01:49
OK, So I am going to uninstall Pivpn. Run apt-get update and apt-get upgrade, reinstall Pivpn then report the results here.

**Comment by Baimba** [comment] 2017-06-19 02:59
WOW..      WOW.. 
After uninstalling and reinstalling Pivpn, I am happy to report that everything seems to be working well. I connected to the server promptly and I am able to access websites both from inside and outside my local network.
It seems that reinstalling the Pivpn did the trick. 
I am very grateful to everyone here who took the time to help me understand this process. **Special Thanks to @cfcolaco for his patience and his time. ..........

**Comment by cfcolaco** [comment] 2017-06-19 07:23
Glad to know that it is working now ;) 
In the future if you have further questions feel free to ask either here or at #pivpn irc channel where i am whenever i can ;)

Meanwhile if you dont have further questions please close this issue!  Enjoy your vpn :D

**Closed** 2017-06-19 09:14 UTC
