### ISSUE TITLE
Connects via Mobile Network, but not via Wifi

### ISSUE THREAD

**Issue by JulianKeller** [pivpn/pivpn#340] opened 2017-08-24 04:26 UTC
I've setup pivpn and i'm using OpenVPN on my iPhone to connect to the vpn. The problem is that I can connect to the vpn fine if I am using my Mobile Data, but I cannot connect to it if I am using Wifi. OpenVPN will just timeout when connecting with Wifi. 

I logged into my router and set it to port forward the pi's ip address. Which is a 192.********* number on my local network. It appears that when connected to Wifi OpenVPN is trying to connect to my public ip address which is a 174********* number. 

What might I be doing wrong? Maybe my port forwarding is setup incorrectly?

**Comment by redfast00** [comment] 2017-08-24 12:38
Are you connecting to the VPN from the network the server is on? Have you tried connecting from a public access point, like at a library, cafe,...?

**Comment by JulianKeller** [comment] 2017-08-25 04:22
Yes I was trying to connect from the same network that the server was on. I tried connecting today from my a public wifi network away from my home, but no luck, it just times out. Connecting from my mobile data is also timing out now.

**Comment by redfast00** [comment] 2017-08-25 06:56
That's strange. Did you change anything? Do you have a static public IP address? What client are you using?

**Comment by cfcolaco** [comment] 2017-08-27 19:33
@JulianKeller 

Check your port forwarding. Make sure you are forwarding the correct protocol. 

And update your initial post with the information we ask for in the issue template... that information is crucial for us to help you the best and to make life easier for us to help you out!

**Comment by RicePls** [comment] 2017-08-28 05:29
I also have the same problem. I can connect to the .ovpn profile on mobile data, but can not on wifi. I even have the correct port forwarded.

**Comment by cfcolaco** [comment] 2017-08-28 06:49
Ok, @JulianKeller @RicePls  there's something here that I am not understanding, you both say, that you can connect through mobile Data but not trough Wi-Fi. 

Is the Wi-Fi network, the same network where the Pi is on?? 

Is useless to connect to a VPN that's in the same network as you are in the moment!!

**Comment by RicePls** [comment] 2017-08-28 06:59
@cfcolaco Yeah, the Wi-Fi network is the same on the Pi. When I first transferred my .ovpn profile, I was confused at first why it did not connect. That is until I turned off Wi-Fi on my device and it connected. I realize it would be useless on the home network lol. I thought my PiVPN setup was broken or something.

**Comment by JulianKeller** [comment] 2017-08-28 15:34
I was trying to connect to the same wifi network that my PI was on. That makes sense why it wasn't working.

**Comment by cfcolaco** [comment] 2017-08-28 15:46
So it means there's no issue at all then? 

you both can access when you are outside right? 

if yes please close the issue

**Comment by gordonZta** [comment] 2017-09-01 18:43
There is still an issue. Even though it may be useless to connect via VPN into the same network the Pi is on, it should still work.

**Comment by Mellgood** [comment] 2017-09-06 23:27
I've tried to connect to my Pi using the same network and it works.
It seems very strange to me that you can connect over mobile network but you are not able to connect using your wlan... can you try to connect using a pc/mac instead of your mobile phone using the same .ovpn config file? 
I think the problem can be on some specific iphone-wifi default routing metric but i haven't got an iphone to perform any test. 
meanwhile... Is anyone having the same issue on android?

**Comment by yanvigdev** [comment] 2017-09-13 17:22
Hello.
I installed piVpn on a raspberry in raspbian jessie in order to access my computers at home and use my own DNS from anywhere.
I am on iPhone 6s and I use OpenVPN Connect in version 1.1.1. When I connect from the 3g network to the VPN it works. But when I connect from a wifi network it does not work (no ping on my computers and no personal DNS).
I asked a friend about Android to do the same experience and in 3g or wifi everything works correctly.

**Comment by cfcolaco** [comment] 2017-10-30 21:56
Closing this issue. if further help needed please raise new issue explaining exactly what is your problem and what you need help with! 

thus connecting from the same local network  or from networks with the same Local IP Subnet makes sense that things fail!!

**Closed by cfcolaco** 2017-10-30 21:56 UTC

**Comment by yanvigdev** [comment] 2017-10-31 07:51
Closing this ticket doesn't solve the problem.

**Comment by cfcolaco** [comment] 2017-10-31 08:16
@yanvigdev agree with you!! and I don't like unsolved problems!! that's why I said to raise a new issue with detailed information on the issue!! 

I loose 90% of my helping ppl time asking for information!! =/ 

If you still have issue, please open a new issue, with detailed information, so I can track and help you the best I can!! 

Please be aware of one thing: if you are connected on a WI-fi network with the same subnet as yours, you wont be able to access your remote local network. 

let's say it like this: 
    UNSECURE SUBNET: 192.168.1.0/24
    YOUR LOCAL REMOTE SUBNET: 192.168.1.0/24 

OpenVPN will fail to add routes since they get into conflict ... as it already exists ... makes sense?? 

Thank you for being interested!! 
I will be glad to help you out.

**Comment by sbstnrjs** [comment] 2018-06-07 17:03
This is my first time commenting so I am not sure of how useful it is to do so on a closed ticket. 
I have the same issue, and I think the problem just wasn't explained correctly. My PiVPN has been running smoothly for months. Lately it does not connect if I am using wifi. From anywhere. If I switch to mobile data on my iPhone, it connects succesfully. I have wiped my Pi, reinstalled PiVPN, checked that my IP is static and that my ports are forwarded correctly. (I use TCP 443 to get around the network policy of my workplace). I could use some help. While I am technical, I am not that knowledgeable when it comes to networking. 

Thx.

**Comment by cfcolaco** [comment] 2018-06-07 17:20
@sbstnrjs this is a closed issue you should have opened a new one ... but as i say in the last comment 

Please be aware of one thing: if you are connected on a WI-fi network with the same subnet as yours, you wont be able to access your remote local network.

> let's say it like this:
> UNSECURE SUBNET: 192.168.1.0/24
> YOUR LOCAL REMOTE SUBNET: 192.168.1.0/24
> 
> OpenVPN will fail to add routes since they get into conflict ... as it already exists ... makes sense??

**Comment by Mellgood** [comment] 2018-06-07 17:36
Can you please explain better where can the conflict happen? The network schema should be something like:

Router_gateway@PUBLIC_IP_ADDRESS --- Raspberry@192.168.1.0/24 --- vpn_server@10.8.0.1 --- vpn_client@10.8.0.n

So I can not figure out how does the conflict may exist

**Comment by cfcolaco** [comment] 2018-06-07 19:58
@sbstnrjs I am not saying you are connecting withing your own home .. what's your home (INTERNAL) subnet? I will give a better example: 

Your home network is 192.168.1.0/24 .. .your router is for example 192.168.1.1 and your pi 192.168.1.2

yo go to a friends house ... his house (INTERNAL) Network is also the same 192.168.1.0/24 ... your friend router is 192.168.1.<something> 

It will fail! because both subnets are the same and it will be as if you were trying to connect within your own network.

so if you are using a common internal subnet ... expect to have a lot of issues as even big companies tend to use them for their internal networks.

**Comment by sbstnrjs** [comment] 2018-06-07 20:01
The problem with that explanation though is that is has worked for a year or more, from everywhere. It just suddenly stopped working. So while I understand what your saying. I don’t see how it would suddenly cause an issue that didn’t exist before.

**Comment by cfcolaco** [comment] 2018-06-07 20:14
@sbstnrjs something might have changed in the meanwhile, so if that is the case we need more details to help to troubleshoot, please open a new issue providing logs both from server and client side so we can find out where the issue is.

**Comment by sbstnrjs** [comment] 2018-06-07 22:37
Ok. I Will do that. Thank you.
