### ISSUE TITLE
Add "--unattended" option

### ISSUE THREAD

**Issue by EWouters** [pivpn/pivpn#223] opened 2017-03-12 08:40 UTC
It would be awesome if there would be an unattended option for the script like pi-hole has. I'd be willing to implement it if more people are interested. I don't have too much experience, but it wouldn't be too hard to port the functionality from pi-hole to this script.

**Comment by redfast00** [comment] 2017-03-12 09:16
There has been some interest in this before (see #86), so if you want to do this, go for it!

**Comment by EWouters** [comment] 2017-03-13 07:22
I implemented it in #224. It was slightly more intrusive than I anticipated.

**Comment by acejacek** [comment] 2017-05-30 22:44
There is problem with installation of unattended-upgrades package:

```
pi@raspberrypi:~ $ sudo apt-get --yes --quiet --no-install-recommends install unattended-upgradesReading package lists...
Building dependency tree...
Reading state information...
unattended-upgrades is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.
2 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Setting up netfilter-persistent (1.0.3+deb8u1) ...
update-rc.d: warning: start and stop actions are no longer supported; falling back to defaults
A dependency job for netfilter-persistent.service failed. See 'journalctl -xn' for details.
invoke-rc.d: initscript netfilter-persistent, action "start" failed.
dpkg: error processing package netfilter-persistent (--configure):
 subprocess installed post-installation script returned error exit status 1
dpkg: dependency problems prevent configuration of iptables-persistent:
 iptables-persistent depends on netfilter-persistent (= 1.0.3+deb8u1); however:
  Package netfilter-persistent is not configured yet.

dpkg: error processing package iptables-persistent (--configure):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 netfilter-persistent
 iptables-persistent
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

```
pi@raspberrypi:~ $ uname -a
Linux raspberrypi 3.16.0-4-686-pae #1 SMP Debian 3.16.36-1+deb8u2 (2016-10-19) i686 GNU/Linux
```

```
pi@raspberrypi:~ $ cat /etc/debian_version 
8.8
```

**Comment by cfcolaco** [comment] 2017-05-31 00:05
@acejacek think it has nothing to do with --unatended, however it seems similar in everything to to issue #231 , please check it out.

**Comment by redfast00** [comment] 2017-06-14 18:54
Closing this since it's a duplicate of #86 and has been implemented. Thanks @EWouters!

**Closed by redfast00** 2017-06-14 18:54 UTC
Labels: enhancement
