### ISSUE TITLE
[FR] Wireguard support Ubuntu 20.04 arm64

### ISSUE THREAD

**Issue by takov751** [pivpn/pivpn#1005] opened 2020-04-01 18:42 UTC
**Is your feature request related to a problem? Please describe.**

I am using a raspberrypi4 with ubuntu server 20.04 daily. However the installation script does not support wireguard, however ubuntu server 20.04 repo contains the wireguard packages and dkms module.

**Describe the solution you'd like**

I would like to request to add this OS and arch as supported.

**Describe alternatives you've considered**
An option to force wireguard if the package presented in repo.

**Additional context**

I know this OS still in development,however at this point ubuntu 20.04 reached beta feature freeze and the release date is around end of April.

Great project. Thank you all your hard work.

**Comment by orazioedoardo** [comment] 2020-04-02 07:31
The main difficulty for automating WireGuard is that you need the kernel headers package for the specific distribution, and they have different names.

I heard that Ubuntu 20.04 has the wireguard kernel module build in. Can you check (without installing `wireguard-dkms`) using:

`find /lib/modules/$(uname -r) -type f -name ‘wireguard.ko’`

**Comment by takov751** [comment] 2020-04-02 13:58
Sadly no, only dkms available. The current kernel version on 20.04 arm64 is 5.4. and the solution that they use at the moment that 20.04 comes with a wireguard multiarch ppa until the kernel with wireguard support comes.

I see your point ,better wait for now.
Thank you. I will try to update this issue if there is any change in the near future.

**Comment by orazioedoardo** [comment] 2020-04-02 15:00
Yeah I know that Ubuntu 20.04 will ship with kernel 5.4 (which is an LTS kernel), however it should have the wireguard module backported.

https://git.launchpad.net/~ubuntu-kernel/ubuntu/+source/linux/+git/focal/commit/?h=master-next&id=026034ef5821d0b0aacebfa4f6a2472be3b7ed38

```
+  * Build and ship a signed wireguard.ko (LP: #1861284)
+    - [Packaging] wireguard — add support for building signed .ko
+    - [Config] wireguard — enable on all architectures
```

**Comment by proper-type** [comment] 2020-04-10 20:53
Hey guys! I'm running a fresh Installation of Ubuntu Server 20.04 on my Raspi 4. I'd love to have pivpn supported.

> Can you check (without installing wireguard-dkms) using:
> find /lib/modules/$(uname -r) -type f -name ‘wireguard.ko’

The command is not giving any output.
The kernel is already freezed for 20.04 (as stated [here](https://wiki.ubuntu.com/FocalFossa/ReleaseSchedule) )
You don't need Wireguard-dkms for it to run, I tried it on my Desktop running 20.04 too. You just have to install the package wireguard and wireguard-utils and it's working.

**Comment by peatrick** [comment] 2020-04-10 23:38
I'm fiddling around with Ubuntu Focal Fossa 20.04 (development branch beta) running x86_64 Linux kernel 5.4.0-21-generic and everything seems to deploy just fine with this great script, but don't appear to be getting a handshake.  I see my Peers transmitting a small amount of data, but no packets through the forwarded port on the router, nor any handshake at the `wg` server.

I'm obviously missing something, eh?  Too early??

**Comment by orazioedoardo** [comment] 2020-04-11 07:30
@peatrick In the future if you are not sure whether the problem is with wireguard or the port forwarding, temporarily change `Endpoint = ` to the local IP of the Raspberry Pi in the client config.

> EDIT: I'm a complete doofus. Removed and recreated the port forward and now traffic seems to properly pass through. Handshakes work from both peers I had configured for testing purposes. Can confirm, script works out of the box on an Ubuntu Server 20.04 LTS VM.

Excellent

> The command is not giving any output.

@proper-type My command had wrong quotes, can you check the edited comment on the Raspberry Pi?

> You don't need Wireguard-dkms for it to run, I tried it on my Desktop running 20.04 too. You just have to install the package wireguard and wireguard-utils and it's working.

I know, if the module is available on Raspberry Pi + Desktop, Ubuntu 20.04 support should be straightforward.

**Comment by proper-type** [comment] 2020-04-11 19:16
The command is still not giving any output. Searching for wireguard.ko in /lib/modules/ isn't, too. When I run lsmod it's not listed.

**Comment by proper-type** [comment] 2020-04-11 19:18
When I try to install wireguard it wants to install it via dkms. Maybe the server kernel hasn't implemented wireguard? (Would be silly)

**Comment by proper-type** [comment] 2020-04-13 14:31
When i try to use the script on my Raspberry Pi 4 with Ubuntu 20.04 Server, the script always wants to install openvpn instead of letting me decide for wireguard. Is this intended?

**Comment by takov751** [comment] 2020-04-14 05:58
Yes it is.

**Comment by mwoolweaver** [comment] 2020-04-14 07:55
`apt-cache search linux-headers-$(uname -r)`
^ ^ seems to be a reliable way to find the proper header package.


`apt install linux-headers-$(uname -r)` 
^ ^ will install the one displayed in the search done in the previous command.

**Comment by orazioedoardo** [comment] 2020-04-18 08:23
Can any of you check what's the kernel headers package on Ubuntu for Raspberry (18.04 or 20.04)? Is it `raspberrypi-kernel-headers` or, like @mwoolweaver said `linux-headers-something`?

**Comment by peatrick** [comment] 2020-04-18 09:07
> Can any of you check what's the kernel headers package on Ubuntu for Raspberry (18.04 or 20.04)? Is it `raspberrypi-kernel-headers` or, like @mwoolweaver said `linux-headers-something`?

Sorry, I'm on Raspbian Lite (buster), but please check this:

`sudo apt-cache search raspberrypi-kernel-headers`

currently on this kernel: Linux pihole2 **4.19.97-v7+** #1294 SMP Thu Jan 30 13:15:58 GMT 2020 armv7l GNU/Linux

**Comment by mwoolweaver** [comment] 2020-04-19 15:30
so I have learned recently that if you use/used `rpi-update` you likely won't be able to find the correct headers using `apt-get` but while learning this i stumbled upon this tool that will grab headers for `rpi-update` kernels.


[notro/rpi-source/wiki](https://github.com/notro/rpi-source/wiki)

**Comment by proper-type** [comment] 2020-04-23 10:56
The wireguard module for linux-raspi has been committed and should be available very soon.
See https://bugs.launchpad.net/ubuntu/+source/linux-raspi/+bug/1872702

**Comment by peatrick** [comment] 2020-04-23 11:41
> The wireguard module for linux-raspi has been committed and should be available very soon.
> See https://bugs.launchpad.net/ubuntu/+source/linux-raspi/+bug/1872702

Will that backport be handled by the Ubuntu team? I'm curious if the Raspbian folks will also have to do their own, or if it could be compiled and used on all ARM Deb family distros. I'd be fine rebuilding my RPi3B+ Pi-hole & Wireguard VPN appliance with either. Regardless of my lack of comprehension, this is very exciting stuff.

`wireguard-dkms` borks my RPi device more often than not with most kernel upgrades and has been a real bear getting the VPN going again after the update.

**Comment by proper-type** [comment] 2020-04-23 12:37
> Will that backport be handled by the Ubuntu team?
Yes, the feature request has been handled by an Ubuntu developer.

> I'm curious if the Raspbian folks will also have to do their own, or if it could be compiled and used on all ARM Deb family distros
Only way to find out is to create a feature request for Raspbian and point the Raspbian devolopers to the commit for the Ubuntu kernel. IMO it should be possible, but I'm not that deep into the subject.

**Comment by scorpio2k2** [comment] 2020-04-25 10:58
wireguard.ko available but still no wireguard option.

**Comment by orazioedoardo** [comment] 2020-04-26 09:29
Can any of you tag me if the WireGuard module gets backported in the official kernel on ARM Ubuntu 20.04 or Raspbian 10?

**Comment by proper-type** [comment] 2020-04-27 22:12
The wireguard kernel module has been back ported to Ubuntu ARM. Raspbian Wireguard Support is not planned at the moment.

**Comment by peatrick** [comment] 2020-04-27 22:24
> Raspbian Wireguard Support is not planned at the moment.

That's rather unfortunate.  Guess I'm going to be switching to Ubuntu ARM this afternoon (my 20.04 ESXi VM has been wonderful thus far -- although only on week one of usage).  Thanks for the updated information @proper-type sir.

**Comment by peatrick** [comment] 2020-04-28 01:33
Have been running Raspbian 10 Lite (buster) on an **RPi3B+** for a couple years now, but what a hassle to have to troubleshoot Wireguard each and every time there's an update to the kernel, totally borks my VPN -- so i finally cannibalized my RetroPie device and spun up Ubuntu 20.04 LTS on this **RPi3B** (non-plus), so far so good, but having some minor issues with my VPN.  Not trying to hijack this thread, as I haven't had time to dig into the potential issues just yet, I probably messed something up migrating my config over, using SCP.  I get a handshake, it's just not passing as much traffic as it should and nothing seems to resolve at the moment.  Thanks for the heads up on wireguard kernel module.  Looking forward to tinkering more.

```
interface: wg0
  public key: yOttu2ElVflqJY8vWegpYedeuY0CkeXjoy44yOZMah8=
  private key: (hidden)
  listening port: 50420

peer: OLGH4W12Igj+Z8JYbc7jMOJSwo48rjMCf9cXbLD0gzM=
  preshared key: (hidden)
  endpoint: 10.10.10.126:46114
  allowed ips: 10.6.0.3/32
  latest handshake: 2 minutes, 40 seconds ago
  transfer: 21.48 KiB received, 380 B sent
```

**Comment by 4llonsy** [comment] 2020-05-23 13:25
Any updates?

**Comment by IevgenSobko** [comment] 2020-06-22 17:38
I guess for Ubuntu 20.04 support might be added easily.
Just install wiregurd-tools and that is it as they backported wireguard to their current kernel 5.4 and official image for Raspberry PI has been released with native kernel support for Wireguard.

**Comment by MichaIng** [comment] 2020-06-28 15:33
I just wanted to open a new topic about generic WireGuard support when the kernel module is shipped with the kernel package itself. Since WireGuard has been officially integrated into Linux 5.6 and is backported by more and more repos into older Linux versions as well (Armbian Linux 5.4, Ubuntu 20.04, ...), it makes sense to thinking about this. Probably this topic can be renamed like:
```
[FR] WireGuard support in case of builtin Linux module
```
or similar, to cover all such cases in a generic way.

We just did this with DietPi: https://github.com/MichaIng/DietPi/pull/3620/files
- Basically we check if any `/lib/modules/*/kernel/net/wireguard/wireguard.ko` is found being part of any installed package. If so, then it has not been build via DKMS or manually, hence no kernel headers are required but the `wireguard-tools` package only (on Debian/Ubuntu).
- It is not 100% failsafe and probably someone has a better idea. In theory the found `wireguard.ko` can be for a kernel that is not used by the system (anymore). E.g. it could be from a still installed kernel package but now a different kernel has been installed on top and replaced the /boot/(uz)Image (or whatever is loaded) that does not ship the WireGuard module.
- Even when comparing with `uname -r` one cannot be sure if a different Linux image has been put in place already but the current session still has an old one loaded.
- So we think that it generally can be assumed, if any `/lib/modules/*/kernel/net/wireguard/wireguard.ko` is shipped directly by a deb package, it can only come from a kernel package. And kernel packages usually setup themselves to be the loaded Linux image, there is rarely any other purpose. Even if the package would be upgraded as part of the install process, an update will very likely not drop a previously added `wireguard.ko`.

**Comment by onedr0p** [comment] 2020-08-01 21:24
If I force the install script to use wireguard it installs everything fine and works.

**Comment by stevoh6** [comment] 2020-08-31 19:41
> Chiming in to say if I force the install script to use wireguard it installs everything fine and works on Ubuntu 20.04-arm64
> 
> ```
> cat /etc/os-release
> NAME="Ubuntu"
> VERSION="20.04.1 LTS (Focal Fossa)"
> ID=ubuntu
> ID_LIKE=debian
> PRETTY_NAME="Ubuntu 20.04.1 LTS"
> VERSION_ID="20.04"
> HOME_URL="https://www.ubuntu.com/"
> SUPPORT_URL="https://help.ubuntu.com/"
> BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
> PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
> VERSION_CODENAME=focal
> UBUNTU_CODENAME=focal
> ```

I can confim, that it aproach is working. 

You can use my install.sh which contain only one change > add Ubuntu 20.04 into supported OS. 
https://github.com/stevoh6/pivpn/blob/master/auto_install/install.sh
https://github.com/stevoh6/pivpn/commit/6099ea34ca51e52cf57bbd931eea8040b760290a

P.S. use it carefully :-)
P.P.S. in my case it failed at this step "Installing wireguard-dkms.", so I give a try to install this packtage separatelly ` apt-get install  wireguard-dkms`, after that I run installer once again `./install.sh` and voila it work's :-)

**Comment by omgapuppy** [comment] 2020-09-02 13:06
@stevoh6 are you planning a PR?

**Comment by stevoh6** [comment] 2020-09-02 13:59
@omgapuppy it will be great if more people can confirm, that it works on their machines. I raised pull request so authors can review it.

**Comment by omgapuppy** [comment] 2020-09-02 15:34
Looks like further changes in `install.sh` are needed - specifically `askWhichVPN()` function.
The PR addresses the 20.04 part of this issue, but misses `arm64` in current form. Should be an easy enough change tho.
Adding `[ "$OSCN" = "focal" ]` *OR* conditional to the [install script L1101 in your PR](https://github.com/pivpn/pivpn/blob/6099ea34ca51e52cf57bbd931eea8040b760290a/auto_install/install.sh#L1101) _should_ do the trick. I tested your script with a hardcoded `arm64` against 20.04 on Pi3 & it worked a charm.

**Comment by orazioedoardo** [comment] 2020-09-03 13:18
This workaround has been submitted to the test branch, Ubuntu on Raspberry Pi should work when installing from test branch: https://github.com/pivpn/pivpn/wiki#testing

Does it work on the 32 bit (ARM) version of Ubuntu?

**Comment by omgapuppy** [comment] 2020-09-03 13:44
Haven't personally tested it on 32 bit, but I'm pretty sure it won't on older SoCs i.e Pi < v3 🤔

**Comment by menzo2003** [comment] 2020-09-03 15:33
There is an Arm32 version of 20.04

https://ubuntu.com/download/raspberry-pi

**Comment by omgapuppy** [comment] 2020-09-03 15:35
Wasn't aware, cheers :)

**Comment by menzo2003** [comment] 2020-09-03 16:26
It works great, on 20.04 ARM32

**Comment by orazioedoardo** [comment] 2020-09-14 15:19
Since this thread seems pretty active, I would be glad if you could try the (just updated) test branch. If you do, please report the distribution, version and cpu architecture.

**Comment by sh78** [comment] 2020-09-19 12:32
I had success today with `curl -L https://test.pivpn.io | TESTING= bash`. I stuck with the interactive installer's defaults, other than port and DNS.

Ubuntu 20.04.1 arm-64 (downloaded from https://ubuntu.com/download/raspberry-pi)
Raspberry Pi 4B

During a quick test with my phone over LTE, TCP is working as expected for both internal and external hosts.

**Comment by bportpat** [comment] 2020-09-25 10:09
`curl -L https://test.pivpn.io | TESTING= bash` work for me today. Interactive install with change to DNS

Ubuntu 20.04.1 arm-64
Raspberry Pi 3B

Quick test with my phone over LTE

**Closed** 2020-11-04 10:51 UTC
Labels: Fix in Test Branch
