### ISSUE TITLE
Need to install wirguard before running PiVPN

### ISSUE THREAD

**Issue by sidewinder94** [pivpn/pivpn#1239] opened 2021-02-03 12:39 UTC
## In raising this issue, I confirm the following: 

`{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting *is* directly related to the pivpn installer script.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pivpn/pivpn/wiki/FAQ), [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed), and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen)).

**Describe the bug**

On Debian 10 (ARM64) the install script does not ask me to choose which VPN service to install

**To Reproduce**

1. Clean Debian 10 (ARM64) installation
2. Run PiVPN installer script
3. Follow the steps

**Expected behavior**
The installer asks me to choose which VPN system I want to use and installs it.

**Desktop (please complete the following information):**
Not relevant, server installation does not complete

**Smartphone (please complete the following information):**
Not relevant, server installation does not complete

**Actual behaviour**
I do not get asked to choose the VPN service I want to use and the setups directly goes to the unattended upgrade setup.

**Additional context**

After the installer finished the following lines can be seen 

```
::: Checking for existing base files...
:::    Checking /usr/local/src/pivpn is a repo... OK!
:::     Updating repo in /usr/local/src/pivpn... done!
main: line 1140: [: : integer expression expected
main: line 1152: [: : integer expression expected
::: Install Complete...
```

**Comment by 4s3ti** [comment] 2021-02-04 21:07
Dear user, even though we love the fact you are using pivpn, the maintainers of this project keep answering the same thing over and over again.

They keep spending time not only on the project that makes your life so great but also on documentation that you not to read at all therefore this issue is being closed. 

Don't know why your issue got closed? 

You can start by reading here: https://www.pivpn.io/#contrib
And here: https://github.com/pivpn/pivpn/blob/master/README.md
And here: https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md

and the first lines on the issue template that appeared after you have pressed all those green buttons to open up this issue: 

```
<!-- 
# PiVPN Issue Template
PLEASE READ THIS TEMPLATE CAREFULLY BEFORE OPENING AN ISSUE! 
Any Issue opened that doesn't follow this template will be removed.
```

Still not happy? 

Feel free to express yourself but most likely our position won't change, and hopefully you have now learned how to open an issue anywhere in the opensource community! 


Wish you a great day, feel free to reopen this issue but this time make sure it follows the rules!

**Comment by sidewinder94** [comment] 2021-02-04 21:42
@4s3ti 
Might want to change that message a bit / check your documentation links.
The Issue documentation link in the readme.md is dead (https://github.com/pivpn/pivpn/blob/master/ISSUE_TEMPLATE.md) (error 404)
And moreover, no template was displayed by github when creating the issue.

I am fully willing to fill out a template, but it needs to be accessible and easily found, I needed to actually open 4 to 5 other issues (not closed) to find something that resembled a template.

**Comment by 4s3ti** [comment] 2021-02-04 23:01
Re-Opened, Thanks for understanding, for properly filling the template and actually for the feedback!! 

The issue template it is presented when you press the "new issue" button, you are given 3 choices and upon selecting it you are given a template to fill in. 

> And moreover, no template was displayed by GitHub when creating the issue (I think i followed a link from the main website being "https://github.com/pivpn/pivpn/issues/new" which does not display a choice).

This is actually interesting feedback, and it is actually here: https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md 

Will fix them ASAP, my apologies if my answer felt to rude but ... well ... you can imagine how many of those come around for me to feel the need of having a saved reply! :p

**Comment by 4s3ti** [comment] 2021-02-04 23:32
Dead and wrong links have been fixed: https://github.com/pivpn/pivpn/commit/b2b93de8dc30e5a6b3611c8f803a89eca0eb80db thanks for the feedback

**Comment by 4s3ti** [comment] 2021-02-04 23:57
The issue has been confirmed 

Tested on AWS t4g.micro instance:

```
root@ip-172-31-5-163:~# cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
root@ip-172-31-5-163:~# uname -a
Linux ip-172-31-5-163 4.19.0-13-arm64 #1 SMP Debian 4.19.160-2 (2020-11-28) aarch64 GNU/Linux

```


```
root@ip-172-31-5-163:~# curl -L https://install.pivpn.io | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   162  100   162    0     0   1514      0 --:--:-- --:--:-- --:--:--  1514
100 83358  100 83358    0     0   661k      0 --:--:-- --:--:-- --:--:--  661k
:::
::: You are root.
::: Hostname length OK
::: Verifying free disk space...
:::
::: Package Cache update is needed, running apt-get update -y ...
 done!
:::
::: Checking apt-get for upgraded packages.... done!
:::
::: Your system is up to date! Continuing with PiVPN installation...
:::    Checking for git... already installed!
:::    Checking for tar... already installed!
:::    Checking for wget... already installed!
:::    Checking for curl... already installed!
:::    Checking for grep... already installed!
:::    Checking for dnsutils... already installed!
:::    Checking for whiptail... already installed!
:::    Checking for net-tools... already installed!
:::    Checking for bsdmainutils... already installed!
:::    Checking for iptables-persistent... already installed!
::: Using User: admin
:::
::: Checking for existing base files...
:::    Checking /usr/local/src/pivpn is a repo... not found!
:::    Cloning https://github.com/pivpn/pivpn.git into /usr/local/src/pivpn... done!
main: line 1140: [: : integer expression expected
main: line 1152: [: : integer expression expected
::: Install Complete...
::: Restarting services...
:::    Checking for unattended-upgrades... already installed!
::: Setupfiles copied to /etc/pivpn//setupVars.conf
::: Installing scripts to /opt/pivpn...
main: line 2288: /etc/bash_completion.d/pivpn: No such file or directory
 done.
::: Flushing writes to disk...
::: done.
:::
root@ip-172-31-5-163:~# cat /etc/pivpn/setupVars.conf 
PLAT=Debian
OSCN=buster
USING_UFW=0
IPv4dev=ens5
install_user=admin
install_home=/home/admin
VPN=
pivpnDEV=
pivpnNET=
subnetClass=24
ALLOWED_IPS=""
UNATTUPG=1
INSTALLED_PACKAGES=()
root@ip-172-31-5-163:~# 
```


Will let @orazioedoardo chimp in as i think there was some talks involving this some time ago .. not entirely sure.

**Comment by orazioedoardo** [comment] 2021-02-05 17:34
I think this is caused by Debian ARM64 not matching any of these conditions: https://github.com/pivpn/pivpn/blob/b2b93de8dc30e5a6b3611c8f803a89eca0eb80db/auto_install/install.sh#L480-L489, so `$WIREGUARD_SUPPORT` is not set. Which packages did you need to install?

**Comment by sidewinder94** [comment] 2021-02-05 17:40
I did install the wireguard package, which in turn, as a dependency installed wireguard-tools.

For that to work, I also needed to add the backports repository into apt though.

**Comment by orazioedoardo** [comment] 2021-02-05 19:07
What about kernel headers?

**Comment by sidewinder94** [comment] 2021-02-05 21:06
I did not install it explicitely, and you'll find below the apt output when asked to install wireguard.


```
sudo apt install wireguard
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
  linux-image-5.9.0-0.bpo.5-cloud-arm64 linux-image-cloud-arm64 wireguard-tools
Suggested packages:
  linux-doc-5.9 debian-kernel-handbook openresolv | resolvconf
The following NEW packages will be installed:
  linux-image-5.9.0-0.bpo.5-cloud-arm64 linux-image-cloud-arm64 wireguard wireguard-tools
0 upgraded, 4 newly installed, 0 to remove and 0 not upgraded.
Need to get 16.7 MB of archives.
After this operation, 81.9 MB of additional disk space will be used.
Do you want to continue? [Y/n]
```

It seems headers were already a part of the distribution, an `apt list | grep headers` returned a list containing those:

```
linux-headers-4.19.0-11-all-arm64/stable 4.19.146-1 arm64
linux-headers-4.19.0-11-all/stable 4.19.146-1 arm64
linux-headers-4.19.0-11-arm64/stable 4.19.146-1 arm64
linux-headers-4.19.0-11-common-rt/stable 4.19.146-1 all
linux-headers-4.19.0-11-common/stable 4.19.146-1 all
linux-headers-4.19.0-11-rt-arm64/stable 4.19.146-1 arm64
linux-headers-4.19.0-13-all-arm64/stable 4.19.160-2 arm64
linux-headers-4.19.0-13-all/stable 4.19.160-2 arm64
linux-headers-4.19.0-13-arm64/stable 4.19.160-2 arm64
linux-headers-4.19.0-13-common-rt/stable 4.19.160-2 all
linux-headers-4.19.0-13-common/stable 4.19.160-2 all
linux-headers-4.19.0-13-rt-arm64/stable 4.19.160-2 arm64
linux-headers-4.19.0-14-all-arm64/stable 4.19.171-2 arm64
linux-headers-4.19.0-14-all/stable 4.19.171-2 arm64
linux-headers-4.19.0-14-arm64/stable 4.19.171-2 arm64
linux-headers-4.19.0-14-common-rt/stable 4.19.171-2 all
linux-headers-4.19.0-14-common/stable 4.19.171-2 all
linux-headers-4.19.0-14-rt-arm64/stable 4.19.171-2 arm64
linux-headers-5.9.0-0.bpo.5-arm64/buster-backports 5.9.15-1~bpo10+1 arm64
linux-headers-5.9.0-0.bpo.5-cloud-arm64/buster-backports 5.9.15-1~bpo10+1 arm64
linux-headers-5.9.0-0.bpo.5-common-rt/buster-backports 5.9.15-1~bpo10+1 all
linux-headers-5.9.0-0.bpo.5-common/buster-backports 5.9.15-1~bpo10+1 all
linux-headers-5.9.0-0.bpo.5-rt-arm64/buster-backports 5.9.15-1~bpo10+1 arm64
linux-headers-arm64/stable 4.19+105+deb10u9 arm64
linux-headers-cloud-arm64/buster-backports 5.9.15-1~bpo10+1 arm64
linux-headers-rt-arm64/stable 4.19+105+deb10u9 arm64
```

**Comment by sidewinder94** [comment] 2021-02-05 21:10
and `apt list --installed | grep headers` returns nothing

**Comment by 4s3ti** [comment] 2021-02-06 22:54
Yup can  confirm that installing wireguard with apt install -y wireguard will get it working and pivpn installs fine after that.

**Comment by orazioedoardo** [comment] 2021-02-11 12:41
I've installed a ARM64 VM of Debian 10 from [this ISO](http://cdimage.debian.org/cdimage/release/10.8.0/arm64/iso-cd/debian-10.8.0-arm64-xfce-CD-1.iso). After adding the Bullseye repo, the following packages are required to install wireguard:

```
$ sudo apt install wireguard
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  binutils binutils-aarch64-linux-gnu binutils-common build-essential cpp cpp-8 dirmngr dkms dpkg-dev fakeroot g++ g++-8 gcc gcc-8 gnupg gnupg-l10n gnupg-utils gpg gpg-agent gpg-wks-client gpg-wks-server
  gpgconf gpgsm libalgorithm-diff-perl libalgorithm-diff-xs-perl libalgorithm-merge-perl libasan5 libassuan0 libatomic1 libbinutils libc-dev-bin libc6-dev libcc1-0 libdpkg-perl libfakeroot
  libfile-fcntllock-perl libgcc-8-dev libgomp1 libisl19 libitm1 libksba8 liblsan0 libmpc3 libmpfr6 libnpth0 libstdc++-8-dev libtsan0 libubsan1 linux-libc-dev make manpages-dev patch pinentry-curses
  wireguard-dkms wireguard-tools
Suggested packages:
  binutils-doc cpp-doc gcc-8-locales dbus-user-session pinentry-gnome3 tor python3-apport menu debian-keyring gcc-8-doc libstdc++6-8-dbg gcc-multilib autoconf automake libtool flex bison gdb gcc-doc libgcc1-dbg
  libgomp1-dbg libitm1-dbg libatomic1-dbg libasan5-dbg liblsan0-dbg libtsan0-dbg libubsan1-dbg libmpx2-dbg libquadmath0-dbg parcimonie xloadimage scdaemon glibc-doc bzr libstdc++-8-doc make-doc ed diffutils-doc
  pinentry-doc openresolv | resolvconf
Recommended packages:
  linux-headers-686-pae | linux-headers-amd64 | linux-headers-generic | linux-headers
The following NEW packages will be installed:
  binutils binutils-aarch64-linux-gnu binutils-common build-essential cpp cpp-8 dirmngr dkms dpkg-dev fakeroot g++ g++-8 gcc gcc-8 gnupg gnupg-l10n gnupg-utils gpg gpg-agent gpg-wks-client gpg-wks-server
  gpgconf gpgsm libalgorithm-diff-perl libalgorithm-diff-xs-perl libalgorithm-merge-perl libasan5 libassuan0 libatomic1 libbinutils libc-dev-bin libc6-dev libcc1-0 libdpkg-perl libfakeroot
  libfile-fcntllock-perl libgcc-8-dev libgomp1 libisl19 libitm1 libksba8 liblsan0 libmpc3 libmpfr6 libnpth0 libstdc++-8-dev libtsan0 libubsan1 linux-libc-dev make manpages-dev patch pinentry-curses wireguard
  wireguard-dkms wireguard-tools
0 upgraded, 56 newly installed, 0 to remove and 0 not upgraded.
Need to get 50.3 MB of archives.
After this operation, 178 MB of additional disk space will be used.
Do you want to continue? [Y/n]
```

Surprisingly, kernel headers are not used to build the module. By the way since Bullseye is going to ship with kernel 5.10 with built-in WireGuard, I think it makes sense to just fix the script for now to stop the installation on arm64 Debian 10.

**Comment by sidewinder94** [comment] 2021-02-12 13:29
So If I understood correctly what was done in the PR, the Wireguard choice will only be proposed if it is known by apt?

Or should I still install Wireguard before running PiVPN next time I need a new VM?

**Comment by orazioedoardo** [comment] 2021-02-13 11:52
On Debian 10 arm64, WireGuard is not be suggested anymore in favor of OpenVPN. When Debian 11 will be available, WireGuard will automatically be available in virtue of this: https://github.com/pivpn/pivpn/blob/309c2cc7d505f4aab9d8c46497bbd96581f75389/auto_install/install.sh#L484

**Comment by danmoo117** [comment] 2021-03-20 16:39
Installing wireguard before running pivpn still does not offer the wireguard option. Is there a solution or workaround for this?

Cheers

**Comment by Revel8804** [comment] 2021-04-06 20:33
im guessing there is still not an answer to this one?

**Comment by 4s3ti** [comment] 2021-04-07 11:02
@Revel8804 the answer is here: 

> On Debian 10 arm64, WireGuard is not suggested anymore in favor of OpenVPN. When Debian 11 will be available, WireGuard will automatically be available in virtue of this:
> 
> https://github.com/pivpn/pivpn/blob/309c2cc7d505f4aab9d8c46497bbd96581f75389/auto_install/install.sh#L484

**Comment by p1r473** [comment] 2021-05-06 16:33
> I think this is caused by Debian ARM64 not matching any of these conditions:
> 
> https://github.com/pivpn/pivpn/blob/b2b93de8dc30e5a6b3611c8f803a89eca0eb80db/auto_install/install.sh#L480-L489
> 
> , so `$WIREGUARD_SUPPORT` is not set. Which packages did you need to install?

Agreed,
I had to `apt-get install wireguard` manually
I also had to `apt-get remove linux-image-rt-arm64` as this package had unmet dependencies

```

root@Harbormaster:~# apt --fix-broken install
Reading package lists... Done
Building dependency tree
Reading state information... Done
Correcting dependencies... Done
The following additional packages will be installed:
  linux-image-4.19.0-16-rt-arm64
Suggested packages:
  linux-doc-4.19 debian-kernel-handbook
Recommended packages:
  firmware-linux-free apparmor
The following NEW packages will be installed:
  linux-image-4.19.0-16-rt-arm64
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
5 not fully installed or removed.
Need to get 0 B/40.7 MB of archives.
After this operation, 226 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
(Reading database ... 82096 files and directories currently installed.)
Preparing to unpack .../linux-image-4.19.0-16-rt-arm64_4.19.181-1_arm64.deb ...
Unpacking linux-image-4.19.0-16-rt-arm64 (4.19.181-1) ...
dpkg: error processing archive /var/cache/apt/archives/linux-image-4.19.0-16-rt-                                                            arm64_4.19.181-1_arm64.deb (--unpack):
 cannot copy extracted data for './boot/vmlinuz-4.19.0-16-rt-arm64' to '/boot/vm                                                            linuz-4.19.0-16-rt-arm64.dpkg-new': failed to write (No space left on device)
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
W: Last kernel image has been removed, so removing the default symlinks
Errors were encountered while processing:
 /var/cache/apt/archives/linux-image-4.19.0-16-rt-arm64_4.19.181-1_arm64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)

root@Harbormaster:~# apt-get remove linux-image-rt-aem64
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package linux-image-rt-aem64
root@Harbormaster:~# apt-get remove linux-image-rt-arm64
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following packages will be REMOVED:
  linux-image-rt-arm64
0 upgraded, 0 newly installed, 1 to remove and 0 not upgraded.
5 not fully installed or removed.
After this operation, 18.4 kB disk space will be freed.
Do you want to continue? [Y/n] y
(Reading database ... 82096 files and directories currently installed.)
Removing linux-image-rt-arm64 (4.19+105+deb10u11) ...
Setting up dkms (2.6.1-4) ...
Setting up wireguard-dkms (1.0.20210219-1) ...
Loading new wireguard-1.0.20210219 DKMS files...
It is likely that 4.4.194 belongs to a chroot's host
Building for 4.19.0-16-rt-arm64 and 4.4.194
Module build for kernel 4.19.0-16-rt-arm64 was skipped since the
kernel headers for this kernel does not seem to be installed.
Module build for kernel 4.4.194 was skipped since the
kernel headers for this kernel does not seem to be installed.
Setting up wireguard-tools (1.0.20210223-1) ...
wg-quick.target is a disabled or a static unit, not starting it.
Setting up wireguard (1.0.20210223-1) ...
Processing triggers for man-db (2.8.5-2) ...
```

**Comment by p1r473** [comment] 2021-05-06 16:36
> Installing wireguard before running pivpn still does not offer the wireguard option. Is there a solution or workaround for this?
> 
> Cheers

Just run `apt-get install wireguard`
Now I am able to run command `wg`

**Comment by 4s3ti** [comment] 2021-05-06 19:38
@orazioedoardo should I add into the documentation that Wireguard is not being supported on Debian 10 and close this one?

**Comment by orazioedoardo** [comment] 2021-05-07 15:10
Debian 10 is indeed supported, but not on ARM64. I would suggest to be more specific here:

https://docs.pivpn.io/faq/#what-boardsoses-does-pivpn-support

> Most x86_64 (Intel and AMD) servers running a Debian or Ubuntu based distro.

**Closed** 2021-11-01 12:25 UTC
Labels: bug, Needs Investigation
