### ISSUE TITLE
Delete Client

### ISSUE THREAD

**Issue by johnBrereton** [pivpn/pivpn#569] opened 2018-08-01 13:26 UTC
Is there any way to completely remove a client so the device does not appear in the list.

**Comment by adrianharabula** [comment] 2018-08-01 13:34
Have you tried `pivpn -r`?

**Comment by jbrereton6** [comment] 2018-08-01 14:35
That just revokes the account I am looking to remove the account so it can not be seen on the list.

**Comment by vrlnx** [comment] 2020-11-11 07:25
I have same issue, it does not go away with `pivpn remove` nor `pivpn -r`

**Comment by orazioedoardo** [comment] 2020-11-11 13:17
@vrlnx Assuming we are talking about OpenVPN, that's not a bug. It's by design. The client is still there (revoked) because the server needs to know that the client is explicitly forbidden.

**Comment by vrlnx** [comment] 2020-12-02 01:42
@orazioedoardo - It's acctually wireguard installed, but I think this is on OpenVPN aswell. I see this as an issue, I don't think this is good to have as a "by-design" feature. I think this will bloat the pi.

**Comment by orazioedoardo** [comment] 2020-12-05 12:48
@vrlnx It it's wireguard, then it's a bug. If it's openvpn, then it's by openvpn public key infrastructure/certificate design, not PiVPN's design. There is no "solution" in such case.

**Comment by orazioedoardo** [comment] 2021-02-20 10:40
No replies in a while, closing... If you can reproduce the issue were a wireguard client can't be removed, open a new issue.

**Closed by orazioedoardo** 2021-02-20 10:40 UTC
Labels: Needs Investigation, enhancement
