### ISSUE TITLE
Changed the network interface from wlan0 to eth0

### ISSUE THREAD

**Issue by zzeesstt** [pivpn/pivpn#392] opened 2017-10-23 07:22 UTC
Hey guys
Help me please with this question.
Changed the network interface from wlan0 to eth0 and OpenVPN stopped working.
What it is necessary to edit in a manual mode, that all again earned?
I did not want to reinstall PiVpn.
Thx all.

**Comment by cfcolaco** [comment] 2017-10-26 21:22
1 - did eth0 kept the same IP Address from the wlan0?? IF NOT ... Change the port forwarding in your router... 

2 - Change the postrouting line in '/etc/iptables/rules.v4' to match the new interface , so instead of ' ... -o wlan0' you get '-o eth0'

and all should be fine!

**Comment by cfcolaco** [comment] 2017-10-30 21:02
@zzeesstt closing issue as no update on this .. please post here and I will reopen of the information provided was not effective. 

thank you

**Closed by cfcolaco** 2017-10-30 21:02 UTC

**Comment by VTcivil99** [comment] 2021-01-06 16:41
I have confirmed this worked for me.   In my case I had created my PiVPN while on wifi (wlan0) then later decided to plug it in to eth0 since it would live right next to my switch.    I used rfkill to turn off wifi.   VPN worked still but would not route internet traffic or local traffic.   After researching I knew iptables was the problem.   I tried to use iptables command line but I'm not experienced in that.    Then ultimately I found this posting and this worked updating the rule.v4 file.    I rebooted a couple times and the setting persisted and working.     Thanks 4s3ti.

**Comment by EDIflyer** [comment] 2022-03-01 00:20
Thanks so much for this @4s3ti - I previously found a tip re changing the iptables to deal with moving from wlan0 to eth0 but hadn't realised that wasn't persistent! Last rebooted months ago so when I did so today I recognised the issue but couldn't remember how I solved it!  Thanks to your advice I've now edited the rules.v4 and am back up and running again 🥳

**Comment by belveder79** [comment] 2023-02-24 16:36
worked also for me on PiZero... thx for solving this!
