### ISSUE TITLE
Tun0 no ip address until service restart

### ISSUE THREAD

**Issue by dcabro** [pivpn/pivpn#316] opened 2017-07-27 08:56 UTC
For some reason, ifconfig show no IP address for the tun0 interface. The client can connect but no traffic flows between the client and the server, and client cannot reach other computers on the network. 

After "systemctl restart openvpn" everything works fine. The tun0 gets the 10.8.0.1 address.  The raspberry pi device is on lan (ethernet) with static IP address given by the DHCP server (the router) with no lease expiry. 

tun0      Link encap:UNSPEC  HWaddr 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  
          inet6 addr: fe80::bf0b:1fab:2901:9d7c/64 Scope:Link
          UP POINTOPOINT RUNNING NOARP MULTICAST DYNAMIC  MTU:1500  Metric:1
          RX packets:6 errors:0 dropped:0 overruns:0 frame:0
          TX packets:51 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:100 
          RX bytes:402 (402.0 B)  TX bytes:2480 (2.4 KiB)

openvpn.log:

ue Jul 25 20:53:30 2017 OpenVPN 2.3.4 arm-unknown-linux-gnueabihf [SSL (OpenSSL)] [LZO] [EPOLL] [PKCS11] [MH] [IPv6] built on Jun 26 2017
Tue Jul 25 20:53:30 2017 library versions: OpenSSL 1.0.1t  3 May 2016, LZO 2.08
Tue Jul 25 20:53:30 2017 Control Channel Authentication: using '/etc/openvpn/easy-rsa/pki/ta.key' as a OpenVPN static key file
Tue Jul 25 20:53:30 2017 TUN/TAP device tun0 opened
Tue Jul 25 20:53:30 2017 do_ifconfig, tt->ipv6=0, tt->did_ifconfig_ipv6_setup=0
Tue Jul 25 20:53:30 2017 /sbin/ip link set dev tun0 up mtu 1500
Tue Jul 25 20:53:30 2017 /sbin/ip addr add dev tun0 10.8.0.1/24 broadcast 10.8.0.255
Tue Jul 25 20:53:30 2017 GID set to nogroup
Tue Jul 25 20:53:30 2017 UID set to nobody
Tue Jul 25 20:53:30 2017 UDPv4 link local (bound): [undef]
Tue Jul 25 20:53:30 2017 UDPv4 link remote: [undef]
Tue Jul 25 20:53:30 2017 Initialization Sequence Completed
Thu Jul 27 10:39:41 2017 REDACTED:26963 [REDACTED] Peer Connection Initiated with [AF_INET]REDACTED:26963
Thu Jul 27 10:39:41 2017 REDACTED/REDACTED:26963 MULTI_sva: pool returned IPv4=10.8.0.2, IPv6=(Not enabled)
Thu Jul 27 10:39:41 2017 REDACTED/REDACTED:26963 send_push_reply(): safe_cap=940

**Comment by cfcolaco** [comment] 2017-08-03 21:38
One thing that I don't understand is the issue itself because it seems a lot of information missing, right now for me the issue is solved, you restarted openvpn ( which is perfectly acceptable to do so every now and then ). 

this seems not to be directly related with PiVPN, so can you provide more details about this issue please so I can better help you with this? 

because so far what you are telling me is, that you had an issue and you solved it by restarting the openvpn and the logs don't show anything abnormal.

**Comment by dcabro** [comment] 2017-08-07 13:10
Which information is missing exactly? How do you mean "it is perfectly acceptable to restart the service every now and then" ? Are you saying that you are aware that problem exists and service need to be occasionally restarted to fix it? Or you mean it's ok for the service to stop working on its own without any apparent reason? Yes, I had an issue and solved it by restarting the service but since I was unable to find the root cause of the issue, and logs do not show anything useful, I was hoping to get some help here. Apparently I was wrong.

**Comment by cfcolaco** [comment] 2017-08-13 10:38
@dcabro don't get me wrong, but sometimes the services just need to be restarted or reloaded, because it hanged for some kind of reason that you can't find in the logs and without logs and so on, it's really hard to solve those issues, and the issue is purely related with OpenVPN not PiVPN script at all. 

it could have been a dependency that changed and the service just stopped working properly, it could have been a kernel update that caused the service to hang and need to be restarted, it could have been that the raspberryPi couldn't handle the traffic and the service crashed. 

Having to restart the service one time, it's not something to worry about, however, let's say if you have to restart it every week or more than one time in one week, then you probably will need to dig deeper and look better for what caused the service to stop. 

one thing that is really useful is to just do  `systemctl status openvpn` when the service is not working, it can give you a lot of useful information regarding what happened. 
Then if it gives you no info, you should start looking and thinking on what changes you made to the server, any updates? any configs? Which Packages does OpenVPN depend on? did any of them have changed meanwhile? or have any of them crashed or is giving any error in the logs?  ... That kind of things ... 
 but so far ... it seems no issue at all ... just an occasional "hang" that happens from time to time, due to any of things I just mentioned, and more. 

If you have any OpenVPN issue that it's not entirely related to PiVPN, feel free to come here and ask for help, fill the Issue form with all the info we ask, and if itś a similar case to this one try to give as many details as possible, considering what I have just told you. 
we will try to help you as much as we can, considering that we do this in our free time. 

but now, seems to me that this issue can be closed. 
so please @dcabro or @redfast00  please close the issue.

**Closed** 2017-08-13 10:46 UTC
