### ISSUE TITLE
[FR] Would like to install both WireGuard and OpenVPN on same Pi using PiVPN

### ISSUE THREAD

**Issue by rolandsmartin** [pivpn/pivpn#974] opened 2020-03-04 02:18 UTC
Is there any way to install both WireGuard and OpenVPN on the same Raspberry Pi using PIVPN? I have already installed and will continue to use OpenVPN. I would like to test out WireGuard on the same Pi. PiVPN makes things so simple, would really like to use it for both.

Any suggestions, manual edits I can make would be much appreciated.

Thanks for a great utility!

Roland

**Comment by orazioedoardo** [comment] 2020-03-04 08:00
Duplicate of https://github.com/pivpn/pivpn/issues/968. Will consider that.

**Closed by orazioedoardo** 2020-03-04 08:00 UTC
