### ISSUE TITLE
Problem regarding multiple port setup

### ISSUE THREAD

**Issue by cloudsurfer1** [pivpn/pivpn#447] opened 2018-01-14 16:35 UTC
# PiVPN Issue Template

Hello, I am running PIVPN successfully for about two weeks now via the standard settings UDP/1194. Unfortunately, I recently experienced some issues on a few WIFI hotspots while traveling, so I would like to run a second server on TCP/443 as a backup solution. I have searched this forum for a setup and found [this tutorial](https://github.com/pivpn/pivpn/issues/178) which I used step by step. However, I can not connect to the server via my devices. I already restarted openvpn and the RPI3 itself and entered a port forwarding for TCP443 on my router, but the issue still exist. While trouble shooting I saw that openvpn debug is not showing any second server at all, however I am not sure whether it should be shown there or not. Anyone who can help me out? If I missed out some important information I am sorry, please let me know I am new into this.

Thanks in advance!

  

## Console output of `pivpn debug`
```
::: Generating Debug Output
:::                                     :::
::              PiVPN Debug              ::
:::                                     :::
::      Latest Commit                    ::
:::                                     :::
commit 72b3dc24e7959e61e0233f2fde278bfc6498c114
Merge: 041d410 4e814fc
Author: redfast00 <redfast00@users.noreply.github.com>
Date:   Fri Dec 22 12:51:48 2017 +0100

    Merge pull request #432 from pivpn/cfcolaco-Patch

    Updated Issue Template
:::                                     :::
::      Recursive list of files in       ::
::      /etc/openvpn/easy-rsa/pki        ::
:::                                     :::
/etc/openvpn/easy-rsa/pki/:
ca.crt
crl.pem
Default.txt
dh2048.pem
index.txt
index.txt.attr
index.txt.attr.old
index.txt.old
issued
X1.ovpn
X1TCP.ovpn
XFire.ovpn
XMBP.ovpn
private
serial
serial.old
ta.key

/etc/openvpn/easy-rsa/pki/issued:
X1.crt
X1TCP.crt
XFire.crt
XMBP.crt
server_X.crt

/etc/openvpn/easy-rsa/pki/private:
ca.key
X1.key
X1TCP.key
XFire.key
XMBP.key
server_X.key
:::                                     :::
::      Output of /etc/pivpn/*           ::
:::                                     :::
:: START /etc/pivpn/DET_PLATFORM ::
Raspbian
:: END /etc/pivpn/DET_PLATFORM ::
:: START /etc/pivpn/INSTALL_PORT ::
1194
:: END /etc/pivpn/INSTALL_PORT ::
:: START /etc/pivpn/INSTALL_PROTO ::
udp
:: END /etc/pivpn/INSTALL_PROTO ::
:: START /etc/pivpn/INSTALL_USER ::
pi
:: END /etc/pivpn/INSTALL_USER ::
:: START /etc/pivpn/NO_UFW ::
1
:: END /etc/pivpn/NO_UFW ::
:: START /etc/pivpn/pivpnINTERFACE ::
eth0
:: END /etc/pivpn/pivpnINTERFACE ::
:: START /etc/pivpn/setupVars.conf ::
pivpnUser=pi
UNATTUPG=unattended-upgrades
pivpnInterface=eth0
IPv4dns=127.0.0.1
IPv4addr=192.168.11.15
IPv4gw=192.168.11.1
pivpnProto=udp
PORT=1194
ENCRYPT=2048
DOWNLOAD_DH_PARAM=false
PUBLICDNS=X.myfritz.net
OVPNDNS1=192.168.11.15
OVPNDNS2=
:: END /etc/pivpn/setupVars.conf ::
:::                                     :::
:: /etc/openvpn/easy-rsa/pki/Default.txt ::
:::                                     :::
client
dev tun
proto udp
remote X.myfritz.net 1194
resolv-retry infinite
nobind
persist-key
persist-tun
key-direction 1
remote-cert-tls server
tls-version-min 1.2
verify-x509-name server_X name
cipher AES-256-CBC
auth SHA256
comp-lzo
verb 1
:::                                     :::
::      Debug Output Complete            ::
:::                                     :::
:::
::: Debug output completed above.
::: Copy saved to /tmp/debug.txt
:::

```
## server_tcp_443.conf
```
dev tun_tcp_443
proto tcp
port 443
ca /etc/openvpn/easy-rsa/pki/ca.crt
cert /etc/openvpn/easy-rsa/pki/issued/server_X.crt
key /etc/openvpn/easy-rsa/pki/private/server_X.key
dh /etc/openvpn/easy-rsa/pki/dh2048.pem
topology subnet
server 10.9.0.0 255.255.255.0
# server and remote endpoints
ifconfig 10.9.0.1 10.9.0.2
# Add route to Client routing table for the OpenVPN Server
push "route 10.9.0.1 255.255.255.255"
# Add route to Client routing table for the OPenVPN Subnet
push "route 10.9.0.0 255.255.255.0"
# your local subnet
push "route 0.0.0.0 "
# Set your primary domain name server address for clients
push "dhcp-option DNS 192.168.11.15"
# 128.0.0.0/1 rather than 0.0.0.0/0. This has the benefit of
# overriding but not wiping out the original default gateway.
push "redirect-gateway def1"
client-to-client
keepalive 10 120
remote-cert-tls client
tls-version-min 1.2
tls-auth /etc/openvpn/easy-rsa/pki/ta.key 0
cipher AES-256-CBC
auth SHA256
comp-lzo
user nobody
group nogroup
persist-key
persist-tun
crl-verify /etc/openvpn/crl.pem
status /var/log/openvpn-status.log 20
status-version 3
log /var/log/openvpn.log
verb 1
# Generated for use by PiVPN.io







```
## X1TCP.ovpn
```
client
dev tun_tcp_443
proto tcp
remote X.myfritz.net 443
resolv-retry infinite
nobind
persist-key
persist-tun
key-direction 1
remote-cert-tls server
tls-version-min 1.2
verify-x509-name server_X name
cipher AES-256-CBC
auth SHA256
comp-lzo
verb 1
<ca>

```

## Console Output of `sudo iptables -t nat -S`
```
-P PREROUTING ACCEPT
-P INPUT ACCEPT
-P OUTPUT ACCEPT
-P POSTROUTING ACCEPT
-A POSTROUTING -s 10.8.0.0/24 -o eth0 -j MASQUERADE
-A POSTROUTING -s 10.9.0.0/24 -o eth0 -j MASQUERADE

```

## Console Output of `sudo iptables -S`
```
-P INPUT ACCEPT
-P FORWARD ACCEPT
-P OUTPUT ACCEPT

```

## output of `sudo netstat -uanp | grep openvpn`

```
udp        0      0 0.0.0.0:1194            0.0.0.0:*                           5699/openvpn
```

**Comment by cloudsurfer1** [comment] 2018-01-14 16:53
## log of OpenVPN Connect iOS App V1.2.5

```
2018-01-14 17:45:19 ----- OpenVPN Start -----
OpenVPN core 3.1.2 ios arm64 64-bit built on Jan  5 2018 23:09:59
2018-01-14 17:45:19 Frame=512/2048/512 mssfix-ctrl=1250
2018-01-14 17:45:19 UNUSED OPTIONS
4 [resolv-retry] [infinite]
5 [nobind]
6 [persist-key]
7 [persist-tun]
11 [verify-x509-name] [server_X] [name]
15 [verb] [1]

2018-01-14 17:45:19 EVENT: RESOLVE
2018-01-14 17:45:19 Contacting [XX.XX.XXX.XX]:443/TCP via TCP
2018-01-14 17:45:19 EVENT: WAIT
2018-01-14 17:45:19 Transport Error: TCP connect error on 'XXX.myfritz.net:443' ([XX.XX.XXX.XX]:443/TCP): SYSTEM/Connection refused
2018-01-14 17:45:19 Client terminated, restarting in 2000 ms...
2018-01-14 17:45:22 EVENT: RECONNECTING
2018-01-14 17:45:22 Contacting [XXXIP6XXX]:443/TCP via TCP
2018-01-14 17:45:22 EVENT: WAIT
2018-01-14 17:45:26 Transport Error: TCP connect error on 'XXX.myfritz.net:443' ([XXXIP6XXX]:443/TCP): SYSTEM/Connection refused
2018-01-14 17:45:26 Client terminated, restarting in 2000 ms...
2018-01-14 17:45:28 EVENT: RECONNECTING
2018-01-14 17:45:28 Contacting [XX.XX.XXX.XX]:443/TCP via TCP
2018-01-14 17:45:28 EVENT: WAIT
2018-01-14 17:45:28 Transport Error: TCP connect error on 'XXX.myfritz.net:443' ([XX.XX.XXX.XX]:443/TCP): SYSTEM/Connection refused
2018-01-14 17:45:28 Client terminated, restarting in 2000 ms...
2018-01-14 17:45:30 EVENT: RECONNECTING
2018-01-14 17:45:30 Contacting [XXXIP6XXX]:443/TCP via TCP
2018-01-14 17:45:30 EVENT: WAIT
2018-01-14 17:45:34 Transport Error: TCP connect error on 'XXX.myfritz.net:443' ([XXXIP6XXX]:443/TCP): SYSTEM/Connection refused
2018-01-14 17:45:34 Client terminated, restarting in 2000 ms...
2018-01-14 17:45:36 EVENT: RECONNECTING
2018-01-14 17:45:36 Contacting [XX.XX.XXX.XX]:443/TCP via TCP
2018-01-14 17:45:36 EVENT: WAIT
2018-01-14 17:45:36 Transport Error: TCP connect error on 'XXX.myfritz.net:443' ([XX.XX.XXX.XX]:443/TCP): SYSTEM/Connection refused
2018-01-14 17:45:36 Client terminated, restarting in 2000 ms...
2018-01-14 17:45:38 EVENT: RECONNECTING
2018-01-14 17:45:38 Contacting [XXXIP6XXX]:443/TCP via TCP
2018-01-14 17:45:38 EVENT: WAIT
2018-01-14 17:45:42 Transport Error: TCP connect error on 'XXX.myfritz.net:443' ([XXXIP6XXX]:443/TCP): SYSTEM/Connection refused

```

**Comment by orazioedoardo** [comment] 2018-01-15 08:08
Restart the server if you didn't: `sudo systemctl restart openvpn`

Then check whether it is listening `sudo netstat -antp | grep openvpn`

**Comment by cloudsurfer1** [comment] 2018-01-15 13:59
> Restart the server if you didn't: sudo systemctl restart openvpn

Done it again via your command (I rebooted the whole RPi3 before), unfortunately it is still not working.



> Then check whether it is listening: sudo netstat -antp | grep openvpn

Nothing is happening if I enter this command, but I searched for this kind of syntax and found  "sudo netstat -antup | grep openvpn" which results in the following output: 

```
pi@raspberrypi:~ $ sudo netstat -antup | grep openvpn
udp        0      0 0.0.0.0:1194            0.0.0.0:*                           18158/openvpn
```

**Comment by orazioedoardo** [comment] 2018-01-15 14:08
It seems to be listening on udp/1194 only. Post the server log as well.

**Comment by cloudsurfer1** [comment] 2018-01-15 17:45
## Console output of `grep VPN /var/log/syslog`
```
Jan 15 14:37:47 raspberrypi systemd[1]: Stopped OpenVPN service.
Jan 15 14:37:47 raspberrypi systemd[1]: Stopping OpenVPN service...
Jan 15 14:37:47 raspberrypi systemd[1]: Starting OpenVPN service...
Jan 15 14:37:47 raspberrypi systemd[1]: Stopping OpenVPN connection to server...
Jan 15 14:37:47 raspberrypi systemd[1]: Starting OpenVPN connection to server_tcp443...
Jan 15 14:37:47 raspberrypi systemd[1]: Started OpenVPN service.
Jan 15 14:37:47 raspberrypi systemd[1]: Stopped OpenVPN connection to server.
Jan 15 14:37:47 raspberrypi systemd[1]: Starting OpenVPN connection to server...
Jan 15 14:37:47 raspberrypi systemd[1]: Failed to start OpenVPN connection to server_tcp443.
Jan 15 14:37:47 raspberrypi systemd[1]: Started OpenVPN connection to server.

```

The logs shows "server_tcp443..." while my conf file is named "server_tcp_443.conf", so I renamed it to "server_tcp443.conf". It successfully connects now, thanks! However, even if the App shows that I am connected, I still cant access my local network nor the internet. But this seems to be a new issue. My first config UDP/1194 still works like a charm.

Thats how the log looks like now:
## Console output of `grep VPN /var/log/syslog`
```
Jan 15 15:26:05 raspberrypi systemd[1]: Stopped OpenVPN service.
Jan 15 15:26:05 raspberrypi systemd[1]: Stopping OpenVPN service...
Jan 15 15:26:05 raspberrypi systemd[1]: Starting OpenVPN service...
Jan 15 15:26:05 raspberrypi systemd[1]: Stopping OpenVPN connection to server...
Jan 15 15:26:05 raspberrypi systemd[1]: Starting OpenVPN connection to server_tcp443...
Jan 15 15:26:05 raspberrypi systemd[1]: Started OpenVPN service.
Jan 15 15:26:05 raspberrypi systemd[1]: Started OpenVPN connection to server_tcp443.
Jan 15 15:26:05 raspberrypi systemd[1]: Stopped OpenVPN connection to server.
Jan 15 15:26:05 raspberrypi systemd[1]: Starting OpenVPN connection to server...
Jan 15 15:26:05 raspberrypi systemd[1]: Started OpenVPN connection to server.
Jan 15 15:26:46 raspberrypi systemd[1]: Stopped OpenVPN service.
Jan 15 15:26:46 raspberrypi systemd[1]: Stopping OpenVPN service...
Jan 15 15:26:46 raspberrypi systemd[1]: Starting OpenVPN service...
Jan 15 15:26:46 raspberrypi systemd[1]: Stopping OpenVPN connection to server...
Jan 15 15:26:46 raspberrypi systemd[1]: Stopping OpenVPN connection to server_tcp443...
Jan 15 15:26:46 raspberrypi systemd[1]: Started OpenVPN service.
Jan 15 15:26:46 raspberrypi systemd[1]: Stopped OpenVPN connection to server_tcp443.
Jan 15 15:26:46 raspberrypi systemd[1]: Starting OpenVPN connection to server_tcp443...
Jan 15 15:26:46 raspberrypi systemd[1]: Started OpenVPN connection to server_tcp443.
Jan 15 15:26:46 raspberrypi systemd[1]: Stopped OpenVPN connection to server.
Jan 15 15:26:46 raspberrypi systemd[1]: Starting OpenVPN connection to server...
Jan 15 15:26:46 raspberrypi systemd[1]: Started OpenVPN connection to server.
```

and the OpenVPN iOS App log:
```
2018-01-15 18:30:48 ----- OpenVPN Start -----
OpenVPN core 3.1.2 ios arm64 64-bit built on Jan  5 2018 23:09:59
2018-01-15 18:30:48 Frame=512/2048/512 mssfix-ctrl=1250
2018-01-15 18:30:48 UNUSED OPTIONS
4 [resolv-retry] [infinite]
5 [nobind]
6 [persist-key]
7 [persist-tun]
11 [verify-x509-name] [server_X] [name]
15 [verb] [1]

2018-01-15 18:30:48 EVENT: RESOLVE
2018-01-15 18:30:48 Contacting [XXIP4XX]:443/TCP via TCP
2018-01-15 18:30:48 EVENT: WAIT
2018-01-15 18:30:52 Transport Error: TCP connect error on 'X.myfritz.net:443' ([XXIP4XX]:443/TCP): SYSTEM/Connection refused
2018-01-15 18:30:52 Client terminated, restarting in 2000 ms...
2018-01-15 18:30:54 EVENT: RECONNECTING
2018-01-15 18:30:54 Contacting [XXIP4XX]:443/TCP via TCP
2018-01-15 18:30:54 EVENT: WAIT
2018-01-15 18:30:55 Connecting to [X.myfritz.net]:443 (XXIP4XX) via TCPv4
2018-01-15 18:30:55 EVENT: CONNECTING
2018-01-15 18:30:55 Tunnel Options:V4,dev-type tun,link-mtu 1572,tun-mtu 1500,proto TCPv4_CLIENT,comp-lzo,keydir 1,cipher AES-256-CBC,auth SHA256,keysize 256,tls-auth,key-method 2,tls-client
2018-01-15 18:30:55 Creds: UsernameEmpty/PasswordEmpty
2018-01-15 18:30:55 Peer Info:
IV_GUI_VER=net.openvpn.connect.ios 1.2.5-1
IV_VER=3.1.2
IV_PLAT=ios
IV_LZO=1
IV_AUTO_SESS=1

2018-01-15 18:30:55 VERIFY OK : depth=1
cert. version    : 3
serial number    : AB:35:77:D3:5B:0C:B7:76
issuer name      : CN=ChangeMe
subject name      : CN=ChangeMe
issued  on        : 2018-01-05 23:10:29
expires on        : 2028-01-03 23:10:29
signed using      : RSA with SHA-256
RSA key size      : 2048 bits
basic constraints : CA=true
key usage        : Key Cert Sign, CRL Sign

2018-01-15 18:30:55 VERIFY OK : depth=0
cert. version    : 3
serial number    : 01
issuer name      : CN=ChangeMe
subject name      : CN=server_X
issued  on        : 2018-01-05 23:10:37
expires on        : 2028-01-03 23:10:37
signed using      : RSA with SHA-256
RSA key size      : 2048 bits
basic constraints : CA=false
key usage        : Digital Signature, Key Encipherment
ext key usage    : TLS Web Server Authentication

2018-01-15 18:30:55 SSL Handshake: TLSv1.2/TLS-DHE-RSA-WITH-AES-256-CBC-SHA
2018-01-15 18:30:55 Session is ACTIVE
2018-01-15 18:30:55 EVENT: GET_CONFIG
2018-01-15 18:30:55 Sending PUSH_REQUEST to server...
2018-01-15 18:30:55 OPTIONS:
0 [route] [10.9.0.1] [255.255.255.255]
1 [route] [10.9.0.0] [255.255.255.0]
2 [route] [0.0.0.0]
3 [dhcp-option] [DNS] [192.168.11.15]
4 [redirect-gateway] [def1]
5 [route-gateway] [10.9.0.1]
6 [topology] [subnet]
7 [ping] [10]
8 [ping-restart] [120]
9 [ifconfig] [10.9.0.2] [255.255.255.0]

2018-01-15 18:30:55 PROTOCOL OPTIONS:
  cipher: AES-256-CBC
  digest: SHA256
  compress: LZO
  peer ID: -1
2018-01-15 18:30:55 EVENT: ASSIGN_IP
2018-01-15 18:30:55 NIP: preparing TUN network settings
2018-01-15 18:30:55 NIP: init TUN network settings with endpoint: XXIP4XX
2018-01-15 18:30:55 NIP: adding IPv4 address to network settings 10.9.0.2/255.255.255.0
2018-01-15 18:30:55 NIP: adding (included) IPv4 route 10.9.0.1/32
2018-01-15 18:30:55 NIP: adding (included) IPv4 route 10.9.0.0/24
2018-01-15 18:30:55 NIP: adding (included) IPv4 route 0.0.0.0/32
2018-01-15 18:30:55 NIP: redirecting all IPv4 traffic to TUN interface
2018-01-15 18:30:55 NIP: adding DNS 192.168.11.15
2018-01-15 18:30:55 Connected via NetworkExtensionTUN
2018-01-15 18:30:55 LZO-ASYM init swap=0 asym=0
2018-01-15 18:30:55 EVENT: CONNECTED @X.myfritz.net:443 (XXIP4XX) via /TCPv4 on NetworkExtensionTUN/10.9.0.2/ gw=[/]
2018-01-15 18:31:22 OS Event: SLEEP
2018-01-15 18:31:22 Raw stats on disconnect:
  BYTES_IN : 13978
  BYTES_OUT : 6206
  PACKETS_IN : 24
  PACKETS_OUT : 32
  TUN_BYTES_IN : 2091
  TUN_BYTES_OUT : 8935
  TUN_PACKETS_IN : 21
  TUN_PACKETS_OUT : 18
  TCP_CONNECT_ERROR : 1
  N_RECONNECT : 1
2018-01-15 18:31:22 Performance stats on disconnect:
  CPU usage (microseconds): 225753
  Tunnel compression ratio (uplink): 2.96796
  Tunnel compression ratio (downlink): 1.56441
  Network bytes per CPU second: 89407
  Tunnel bytes per CPU second: 48840
2018-01-15 18:31:22 EVENT: PAUSE
2018-01-15 18:31:23 OS Event: WAKEUP
2018-01-15 18:31:26 RESUME TEST: Internet:ReachableViaWWAN/WR t------
2018-01-15 18:31:26 STANDARD RESUME
2018-01-15 18:31:26 EVENT: RESUME
2018-01-15 18:31:26 EVENT: RECONNECTING
2018-01-15 18:31:26 Contacting [XXIP4XX]:443/TCP via TCP
2018-01-15 18:31:26 EVENT: WAIT
2018-01-15 18:31:26 Connecting to [X.myfritz.net]:443 (XXIP4XX) via TCPv4
2018-01-15 18:31:26 OS Event: SLEEP
2018-01-15 18:31:26 EVENT: PAUSE
2018-01-15 18:31:27 OS Event: WAKEUP
2018-01-15 18:31:30 RESUME TEST: Internet:ReachableViaWWAN/WR t------
2018-01-15 18:31:30 STANDARD RESUME
2018-01-15 18:31:30 EVENT: RESUME
2018-01-15 18:31:30 EVENT: RECONNECTING
2018-01-15 18:31:30 Contacting [XXIP4XX]:443/TCP via TCP
2018-01-15 18:31:30 EVENT: WAIT
2018-01-15 18:31:30 OS Event: SLEEP
2018-01-15 18:31:30 EVENT: PAUSE
2018-01-15 18:32:13 OS Event: WAKEUP
2018-01-15 18:32:16 RESUME TEST: Internet:ReachableViaWWAN/WR t------
2018-01-15 18:32:16 STANDARD RESUME
2018-01-15 18:32:16 EVENT: RESUME
2018-01-15 18:32:16 EVENT: RECONNECTING
2018-01-15 18:32:16 Contacting [XXIP4XX]:443/TCP via TCP
2018-01-15 18:32:16 EVENT: WAIT
2018-01-15 18:32:16 Connecting to [X.myfritz.net]:443 (XXIP4XX) via TCPv4
2018-01-15 18:32:16 EVENT: CONNECTING
2018-01-15 18:32:16 Tunnel Options:V4,dev-type tun,link-mtu 1572,tun-mtu 1500,proto TCPv4_CLIENT,comp-lzo,keydir 1,cipher AES-256-CBC,auth SHA256,keysize 256,tls-auth,key-method 2,tls-client
2018-01-15 18:32:16 Creds: UsernameEmpty/PasswordEmpty
2018-01-15 18:32:16 Peer Info:
IV_GUI_VER=net.openvpn.connect.ios 1.2.5-1
IV_VER=3.1.2
IV_PLAT=ios
IV_LZO=1
IV_AUTO_SESS=1

2018-01-15 18:32:17 VERIFY OK : depth=1
cert. version    : 3
serial number    : AB:35:77:D3:5B:0C:B7:76
issuer name      : CN=ChangeMe
subject name      : CN=ChangeMe
issued  on        : 2018-01-05 23:10:29
expires on        : 2028-01-03 23:10:29
signed using      : RSA with SHA-256
RSA key size      : 2048 bits
basic constraints : CA=true
key usage        : Key Cert Sign, CRL Sign

2018-01-15 18:32:17 VERIFY OK : depth=0
cert. version    : 3
serial number    : 01
issuer name      : CN=ChangeMe
subject name      : CN=server_X
issued  on        : 2018-01-05 23:10:37
expires on        : 2028-01-03 23:10:37
signed using      : RSA with SHA-256
RSA key size      : 2048 bits
basic constraints : CA=false
key usage        : Digital Signature, Key Encipherment
ext key usage    : TLS Web Server Authentication

2018-01-15 18:32:17 SSL Handshake: TLSv1.2/TLS-DHE-RSA-WITH-AES-256-CBC-SHA
2018-01-15 18:32:17 Session is ACTIVE
2018-01-15 18:32:17 EVENT: GET_CONFIG
2018-01-15 18:32:17 Sending PUSH_REQUEST to server...
2018-01-15 18:32:17 OPTIONS:
0 [route] [10.9.0.1] [255.255.255.255]
1 [route] [10.9.0.0] [255.255.255.0]
2 [route] [0.0.0.0]
3 [dhcp-option] [DNS] [192.168.11.15]
4 [redirect-gateway] [def1]
5 [route-gateway] [10.9.0.1]
6 [topology] [subnet]
7 [ping] [10]
8 [ping-restart] [120]
9 [ifconfig] [10.9.0.2] [255.255.255.0]

2018-01-15 18:32:17 PROTOCOL OPTIONS:
  cipher: AES-256-CBC
  digest: SHA256
  compress: LZO
  peer ID: -1
2018-01-15 18:32:17 EVENT: ASSIGN_IP
2018-01-15 18:32:17 NIP: preparing TUN network settings
2018-01-15 18:32:17 NIP: init TUN network settings with endpoint: XXIP4XX
2018-01-15 18:32:17 NIP: adding IPv4 address to network settings 10.9.0.2/255.255.255.0
2018-01-15 18:32:17 NIP: adding (included) IPv4 route 10.9.0.1/32
2018-01-15 18:32:17 NIP: adding (included) IPv4 route 10.9.0.0/24
2018-01-15 18:32:17 NIP: adding (included) IPv4 route 0.0.0.0/32
2018-01-15 18:32:17 NIP: redirecting all IPv4 traffic to TUN interface
2018-01-15 18:32:17 NIP: adding DNS 192.168.11.15
2018-01-15 18:32:17 Connected via NetworkExtensionTUN
2018-01-15 18:32:17 LZO-ASYM init swap=0 asym=0
2018-01-15 18:32:17 EVENT: CONNECTED @X.myfritz.net:443 (XXIP4XX) via /TCPv4 on NetworkExtensionTUN/10.9.0.2/ gw=[/]
```

**Comment by orazioedoardo** [comment] 2018-01-15 18:58
I forgot to specify which log I asked you for, it’s `/var/log/openvpn.log`.

Attempt a connection both on 1194/upd and then on 443/tcp, then paste it here.

**Comment by cloudsurfer1** [comment] 2018-01-15 21:48
## Console output of `/var/log/openvpn.log`
```
Mon Jan 15 22:31:32 2018 TCP connection established with [AF_INET]80.187.118.33:17230
Mon Jan 15 22:31:33 2018 80.187.118.33:17230 peer info: IV_GUI_VER=net.openvpn.connect.ios_1.2.5-1
Mon Jan 15 22:31:33 2018 80.187.118.33:17230 peer info: IV_VER=3.1.2
Mon Jan 15 22:31:33 2018 80.187.118.33:17230 peer info: IV_PLAT=ios
Mon Jan 15 22:31:33 2018 80.187.118.33:17230 peer info: IV_LZO=1
Mon Jan 15 22:31:33 2018 80.187.118.33:17230 peer info: IV_AUTO_SESS=1
Mon Jan 15 22:31:33 2018 80.187.118.33:17230 [X1TCP] Peer Connection Initiated with [AF_INET]80.187.118.33:17230
Mon Jan 15 22:31:33 2018 MULTI_sva: pool returned IPv4=10.9.0.2, IPv6=(Not enabled)
Mon Jan 15 22:32:34 2018 X1TCP/80.187.118.33:17230 Connection reset, restarting [0]
Mon Jan 15 22:34:05 2018 TCP connection established with [AF_INET]192.168.11.33:55667
Mon Jan 15 22:34:05 2018 192.168.11.33:55667 WARNING: Bad encapsulated packet length from peer (5635), which must be > 0 and <= 1627 -- please ensure that --tun-mtu or --link-mtu is equal on both peers -- this condition could also indicate a possible active attack on the TCP link -- [Attempting restart...]
Mon Jan 15 22:34:05 2018 192.168.11.33:55667 Connection reset, restarting [0]
Mon Jan 15 22:34:13 2018 TCP connection established with [AF_INET]192.168.11.33:55684
Mon Jan 15 22:35:14 2018 192.168.11.33:55684 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
Mon Jan 15 22:35:14 2018 192.168.11.33:55684 TLS Error: TLS handshake failed
Mon Jan 15 22:35:14 2018 192.168.11.33:55684 Fatal TLS error (check_tls_errors_co), restarting

```

"WARNING: Bad encapsulated packet length from peer (5635), which must be > 0 and <= 1627 -- please ensure that --tun-mtu or --link-mtu is equal on both peers -- this condition could also indicate a possible active attack on the TCP link -- [Attempting restart...]" 

Looks like an issue here doesnt it?

Beside of that, the log shows "TCP connection established" when I were already on the UDP/1194 profile. (I started with TCP/443, changing to UDP/1194 at 22:33:30 which doesnt fit to the time stamp either)

**Comment by orazioedoardo** [comment] 2018-01-15 22:24
Seems like the issue is related to the TCP tunnel, according to [this](https://forums.openvpn.net/viewtopic.php?t=10455) post, it could be a random bot probing the port (it’s common on the internet).

Try moving to a high TCP port like 12345 (I know, this may defeat your initial purpose). If it doesn’t work than the TCP overhead is my next guess.

**Comment by cloudsurfer1** [comment] 2018-01-15 22:31
I'll check that tomorrow, thank you very much for your help orazioedoardo!

P.S. removed, thanks

**Comment by cloudsurfer1** [comment] 2018-01-29 15:57
Sorry for delay, I was quite busy recently. I switched to Port TCP/12345 as suggested by @orazioedoardo, resulting in the same issue like before. Like on TCP/443, I can connect to the server and even browse the web and access my pi-Hole for a short time, however once I start a download or a speed test, the speed is fine in the beginning (approx. 8Mbps), quickly reducing towards 0Mbps till the speed test finally fails. I am testing via my phone on LTE with a really good performance (80/13Mbps), so the connection shouldn't be the problem. Thereafter I can not access any websites or local IPs anymore until I restart the connection. Is that an indicator for the TCP overhead that you mentioned before?

**Comment by orazioedoardo** [comment] 2018-01-29 16:41
Are you getting the same `Connection reset` and `Bad encapsulated packet length` even on a different TCP port? Because if that’s the case it could actually be a MTU issue (though in this case I would not know how to set the exact value).

**Comment by d0nlab** [comment] 2018-01-29 22:11
Your issue seems similar to the description in the comments in this 🐜. BTW I’m having the same problem  via TCP 443. Over UDP 1194 is fine.  OpenVPN 1.2.6 for iOS on 11.2.5. 

https://forums.openvpn.net/viewtopic.php?f=36&t=25627

https://www.reddit.com/r/OpenVPN/comments/7s4xnf/problems_after_updating_to_126_app_ios/?st=JD0RNE7J&sh=cf5f5723

**Comment by cloudsurfer1** [comment] 2018-01-30 19:47
> Are you getting the same Connection reset and Bad encapsulated packet length even on a different TCP port? Because if that’s the case it could actually be a MTU issue (though in this case I would not know how to set the exact value).

No, but I experience the same connection problems like on 443 (on my iPhone). But I think thats because OpenVPN is not listining on TCP443 in this config.


> Your issue seems similar to the description in the comments in this 🐜. BTW I’m having the same problem  via TCP 443. Over UDP 1194 is fine.  OpenVPN 1.2.6 for iOS on 11.2.5.

Thanks, I tried to make it work on my Android tablet and it actually seems to work now.

However, I think I found a reason for the "Bad encapsulated packet length from peer" error message. I am running Pi-Hole on my Rp3 as well, the IP of (the same) Rp3 is listed as local DNS server in the FritzBox settings. It seems like whenever PiVPN/OpenVPN is listining on TCP 443, all (https?) requests are not just forwarded to the Pi-Hole, but also to the OpenVPN server, resulting in this error message. I found it out while troubleshooting, when I had seen that the OpenVPN.log file size is increasing fast even there was no active connection to a client. After removing the Rp3 IP in the FritzBox settings, the error messages were gone. However, I would love to use both, Pi-Hole and PiVPN. Is there any work around to prevent Pi-Hole traffic beeing mixed up with PiVPN traffic? Or whats about just deactivating the OpenVPN server log?

**Comment by orazioedoardo** [comment] 2018-01-30 20:37
I think you could be right! When a client asks pihole to resolve a host it may try to fetch the ad on port 443 on the pi, in the usual scenario it won’t work since there is no web server.
However since you have openvpn listening on port 443 the client tries to download the ad but the request doesn’t make sense to openvpn. Not sure why you are experiencing problems on a different port too. By the way pivpn works fine with pihole on the standard udp port setup.

**Comment by cloudsurfer1** [comment] 2018-01-30 21:20
I think there are two different problems, the first TCP in general when I connect via the OpenVPN iOS App V1.2.6 (via Android it works, tho) which might be solved with the next App release and on the other hand the error messages created because of my Pi-Hole/PiVPN setup. I think these messages have no impact on the actual VPN connection, they are just "spamming" my OpenVPN.log file.

**Comment by d0nlab** [comment] 2018-01-31 06:30
Yes, two problems. iOS 1.2.5/1.2.6 app doesn’t like TCP 443 at the moment. 

Bad encapsulation is a cosmetic side effect of listening over 443. Don’t see a way around that as I need 443 for networks which block 1194.

**Comment by d0nlab** [comment] 2018-01-31 19:24
https://github.com/pi-hole/pi-hole/wiki/OpenVPN-server:-Firewall-configuration-(using-iptables)

**Comment by cloudsurfer1** [comment] 2018-02-03 16:50
With iOS app V1.2.7 the problems with TCP 443 are actually gone, thank you. 

I could solve the Bad encapsulation issues caused by the Pi-Hole with a work around. While the clients are using TCP 443, the OpenVPN server is listening on another port. The forwarding between 443 and the other port is realized by my FritzBox.

**Comment by d0nlab** [comment] 2018-02-03 18:33
Same for me. TCP 443 is working again reliably after 1.2.7 update. Still getting bad encapsulation errors in logs. So you think if I listen over say... 5000 for example and set my router to forward 443 from outside to 5000 inside that will work?

**Comment by orazioedoardo** [comment] 2018-02-04 09:01
@d0nlab The "bad encapsulation" message could be a result of HTTPS traffic being sent from random bots to port 443, which has nothing to do with openvpn. Moving to a non standard port reduces the likelihood of such "internet noise".

**Comment by d0nlab** [comment] 2018-02-04 20:55
@Piero, agree that’s the case but strange thing is the majority of my logs with this error come from internal clients on my network. So I was thing of changing my internal port but leave 443 from outside.

**Closed** 2019-04-26 20:14 UTC
