### ISSUE TITLE
Installation Issue (Failing)

### ISSUE THREAD

**Issue by GeekNathan** [pivpn/pivpn#173] opened 2016-12-25 06:26 UTC
# PiVPN Issue Template

## Console output of `curl install.pivpn.io | bash`
```
pi@raspberrypi:~ $ curl -L https://install.pivpn.io | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   178  100   178    0     0    155      0  0:00:01  0:00:01 --:--:--   155
100 43489  100 43489    0     0  23923      0  0:00:01  0:00:01 --:--:-- 23923
:::
::: sudo will be used for the install.
::: Verifying free disk space...
:::
::: Checking apt-get for upgraded packages.... done!
:::
::: Your system is up to date! Continuing with PiVPN installation...
debconf: DbDriver "passwords" warning: could not open /var/cache/debconf/passwords.dat: Permission denied
::: Using interface: eth0
bash: line 278: nslookup: command not found
::: Static IP already configured.
::: Using User: pi
:::
::: Stopping OpenVPN service...Failed to stop openvpn.service: Unit openvpn.service not loaded.
 done.
:::
::: Checking for existing base files...
:::    Checking /etc/.pivpn is a repo...:::    Cloning https://github.com/pivpn/pivpn.git into /etc/.pivpn...sudo: git: command not found
 done!
:::
::: Installing scripts to /opt/pivpn...cp: cannot stat ‘/etc/.pivpn/scripts/makeOVPN.sh’: No such file or directory
cp: cannot stat ‘/etc/.pivpn/scripts/clientStat.sh’: No such file or directory
cp: cannot stat ‘/etc/.pivpn/scripts/listOVPN.sh’: No such file or directory
cp: cannot stat ‘/etc/.pivpn/scripts/removeOVPN.sh’: No such file or directory
cp: cannot stat ‘/etc/.pivpn/scripts/uninstall.sh’: No such file or directory
cp: cannot stat ‘/etc/.pivpn/scripts/pivpnDebug.sh’: No such file or directory
cp: cannot stat ‘/etc/.pivpn/scripts/fix_iptables.sh’: No such file or directory
chmod: cannot access ‘/opt/pivpn/makeOVPN.sh’: No such file or directory
chmod: cannot access ‘/opt/pivpn/clientStat.sh’: No such file or directory
chmod: cannot access ‘/opt/pivpn/listOVPN.sh’: No such file or directory
chmod: cannot access ‘/opt/pivpn/removeOVPN.sh’: No such file or directory
chmod: cannot access ‘/opt/pivpn/uninstall.sh’: No such file or directory
chmod: cannot access ‘/opt/pivpn/pivpnDebug.sh’: No such file or directory
chmod: cannot access ‘/opt/pivpn/fix_iptables.sh’: No such file or directory
cp: cannot stat ‘/etc/.pivpn/pivpn’: No such file or directory
chmod: cannot access ‘/usr/local/bin/pivpn’: No such file or directory
cp: cannot stat ‘/etc/.pivpn/scripts/bash-completion’: No such file or directory
bash: line 404: /etc/bash_completion.d/pivpn: No such file or directory
 done.
::: Using protocol: udp
tar: /etc/openvpn: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
chown: cannot access ‘/etc/openvpn/easy-rsa’: No such file or directory
mkdir: cannot create directory ‘/etc/openvpn/easy-rsa/pki’: No such file or directory
tee: /etc/openvpn/easy-rsa/vars: No such file or directory
bash: line 814: cd: /etc/openvpn/easy-rsa: No such file or directory
Failed to execute operation: No such file or directory
Failed to start openvpn.service: Unit openvpn.service failed to load: No such file or directory.

Rebooting system...

Broadcast message from root@raspberrypi (Sun 2016-12-25 06:02:28 UTC):

The system is going down for reboot NOW!

::: Install Complete...
pi@raspberrypi:~ $

```

## Console output of `pivpn debug`
```
sudo pivpn debug
cat: /etc/pivpn/NO_UFW: No such file or directory
::: Generating Debug Output
:::                                     :::
::              PiVPN Debug              ::
:::                                     :::
::      Latest Commit                    ::
:::                                     :::
commit b7be6549157df8ec05caebe19115fcdf1783b8f7
Author: Kaladin Light <0.kaladin@gmail.com>
Date:   Sat Dec 24 17:24:21 2016 -0500

    Version 1.9
:::                                     :::
::      Recursive list of files in       ::
::      /etc/openvpn/easy-rsa/pki        ::
:::                                     :::
ls: cannot access /etc/openvpn/easy-rsa/pki/: No such file or directory
:::                                     :::
::      Output of /etc/pivpn/*           ::
:::                                     :::
:: START /etc/pivpn/INSTALL_PORT ::
1194
:: END /etc/pivpn/INSTALL_PORT ::
:: START /etc/pivpn/INSTALL_PROTO ::
udp
:: END /etc/pivpn/INSTALL_PROTO ::
:::                                     :::
:: /etc/openvpn/easy-rsa/pki/Default.txt ::
:::                                     :::
cat: /etc/openvpn/easy-rsa/pki/Default.txt: No such file or directory
:::                                     :::
::      Debug Output Complete            ::
:::                                     :::
:::
::: Debug output completed above.
::: Copy saved to /tmp/debug.txt
:::
pi@raspberrypi:~ $

```

## Issue

I had to install git myself for that part of the install routine to work which did allow me to get pivpn scripts installed. Getting to that point required a bit of work so when i tried to "PIVPN add" and it reported issues on line 91 and 99 in the makeOVPN.sh I gave up......

I'm running a full updated/upgraded Raspbian on an RPi2.

Regards

**Comment by 0-kaladin** [comment] 2016-12-25 08:15
Looks like sdcard issues. Nothing was working. I'd reboot the pi. Apt-get update, Apt-get upgrade. 
Pivpn uninstall. 
Reboot. 
Then reinstall.

**Comment by GeekNathan** [comment] 2016-12-25 09:24
I did not mention it, but to be sure I completely rebuilt raspian and the issues reproduced exactly the same. I've had better luck using https://github.com/StarshipEngineer/OpenVPN-Setup

**Comment by 0-kaladin** [comment] 2016-12-25 12:19
Oh. Run the install as the root user. I prob missed some things as normal user.

**Comment by darkrain-nl** [comment] 2016-12-25 12:26
I tried reinstalling but it didn't work until I manually entered "sudo apt-het install openvpn git dhcpcd5 tar wget grep iptables-persistent dnsutils expect whiptail" after that started the install again andeverything worked as it should.
So in my opinion the problem is in the "install_dependent_packages" function.
I run a raspberry Pi 3 with Debian Jessie.

**Comment by 0-kaladin** [comment] 2016-12-25 23:07
Fixed committed.

**Closed by 0-kaladin** 2016-12-25 23:07 UTC

**Comment by GeekNathan** [comment] 2016-12-25 23:32
I'll give it another go, I have plenty of Pi's lying around....thanks Kaladin.

**Comment by award28** [comment] 2020-09-06 20:13
I ran into this same issue while trying to install pivpn on my octoprint raspberry pi.

For anyone else who runs into this same issue, I found that removing the `sudo git` sanity check before running the script allowed the installation to continue.

Probably not the best idea to completely remove this from your system, so I'd recommend moving it, and then moving it back when you're done 🙂

```bash
sudo mv /root/bin/git ~/git_sanity_check
curl -L install.pivpn.io | bash
sudo mv ~/git_sanity_check /root/bin/git
```
