### ISSUE TITLE
OpenVPN client ccd file error

### ISSUE THREAD

**Issue by liasom** [pivpn/pivpn#1614] opened 2022-09-04 13:49 UTC
### Discussed in https://github.com/pivpn/pivpn/discussions/1613

<div type='discussions-op-text'>

<sup>Originally posted by **liasom** September  4, 2022</sup>
New installations (today and yesterday) of OpenVPN on two separate Raspberry Pi computers. One is Pi Zero 1.3 with 32-bit Raspberry Pi OS lite and the other is Pi Zero 2 W with Pi OS 64-bit. This error happens on both. When I create a client ovpn profile the corresponding ccd file contains an error in having no space between the ip address and subnet. This content pasted in from one of the ccd files.

ifconfig-push 10.0.8.2255.255.255.0
</div>

**Comment by 4s3ti** [comment] 2022-09-04 13:51
duplicate of discussion no need for issue! I will open an issue with the correct details if needed.

**Closed by 4s3ti** 2022-09-04 13:51 UTC

**Comment by liasom** [comment] 2022-09-04 14:11
Thanks!
