### ISSUE TITLE
Raspberry pi Zero with an USB-Ethernet adapter.

### ISSUE THREAD

**Issue by xbian** [pivpn/pivpn#1018] opened 2020-04-14 14:51 UTC
- Below is the install run that went through.
::: sudo will be used for the install.
::: Hostname length OK
::: Verifying free disk space...
::: Checking apt-get for upgraded packages.... done!
::: Your system is up to date! Continuing with PiVPN installation...
::: Checking for git... already installed!
::: Checking for tar... already installed!
::: Checking for wget... already installed!
::: Checking for curl... already installed!
::: Checking for grep... already installed!
::: Checking for dnsutils... already installed!
::: Checking for whiptail... already installed!
::: Checking for net-tools... already installed!
::: Checking for bsdmainutils... already installed!
::: Checking for dhcpcd5... already installed!
::: Checking for iptables-persistent... already installed!
::: Could not find any active network interface, exiting

**Comment by shelleycat485** [comment] 2020-04-17 13:19
Raspberry-pi Zero-W with eth0 as USB adapter (and wlan0 active too) found interfaces with no problem.  /etc/debian-version 9.11.  eth0 is dhcp, wlan0 is static, both were seen by installer.

**Comment by xbian** [comment] 2020-04-17 13:29
mine is a Raspberry-pi Zero v1.3 with the camera connector, without w.

**Comment by shelleycat485** [comment] 2020-04-17 13:50
here is my ifconfig output, I know the scripts looks for some keywords in it like UP.
pi@raspbwplus:~ $ ifconfig
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.1.230  netmask 255.255.255.0  broadcast 192.168.1.255
        ether 00:ee:22:aa:17:34  txqueuelen 1000  (Ethernet)
        RX packets 50439  bytes 33225706 (31.6 MiB)
        RX errors 0  dropped 5  overruns 0  frame 0
        TX packets 6163  bytes 718819 (701.9 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 1  bytes 29 (29.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 1  bytes 29 (29.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

wg0: flags=209<UP,POINTOPOINT,RUNNING,NOARP>  mtu 1420
        inet 10.6.0.1  netmask 255.255.255.0  destination 10.6.0.1
        unspec 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  txqueuelen 1000  (UNSPEC)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

wlan0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.3.5  netmask 255.255.255.0  broadcast 192.168.3.255
        ether b8:27:eb:22:af:fb  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 70  bytes 12521 (12.2 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

**Comment by orazioedoardo** [comment] 2020-04-18 08:25
@shelleycat485 You are right, it looks for UP.

@xbian post the output of `ip a`

There is also a workaround here: https://github.com/pivpn/pivpn/issues/994#issuecomment-605494256

**Comment by xbian** [comment] 2020-04-18 08:36
```

$ ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UNKNOWN group default qlen 1000
    link/ether 9c:eb:e8:2c:c3:f7 brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.175/24 brd 192.168.1.255 scope global dynamic noprefixroute eth0
       valid_lft 82441sec preferred_lft 71641sec
    inet6 2a00:23c4:158c:a500:fbd1:fa96:7ab2:62f/64 scope global dynamic mngtmpaddr noprefixroute 
       valid_lft 21474809sec preferred_lft 21474809sec
    inet6 fdaa:bbcc:ddee:0:a1e5:13b8:48f7:7296/64 scope global mngtmpaddr noprefixroute 
       valid_lft forever preferred_lft forever
    inet6 fe80::a073:3f9c:65b3:dc9e/64 scope link 
       valid_lft forever preferred_lft forever

```

**Comment by orazioedoardo** [comment] 2020-04-18 08:38
Use this workaround: https://github.com/pivpn/pivpn/issues/994#issuecomment-605494256

**Comment by orazioedoardo** [comment] 2020-04-26 09:12
Most likely a duplicate of #994, maybe will add an option in the script like "Show all interfaces". In the meanwhile, closing... Reopen if different issue.

**Closed by orazioedoardo** 2020-04-26 09:12 UTC
Labels: Needs Investigation
