### ISSUE TITLE
Unable to connect to PiVPN

### ISSUE THREAD

**Issue by ZetiX** [pivpn/pivpn#643] opened 2018-11-17 02:38 UTC
# PiVPN Issue Template
Install is successful.
All links are pastebin.
I removed my ip address from logs containing them.

## Have you searched for similar issues and solutions? 
Yes, but none of them worked.
  

## Console output of `curl -L install.pivpn.io | bash`
```
https://pastebin.com/7EvKLvdh
```

## Console output of `pivpn add` or `pivpn add nopass`
```
https://pastebin.com/4TUVsTQr
```

## Console output of `pivpn debug`
```
https://pastebin.com/JTDxQ101
```

## Console Output of `sudo iptables -t nat -S`
```
https://pastebin.com/rRKR7JEQ
```

## Console Output of `sudo iptables -S`
```
https://pastebin.com/rH5QP83v
```

## output of `sudo netstat -uanp | grep openvpn`

```
https://pastebin.com/5RZXS5WV
```

## Have you taken any steps towards solving your issue? 
Tried googling, and came across [sudo systemctl status openvpn@server.service](https://pastebin.com/8QADLzwQ), but I don't have error output.

The user I'm putting pivpn on is connected by using my RSA passphrase as I have set up a key pair.
UFW is installed on the pi.
Port 1194 is forwarded to 192.168.1.10[static] which is my RPi3. It is also the only port open.
I have Pi-Hole Installed, so I changed the listen-address in dnsmasq to 127.0.0.1, 192.168.1.10, 10.8.0.1

[Here is the output of my iPhone.](https://pastebin.com/9fVNAnvZ)

**Comment by orazioedoardo** [comment] 2018-11-17 08:35
Looks like the script haven’t added proper ufw rules, might be a bug. Post the outpout of `sudo ufw status verbose`. Also, can you confirm that you chose port 1194 with protocol UDP from the wizard?

**Comment by orazioedoardo** [comment] 2018-11-18 08:16
Can you temporary disable ufw and check if it works? `sudo ufw enable`

**Comment by ZetiX** [comment] 2018-11-18 19:53
`/var/log/openvpn.log` was empty, but here's the log for [/var/log/openvpn.log.1](https://pastebin.com/Rdgd20Es)

[/var/log/ufw.log](https://pastebin.com/fn3fyZdx)

**Comment by orazioedoardo** [comment] 2018-11-22 10:31
Sorry for the delay, here's what I can tell as of now:
1) OpenVPN is indeed running, port is listening and log confirms that there are no errors.
2) Ufw is configured correctly to allow incoming connections from port 1194/udp and from the vpn network (10.8.0.0/24). Also logs confirm that it's not blocking connections to the port.
3) I don't think fail2ban plays a role here since it should only affect ssh.

However, the `sudo iptables -S` and `sudo ufw status verbose` show conflicting results. For example ufw says that routed (forwarded) connections are allowed but iptables shows that the FORWARD policy is set to drop. Port 1194 is present on ufw but not on iptables. Looks like ufw rules are not actually being used.

First, try to reload them: `sudo ufw reload` and try to connect. If it still doesn't work, we could temporary reset the firewall:
```
sudo iptables -P INPUT ACCEPT
sudo iptables -P FORWARD ACCEPT
sudo iptables -P OUTPUT ACCEPT
sudo iptables -F
sudo iptables -X
```
If it's a firewall issue this should at least allow you to connect to the server (by the way, are you connecting from a different network?)
If it doesn't work, just reboot and we'll try something else.

**Comment by orazioedoardo** [comment] 2018-11-23 08:51
I’m not sure if I understand your question. Do you want to access your LAN devices (192.168.1.0/24) from a VPN client? You can already do it.

**Comment by ZetiX** [comment] 2018-11-23 18:54
Unfortunately it doesn’t appear that I can, which is why I’m a bit confused.

**Comment by ZetiX** [comment] 2018-11-25 08:08
[openvpn](https://pastebin.com/5mVHfwqE)

[ufw](https://pastebin.com/HXKWVTuz)

[iptables](https://pastebin.com/SW2tyQua)

The ip is the same as my home ip, but I'm able to access my router page. However I'm unable to access the network storage, and my windows media connection.

**Comment by orazioedoardo** [comment] 2018-11-25 09:04
The fact that web browsing works and that you can access your router web page makes me think that the issue is about the network storage itself.

What protocol are you using to connect to it? Are you trying to access via local dns name (e.g. mynas.local) or via IP?

**Comment by sbrl** [comment] 2018-12-28 21:36
Hey! I think I've run into this bug myself. Here are my observations:

 - Executing `sudo ufw reload` fixes the issue.
 - Rebooting causes the issue to crop up again.

I'm running on a Raspberry Pi 3 with _Raspbian 9.6 (stretch)_.

Here's an extract from `/var/log/ufw.log` just after a reboot:

```
Dec 28 20:58:45 SERVER_NAME kernel: [50042.744362] [UFW BLOCK] IN=eth0 OUT= MAC=************** SRC=****CLIENT_PUBLIC_IP***** DST=****SERVER_PRIVATE_IP**** LEN=82 TOS=0x00 PREC=0x00 TTL=52 ID=53404 DF PROTO=UDP SPT=59252 DPT=1194 LEN=62
```

Upon executing `sudo ufw reload`, the VPN then works.

# Steps to reproduce
1. Enable UFW
2. Install & setup PiVPN
3. Wonder why it's not working - and then remember you need to allow it through ufw (execute `sudo ufw allow 1194/udp`)
4. Observe the OpenVPN server working & accepting clients
5. Reboot the server.
6. Observe the OpenVPN server _not_ working. Check `/var/log/ufw.log` for evidence that UFW is blocking packets
7. Execute `sudo ufw reload`
8. Observe the OpenVPN server working again.

Is there any fix for this?

**Comment by stonehippo** [comment] 2019-01-01 06:32
I have found the same issue that @sbrl describes: `blocks my OpenVPN port on reboot until I do `sudo ufw reload`.

**Comment by orazioedoardo** [comment] 2019-01-01 08:46
@sbrl and @stonehippo what's the output of `cat /etc/pivpn/NO_UFW`?

**Comment by stonehippo** [comment] 2019-01-01 15:16
@orazioedoardo for me, it's 

```
0
```

ufw was already installed and running when I installed pivpn.

**Comment by stonehippo** [comment] 2019-01-01 15:21
@orazioedoardo here's the contents of `cat /etc/pivpn/install.log`, too:

```
:::
::: Stopping OpenVPN service... done.
:::   
::: Installing scripts to /opt/pivpn... done.
::: Using protocol: udp
set_var EASYRSA_ALGO       ec
set_var EASYRSA_CURVE      prime256v1
::: Building CA...

::: CA Complete.

Note: using Easy-RSA configuration from: ./vars

Note: using Easy-RSA configuration from: ./vars

An updated CRL has been created.
CRL file: /etc/openvpn/easy-rsa/pki/crl.pem

net.ipv4.ip_forward = 1
::: Detected UFW is enabled.
::: Adding UFW rules...
Rule added
Rule added (v6)
Rule added
Firewall reloaded
::: UFW configuration completed.
::: Using Google servers.
```

**Comment by orazioedoardo** [comment] 2019-01-08 06:51
@sbrl @stonehippo Looks like ufw does not apply rules on reboot, what's the output of `sudo systemctl status ufw`?

Reboot and post the output of `sudo ufw status verbose` (do not issue a reload first).

**Comment by sbrl** [comment] 2019-01-08 18:23
@orazioedoardo Thanks for the reply. Here's the output of those commands after a reboot:

```
$ sudo systemctl status ufw
[sudo] password for pi: 
● ufw.service - Uncomplicated firewall
   Loaded: loaded (/lib/systemd/system/ufw.service; enabled; vendor preset: enab
   Active: active (exited) since Tue 2019-01-08 18:22:20 GMT; 50s ago
     Docs: man:ufw(8)
  Process: 99 ExecStart=/lib/ufw/ufw-init start quiet (code=exited, status=0/SUC
 Main PID: 99 (code=exited, status=0/SUCCESS)
   CGroup: /system.slice/ufw.service

Jan 08 18:22:20 elessar systemd[1]: Started Uncomplicated firewall.
Warning: Journal has been rotated since unit was started. Log output is incomple
$ sudo ufw status verbose
Status: active
Logging: on (low)
Default: deny (incoming), allow (outgoing), allow (routed)
New profiles: skip

To                         Action      From
--                         ------      ----
2568/tcp                   ALLOW IN    Anywhere                   # ssh
137,138/udp (CIFS)         ALLOW IN    Anywhere                  
139,445/tcp (CIFS)         ALLOW IN    Anywhere                  
22000/tcp (syncthing)      ALLOW IN    Anywhere                  
21027/udp (syncthing)      ALLOW IN    Anywhere                  
8384/tcp (syncthing-gui)   ALLOW IN    Anywhere                  
25826/udp (collectd)       ALLOW IN    Anywhere                  
30000/udp (minetest)       ALLOW IN    Anywhere                  
123/udp (ntpd)             ALLOW IN    Anywhere                  
111,2049/tcp (NFS)         ALLOW IN    Anywhere                  
111,2049/udp (NFS)         ALLOW IN    Anywhere                  
80/tcp (proto-http)        ALLOW IN    Anywhere                  
443/tcp (proto-https)      ALLOW IN    Anywhere                  
69/udp (tftpd)             ALLOW IN    Anywhere                  
631 (CUPS)                 ALLOW IN    Anywhere                  
161/udp                    ALLOW IN    172.16.230.56              # snmp
162/udp                    ALLOW IN    Anywhere                   # snmp-trap
Anywhere                   ALLOW IN    10.8.0.0/24               
1194/udp                   ALLOW IN    Anywhere                   # OpenVPN
2568/tcp (v6)              ALLOW IN    Anywhere (v6)              # ssh
137,138/udp (CIFS (v6))    ALLOW IN    Anywhere (v6)             
139,445/tcp (CIFS (v6))    ALLOW IN    Anywhere (v6)             
22000/tcp (syncthing (v6)) ALLOW IN    Anywhere (v6)             
21027/udp (syncthing (v6)) ALLOW IN    Anywhere (v6)             
8384/tcp (syncthing-gui (v6)) ALLOW IN    Anywhere (v6)             
25826/udp (collectd (v6))  ALLOW IN    Anywhere (v6)             
30000/udp (minetest (v6))  ALLOW IN    Anywhere (v6)             
123/udp (ntpd (v6))        ALLOW IN    Anywhere (v6)             
111,2049/tcp (NFS (v6))    ALLOW IN    Anywhere (v6)             
111,2049/udp (NFS (v6))    ALLOW IN    Anywhere (v6)             
80/tcp (proto-http (v6))   ALLOW IN    Anywhere (v6)             
443/tcp (proto-https (v6)) ALLOW IN    Anywhere (v6)             
69/udp (tftpd (v6))        ALLOW IN    Anywhere (v6)             
631 (CUPS (v6))            ALLOW IN    Anywhere (v6)             
162/udp (v6)               ALLOW IN    Anywhere (v6)              # snmp-trap
1194/udp (v6)              ALLOW IN    Anywhere (v6)              # OpenVPN


```

**Comment by orazioedoardo** [comment] 2019-01-08 20:34
So, ufw still has the rule but let’s check if it gets passed to iptables as well: `sudo iptables -vnL ufw-user-input`, `sudo iptables -vnL -t nat` and `sudo iptables -S | grep ^-P`.

**Comment by sbrl** [comment] 2019-01-11 00:41
```
$ sudo iptables -vnL ufw-user-input
Chain ufw-user-input (1 references)
 pkts bytes target     prot opt in     out     source               destination         
    1    60 ACCEPT     tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            tcp dpt:2568
   45  5971 ACCEPT     udp  --  *      *       0.0.0.0/0            0.0.0.0/0            multiport dports 137,138 /* 'dapp_CIFS' */
    0     0 ACCEPT     tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            multiport dports 139,445 /* 'dapp_CIFS' */
    1    60 ACCEPT     tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            tcp dpt:22000 /* 'dapp_syncthing' */
    1   315 ACCEPT     udp  --  *      *       0.0.0.0/0            0.0.0.0/0            udp dpt:21027 /* 'dapp_syncthing' */
    0     0 ACCEPT     tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            tcp dpt:8384 /* 'dapp_syncthing-gui' */
    0     0 ACCEPT     udp  --  *      *       0.0.0.0/0            0.0.0.0/0            udp dpt:25826 /* 'dapp_collectd' */
    0     0 ACCEPT     udp  --  *      *       0.0.0.0/0            0.0.0.0/0            udp dpt:30000 /* 'dapp_minetest' */
    0     0 ACCEPT     udp  --  *      *       0.0.0.0/0            0.0.0.0/0            udp dpt:123 /* 'dapp_ntpd' */
    1    60 ACCEPT     tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            multiport dports 111,2049 /* 'dapp_NFS' */
    0     0 ACCEPT     udp  --  *      *       0.0.0.0/0            0.0.0.0/0            multiport dports 111,2049 /* 'dapp_NFS' */
    0     0 ACCEPT     tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            tcp dpt:80 /* 'dapp_proto-http' */
    0     0 ACCEPT     tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            tcp dpt:443 /* 'dapp_proto-https' */
    0     0 ACCEPT     udp  --  *      *       0.0.0.0/0            0.0.0.0/0            udp dpt:69 /* 'dapp_tftpd' */
    1    60 ACCEPT     tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            tcp dpt:631 /* 'dapp_CUPS' */
    0     0 ACCEPT     udp  --  *      *       0.0.0.0/0            0.0.0.0/0            udp dpt:631 /* 'dapp_CUPS' */
    0     0 ACCEPT     udp  --  *      *       172.16.230.56        0.0.0.0/0            udp dpt:161
    0     0 ACCEPT     udp  --  *      *       0.0.0.0/0            0.0.0.0/0            udp dpt:162
$ sudo iptables -vnL -t nat
Chain PREROUTING (policy ACCEPT 12 packets, 1225 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain INPUT (policy ACCEPT 8 packets, 1009 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain OUTPUT (policy ACCEPT 25 packets, 2616 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain POSTROUTING (policy ACCEPT 25 packets, 2616 bytes)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 MASQUERADE  all  --  *      eth0    10.8.0.0/24          0.0.0.0/0           
$ sudo iptables -S | grep ^-P
-P INPUT DROP
-P FORWARD DROP
-P OUTPUT ACCEPT
```

**Comment by orazioedoardo** [comment] 2019-01-12 14:21
Basically ufw shows the rules inside its output but they are not passed to iptables. Let’s check whether you actually have the rules on disk with `sudo cat /etc/ufw/user.rules` and `sudo /etc/ufw/before.rules`

**Comment by sbrl** [comment] 2019-01-12 14:59
This is after a `sudo ufw reload`:

```
$ sudo cat /etc/ufw/user.rules
[sudo] password for pi: 
*filter
:ufw-user-input - [0:0]
:ufw-user-output - [0:0]
:ufw-user-forward - [0:0]
:ufw-before-logging-input - [0:0]
:ufw-before-logging-output - [0:0]
:ufw-before-logging-forward - [0:0]
:ufw-user-logging-input - [0:0]
:ufw-user-logging-output - [0:0]
:ufw-user-logging-forward - [0:0]
:ufw-after-logging-input - [0:0]
:ufw-after-logging-output - [0:0]
:ufw-after-logging-forward - [0:0]
:ufw-logging-deny - [0:0]
:ufw-logging-allow - [0:0]
:ufw-user-limit - [0:0]
:ufw-user-limit-accept - [0:0]
### RULES ###

### tuple ### allow tcp 2568 0.0.0.0/0 any 0.0.0.0/0 in comment=737368
-A ufw-user-input -p tcp --dport 2568 -j ACCEPT

### tuple ### allow udp 137,138 0.0.0.0/0 any 0.0.0.0/0 CIFS - in
-A ufw-user-input -p udp -m multiport --dports 137,138 -j ACCEPT -m comment --comment 'dapp_CIFS'

### tuple ### allow tcp 139,445 0.0.0.0/0 any 0.0.0.0/0 CIFS - in
-A ufw-user-input -p tcp -m multiport --dports 139,445 -j ACCEPT -m comment --comment 'dapp_CIFS'

### tuple ### allow tcp 22000 0.0.0.0/0 any 0.0.0.0/0 syncthing - in
-A ufw-user-input -p tcp --dport 22000 -j ACCEPT -m comment --comment 'dapp_syncthing'

### tuple ### allow udp 21027 0.0.0.0/0 any 0.0.0.0/0 syncthing - in
-A ufw-user-input -p udp --dport 21027 -j ACCEPT -m comment --comment 'dapp_syncthing'

### tuple ### allow tcp 8384 0.0.0.0/0 any 0.0.0.0/0 syncthing-gui - in
-A ufw-user-input -p tcp --dport 8384 -j ACCEPT -m comment --comment 'dapp_syncthing-gui'

### tuple ### allow udp 25826 0.0.0.0/0 any 0.0.0.0/0 collectd - in
-A ufw-user-input -p udp --dport 25826 -j ACCEPT -m comment --comment 'dapp_collectd'

### tuple ### allow udp 30000 0.0.0.0/0 any 0.0.0.0/0 minetest - in
-A ufw-user-input -p udp --dport 30000 -j ACCEPT -m comment --comment 'dapp_minetest'

### tuple ### allow udp 123 0.0.0.0/0 any 0.0.0.0/0 ntpd - in
-A ufw-user-input -p udp --dport 123 -j ACCEPT -m comment --comment 'dapp_ntpd'

### tuple ### allow tcp 111,2049 0.0.0.0/0 any 0.0.0.0/0 NFS - in
-A ufw-user-input -p tcp -m multiport --dports 111,2049 -j ACCEPT -m comment --comment 'dapp_NFS'

### tuple ### allow udp 111,2049 0.0.0.0/0 any 0.0.0.0/0 NFS - in
-A ufw-user-input -p udp -m multiport --dports 111,2049 -j ACCEPT -m comment --comment 'dapp_NFS'

### tuple ### allow tcp 80 0.0.0.0/0 any 0.0.0.0/0 proto-http - in
-A ufw-user-input -p tcp --dport 80 -j ACCEPT -m comment --comment 'dapp_proto-http'

### tuple ### allow tcp 443 0.0.0.0/0 any 0.0.0.0/0 proto-https - in
-A ufw-user-input -p tcp --dport 443 -j ACCEPT -m comment --comment 'dapp_proto-https'

### tuple ### allow udp 69 0.0.0.0/0 any 0.0.0.0/0 tftpd - in
-A ufw-user-input -p udp --dport 69 -j ACCEPT -m comment --comment 'dapp_tftpd'

### tuple ### allow any 631 0.0.0.0/0 any 0.0.0.0/0 CUPS - in
-A ufw-user-input -p tcp --dport 631 -j ACCEPT -m comment --comment 'dapp_CUPS'
-A ufw-user-input -p udp --dport 631 -j ACCEPT -m comment --comment 'dapp_CUPS'

### tuple ### allow udp 161 0.0.0.0/0 any 172.16.230.56 in comment=736e6d70
-A ufw-user-input -p udp --dport 161 -s 172.16.230.56 -j ACCEPT

### tuple ### allow udp 162 0.0.0.0/0 any 0.0.0.0/0 in comment=736e6d702d74726170
-A ufw-user-input -p udp --dport 162 -j ACCEPT

### tuple ### allow any any 0.0.0.0/0 any 10.8.0.0/24 in
-A ufw-user-input -s 10.8.0.0/24 -j ACCEPT

### tuple ### allow udp 1194 0.0.0.0/0 any 0.0.0.0/0 in comment=4f70656e56504e
-A ufw-user-input -p udp --dport 1194 -j ACCEPT

### END RULES ###

### LOGGING ###
-A ufw-after-logging-input -j LOG --log-prefix "[UFW BLOCK] " -m limit --limit 3/min --limit-burst 10
-I ufw-logging-deny -m conntrack --ctstate INVALID -j RETURN -m limit --limit 3/min --limit-burst 10
-A ufw-logging-deny -j LOG --log-prefix "[UFW BLOCK] " -m limit --limit 3/min --limit-burst 10
-A ufw-logging-allow -j LOG --log-prefix "[UFW ALLOW] " -m limit --limit 3/min --limit-burst 10
### END LOGGING ###

### RATE LIMITING ###
-A ufw-user-limit -m limit --limit 3/minute -j LOG --log-prefix "[UFW LIMIT BLOCK] "
-A ufw-user-limit -j REJECT
-A ufw-user-limit-accept -j ACCEPT
### END RATE LIMITING ###
COMMIT
$ sudo cat /etc/ufw/before.rules
#
# rules.before
#
# Rules that should be run before the ufw command line added rules. Custom
# rules should be added to one of these chains:
#   ufw-before-input
#   ufw-before-output
#   ufw-before-forward
#

# START OPENVPN RULES
# NAT table rules
*nat
:POSTROUTING ACCEPT [0:0] 
# Allow traffic from OpenVPN client to masquerade 
-A POSTROUTING -s 10.8.0.0/24 -o eth0 -j MASQUERADE
COMMIT
# END OPENVPN RULES

# Don't delete these required lines, otherwise there will be errors
*filter
:ufw-before-input - [0:0]
:ufw-before-output - [0:0]
:ufw-before-forward - [0:0]
:ufw-not-local - [0:0]
# End required lines


# allow all on loopback
-A ufw-before-input -i lo -j ACCEPT
-A ufw-before-output -o lo -j ACCEPT

# quickly process packets for which we already have a connection
-A ufw-before-input -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A ufw-before-output -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A ufw-before-forward -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT

# drop INVALID packets (logs these in loglevel medium and higher)
-A ufw-before-input -m conntrack --ctstate INVALID -j ufw-logging-deny
-A ufw-before-input -m conntrack --ctstate INVALID -j DROP

# ok icmp codes for INPUT
-A ufw-before-input -p icmp --icmp-type destination-unreachable -j ACCEPT
-A ufw-before-input -p icmp --icmp-type source-quench -j ACCEPT
-A ufw-before-input -p icmp --icmp-type time-exceeded -j ACCEPT
-A ufw-before-input -p icmp --icmp-type parameter-problem -j ACCEPT
-A ufw-before-input -p icmp --icmp-type echo-request -j ACCEPT

# ok icmp code for FORWARD
-A ufw-before-forward -p icmp --icmp-type destination-unreachable -j ACCEPT
-A ufw-before-forward -p icmp --icmp-type source-quench -j ACCEPT
-A ufw-before-forward -p icmp --icmp-type time-exceeded -j ACCEPT
-A ufw-before-forward -p icmp --icmp-type parameter-problem -j ACCEPT
-A ufw-before-forward -p icmp --icmp-type echo-request -j ACCEPT

# allow dhcp client to work
-A ufw-before-input -p udp --sport 67 --dport 68 -j ACCEPT

#
# ufw-not-local
#
-A ufw-before-input -j ufw-not-local

# if LOCAL, RETURN
-A ufw-not-local -m addrtype --dst-type LOCAL -j RETURN

# if MULTICAST, RETURN
-A ufw-not-local -m addrtype --dst-type MULTICAST -j RETURN

# if BROADCAST, RETURN
-A ufw-not-local -m addrtype --dst-type BROADCAST -j RETURN

# all other non-local packets are dropped
-A ufw-not-local -m limit --limit 3/min --limit-burst 10 -j ufw-logging-deny
-A ufw-not-local -j DROP

# allow MULTICAST mDNS for service discovery (be sure the MULTICAST line above
# is uncommented)
-A ufw-before-input -p udp -d 224.0.0.251 --dport 5353 -j ACCEPT

# allow MULTICAST UPnP for service discovery (be sure the MULTICAST line above
# is uncommented)
-A ufw-before-input -p udp -d 239.255.255.250 --dport 1900 -j ACCEPT

# don't delete the 'COMMIT' line or these rules won't be processed
COMMIT
```

**Comment by 4s3ti** [comment] 2019-05-26 13:17
I will be closing this issue as it seems not to be related with PiVPN itself. 

If you still want to keep this thread, feel free to reopen it and will gladly try to help out!

**Closed by 4s3ti** 2019-05-26 13:17 UTC

**Comment by sbrl** [comment] 2019-05-26 16:54
I see, @4s3ti. Currently I'm still using the workaround of reloading the ufw configuration in `/etc/rc.local`. If it's not an issue with PiVPN, then who should I get in touch with to resolve the issue?

**Comment by raul-valadez** [comment] 2019-08-26 03:45
Hi @sbrl, this will fix your problem:

sudo apt remove iptables-persistent
sudo apt autoremove

That fix it for me, before I had to restart every time ufw for my pivpn to works at every boot, after remove iptables-persistent, everything worked like a charm!

Best Regards.

**Comment by sbrl** [comment] 2019-08-28 11:20
@raul-valadez I see, thanks. `iptables-persistent` sounds like an important package though, so I'm not what side-effects removing it might have.

**Comment by sbrl** [comment] 2019-08-31 11:59
Ah, I see! Thanks for clarifying. I'll give it a go if I have some time.
